// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {apikey} from '../models';

export function CreateAPIKey(arg1:apikey.CreateParams):Promise<apikey.CreateResult>;

export function ListAPIKeys():Promise<Array<apikey.APIKeyEntry>>;

export function RevokeAPIKey(arg1:string):Promise<void>;

export function RotateAPIKey(arg1:string):Promise<apikey.CreateResult>;

export function SetAPIKeyRoles(arg1:string,arg2:Array<string>):Promise<void>;
