// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateAPIKey(arg1) {
  return window['go']['apikey']['APIKey']['CreateAPIKey'](arg1);
}

export function ListAPIKeys() {
  return window['go']['apikey']['APIKey']['ListAPIKeys']();
}

export function RevokeAPIKey(arg1) {
  return window['go']['apikey']['APIKey']['RevokeAPIKey'](arg1);
}

export function RotateAPIKey(arg1) {
  return window['go']['apikey']['APIKey']['RotateAPIKey'](arg1);
}

export function SetAPIKeyRoles(arg1, arg2) {
  return window['go']['apikey']['APIKey']['SetAPIKeyRoles'](arg1, arg2);
}
