// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddPermission(arg1) {
  return window['go']['role']['Role']['AddPermission'](arg1);
}

export function AssignUserToRole(arg1, arg2) {
  return window['go']['role']['Role']['AssignUserToRole'](arg1, arg2);
}

export function CreateRole(arg1) {
  return window['go']['role']['Role']['CreateRole'](arg1);
}

export function DeleteRole(arg1) {
  return window['go']['role']['Role']['DeleteRole'](arg1);
}

export function DuplicateRole(arg1) {
  return window['go']['role']['Role']['DuplicateRole'](arg1);
}

export function GetMyPermissions() {
  return window['go']['role']['Role']['GetMyPermissions']();
}

export function ListPermissions(arg1) {
  return window['go']['role']['Role']['ListPermissions'](arg1);
}

export function ListRoles() {
  return window['go']['role']['Role']['ListRoles']();
}

export function ListUsersInRole(arg1) {
  return window['go']['role']['Role']['ListUsersInRole'](arg1);
}

export function RemovePermission(arg1) {
  return window['go']['role']['Role']['RemovePermission'](arg1);
}

export function RemoveUserFromRole(arg1) {
  return window['go']['role']['Role']['RemoveUserFromRole'](arg1);
}

export function RenameRole(arg1, arg2) {
  return window['go']['role']['Role']['RenameRole'](arg1, arg2);
}
