// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {role} from '../models';
import {generated} from '../models';
import {core} from '../models';

export function AddPermission(arg1:role.AddPermissionParams):Promise<role.PermissionEntry>;

export function AssignUserToRole(arg1:string,arg2:string):Promise<void>;

export function CreateRole(arg1:string):Promise<generated.Role>;

export function DeleteRole(arg1:string):Promise<void>;

export function DuplicateRole(arg1:string):Promise<generated.Role>;

export function GetMyPermissions():Promise<Array<core.PermissionEntry>>;

export function ListPermissions(arg1:string):Promise<Array<role.PermissionEntry>>;

export function ListRoles():Promise<Array<generated.ListRolesByWorkspaceRow>>;

export function ListUsersInRole(arg1:string):Promise<Array<role.RoleUserEntry>>;

export function RemovePermission(arg1:string):Promise<void>;

export function RemoveUserFromRole(arg1:string):Promise<void>;

export function RenameRole(arg1:string,arg2:string):Promise<void>;
