// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {server} from '../models';

export function CreateServer(arg1:string):Promise<void>;

export function GetCurrentServer():Promise<string>;

export function GetDefaultServer():Promise<string>;

export function GetServerManifest(arg1:string):Promise<server.Manifest>;

export function ListServers():Promise<Array<string>>;

export function RemoveServer(arg1:string):Promise<void>;

export function SetCurrentServer(arg1:string):Promise<void>;
