// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateServer(arg1) {
  return window['go']['server']['Server']['CreateServer'](arg1);
}

export function GetCurrentServer() {
  return window['go']['server']['Server']['GetCurrentServer']();
}

export function GetDefaultServer() {
  return window['go']['server']['Server']['GetDefaultServer']();
}

export function GetServerManifest(arg1) {
  return window['go']['server']['Server']['GetServerManifest'](arg1);
}

export function ListServers() {
  return window['go']['server']['Server']['ListServers']();
}

export function RemoveServer(arg1) {
  return window['go']['server']['Server']['RemoveServer'](arg1);
}

export function SetCurrentServer(arg1) {
  return window['go']['server']['Server']['SetCurrentServer'](arg1);
}
