// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * CacheStats represents cache/buffer statistics from explain plans.
 */
export class CacheStats {
    "sharedHitBlocks"?: number | null;
    "sharedReadBlocks"?: number | null;
    "sharedDirtiedBlocks"?: number | null;
    "sharedWrittenBlocks"?: number | null;
    "tempReadBlocks"?: number | null;
    "tempWriteBlocks"?: number | null;
    "localHitBlocks"?: number | null;
    "localReadBlocks"?: number | null;
    "localDirtiedBlocks"?: number | null;
    "localWrittenBlocks"?: number | null;

    /**
     * Formatted display strings (computed in backend)
     */
    "sharedHitBlocksFormatted"?: string | null;
    "sharedReadBlocksFormatted"?: string | null;
    "tempReadBlocksFormatted"?: string | null;
    "tempWriteBlocksFormatted"?: string | null;

    /** Creates a new CacheStats instance. */
    constructor($$source: Partial<CacheStats> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CacheStats instance from a string or object.
     */
    static createFrom($$source: any = {}): CacheStats {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CacheStats($$parsedSource as Partial<CacheStats>);
    }
}

/**
 * CandidateType represents the type of a completion suggestion
 */
export enum CandidateType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    CandidateTypeKeyword = 1,
    CandidateTypeSchema = 2,
    CandidateTypeTable = 3,
    CandidateTypeForeignTable = 4,
    CandidateTypeView = 5,
    CandidateTypeMaterializedView = 6,
    CandidateTypeColumn = 7,
    CandidateTypeOperator = 8,
    CandidateTypeType = 9,
    CandidateTypeFunction = 10,
    CandidateTypeEnumValue = 11,
    CandidateTypeSetting = 12,
};

/**
 * Column represents a column in a table or CTE
 */
export class Column {
    "Name": string;

    /**
     * Native column type e.g. varchar(255), int4, timestamptz
     */
    "Type": string;
    "Nullable": boolean;

    /**
     * Default value expression, nil if none
     */
    "Default": string | null;
    "IsPrimaryKey": boolean;
    "IsForeignKey": boolean;

    /**
     * Set only when IsForeignKey is true
     */
    "ForeignKey": ForeignKeyRef | null;

    /**
     * EnumValues holds the allowed values when the column is an enumerated
     * type (PG native enum, MySQL enum/set). Resolved once by
     * EnrichEnumValues; nil for every other type. Single source of truth
     * for the cell editor and the enum lint rule.
     */
    "EnumValues": string[];

    /**
     * Dialect-specific metadata not covered above (optional)
     */
    "Extra": { [_ in string]?: any };

    /**
     * Description is the column COMMENT, if any. Used for hover docs and as the
     * carrier for schema-driven codegen annotations.
     */
    "Description"?: string;

    /** Creates a new Column instance. */
    constructor($$source: Partial<Column> = {}) {
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Type" in $$source)) {
            this["Type"] = "";
        }
        if (!("Nullable" in $$source)) {
            this["Nullable"] = false;
        }
        if (!("Default" in $$source)) {
            this["Default"] = null;
        }
        if (!("IsPrimaryKey" in $$source)) {
            this["IsPrimaryKey"] = false;
        }
        if (!("IsForeignKey" in $$source)) {
            this["IsForeignKey"] = false;
        }
        if (!("ForeignKey" in $$source)) {
            this["ForeignKey"] = null;
        }
        if (!("EnumValues" in $$source)) {
            this["EnumValues"] = [];
        }
        if (!("Extra" in $$source)) {
            this["Extra"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Column instance from a string or object.
     */
    static createFrom($$source: any = {}): Column {
        const $$createField6_0 = $$createType1;
        const $$createField7_0 = $$createType2;
        const $$createField8_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ForeignKey" in $$parsedSource) {
            $$parsedSource["ForeignKey"] = $$createField6_0($$parsedSource["ForeignKey"]);
        }
        if ("EnumValues" in $$parsedSource) {
            $$parsedSource["EnumValues"] = $$createField7_0($$parsedSource["EnumValues"]);
        }
        if ("Extra" in $$parsedSource) {
            $$parsedSource["Extra"] = $$createField8_0($$parsedSource["Extra"]);
        }
        return new Column($$parsedSource as Partial<Column>);
    }
}

/**
 * ExplainNode is the dialect-agnostic representation of a plan node.
 */
export class ExplainNode {
    "id": string;
    "type": NodeType;
    "operation": string;
    "targetTable"?: string | null;
    "indexName"?: string | null;
    "condition"?: string | null;
    "sortKey"?: string[];
    "estimatedRows"?: number | null;
    "estimatedCost"?: number | null;

    /**
     * Cost excluding children
     */
    "exclusiveCost"?: number | null;
    "actualRows"?: number | null;

    /**
     * Total time (including children)
     */
    "actualTime"?: number | null;

    /**
     * Time excluding children
     */
    "exclusiveTime"?: number | null;

    /**
     * Peak memory usage in KB
     */
    "peakMemory"?: number | null;
    "children": (ExplainNode | null)[];
    "metadata": { [_ in string]?: any };
    "rawOutput"?: string | null;
    "depth": number;
    "percentOfTotal": number;
    "warnings": string[];
    "cacheStats"?: CacheStats | null;

    /** Creates a new ExplainNode instance. */
    constructor($$source: Partial<ExplainNode> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = NodeType.$zero;
        }
        if (!("operation" in $$source)) {
            this["operation"] = "";
        }
        if (!("children" in $$source)) {
            this["children"] = [];
        }
        if (!("metadata" in $$source)) {
            this["metadata"] = {};
        }
        if (!("depth" in $$source)) {
            this["depth"] = 0;
        }
        if (!("percentOfTotal" in $$source)) {
            this["percentOfTotal"] = 0;
        }
        if (!("warnings" in $$source)) {
            this["warnings"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExplainNode instance from a string or object.
     */
    static createFrom($$source: any = {}): ExplainNode {
        const $$createField6_0 = $$createType2;
        const $$createField14_0 = $$createType6;
        const $$createField15_0 = $$createType3;
        const $$createField19_0 = $$createType2;
        const $$createField20_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sortKey" in $$parsedSource) {
            $$parsedSource["sortKey"] = $$createField6_0($$parsedSource["sortKey"]);
        }
        if ("children" in $$parsedSource) {
            $$parsedSource["children"] = $$createField14_0($$parsedSource["children"]);
        }
        if ("metadata" in $$parsedSource) {
            $$parsedSource["metadata"] = $$createField15_0($$parsedSource["metadata"]);
        }
        if ("warnings" in $$parsedSource) {
            $$parsedSource["warnings"] = $$createField19_0($$parsedSource["warnings"]);
        }
        if ("cacheStats" in $$parsedSource) {
            $$parsedSource["cacheStats"] = $$createField20_0($$parsedSource["cacheStats"]);
        }
        return new ExplainNode($$parsedSource as Partial<ExplainNode>);
    }
}

/**
 * ForeignKeyRef describes the referenced table and column for a foreign key.
 * Present only when the column is part of a foreign key constraint.
 */
export class ForeignKeyRef {
    "SchemaName": string;
    "TableName": string;
    "ColumnName": string;

    /** Creates a new ForeignKeyRef instance. */
    constructor($$source: Partial<ForeignKeyRef> = {}) {
        if (!("SchemaName" in $$source)) {
            this["SchemaName"] = "";
        }
        if (!("TableName" in $$source)) {
            this["TableName"] = "";
        }
        if (!("ColumnName" in $$source)) {
            this["ColumnName"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ForeignKeyRef instance from a string or object.
     */
    static createFrom($$source: any = {}): ForeignKeyRef {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ForeignKeyRef($$parsedSource as Partial<ForeignKeyRef>);
    }
}

/**
 * Function is a callable routine (from introspection).
 */
export class Function {
    "schema": string;
    "name": string;
    "args": string;
    "result": string;
    "kind": string;
    "description"?: string;
    "oid": number;

    /** Creates a new Function instance. */
    constructor($$source: Partial<Function> = {}) {
        if (!("schema" in $$source)) {
            this["schema"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("args" in $$source)) {
            this["args"] = "";
        }
        if (!("result" in $$source)) {
            this["result"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("oid" in $$source)) {
            this["oid"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Function instance from a string or object.
     */
    static createFrom($$source: any = {}): Function {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Function($$parsedSource as Partial<Function>);
    }
}

/**
 * IndexColumnInfo represents a column in an index (dialect-agnostic)
 * Fields are optional where not all databases support them
 */
export class IndexColumnInfo {
    "Name": string;

    /**
     * Position/order of column in the index (1-based, similar to SeqNo)
     */
    "Position": number;

    /**
     * Collation name if specified (empty if not applicable)
     */
    "Collation": string;

    /**
     * Whether column is ordered descending (false = ascending/default)
     */
    "Descending": boolean;

    /** Creates a new IndexColumnInfo instance. */
    constructor($$source: Partial<IndexColumnInfo> = {}) {
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Position" in $$source)) {
            this["Position"] = 0;
        }
        if (!("Collation" in $$source)) {
            this["Collation"] = "";
        }
        if (!("Descending" in $$source)) {
            this["Descending"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IndexColumnInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): IndexColumnInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new IndexColumnInfo($$parsedSource as Partial<IndexColumnInfo>);
    }
}

/**
 * IndexInfo represents an index in the database (dialect-agnostic)
 */
export class IndexInfo {
    "Name": string;
    "TableName": string;
    "DDL": string;
    "Columns": IndexColumnInfo[];

    /** Creates a new IndexInfo instance. */
    constructor($$source: Partial<IndexInfo> = {}) {
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("TableName" in $$source)) {
            this["TableName"] = "";
        }
        if (!("DDL" in $$source)) {
            this["DDL"] = "";
        }
        if (!("Columns" in $$source)) {
            this["Columns"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IndexInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): IndexInfo {
        const $$createField3_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Columns" in $$parsedSource) {
            $$parsedSource["Columns"] = $$createField3_0($$parsedSource["Columns"]);
        }
        return new IndexInfo($$parsedSource as Partial<IndexInfo>);
    }
}

/**
 * InspectField represents a resolved field/column reference in a SQL statement
 */
export class InspectField {
    /**
     * Column name
     */
    "Name": string;

    /**
     * Optional alias (e.g., SELECT c1 AS col1)
     */
    "Alias": string | null;

    /**
     * Resolved table name
     */
    "Table": string;

    /**
     * Resolved schema name
     */
    "Schema": string;

    /**
     * 1-based line of the identifier token (0 = unknown)
     */
    "StartLine": number;

    /**
     * 0-based column
     */
    "StartCol": number;

    /**
     * 0-based exclusive end column
     */
    "EndCol": number;

    /** Creates a new InspectField instance. */
    constructor($$source: Partial<InspectField> = {}) {
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Alias" in $$source)) {
            this["Alias"] = null;
        }
        if (!("Table" in $$source)) {
            this["Table"] = "";
        }
        if (!("Schema" in $$source)) {
            this["Schema"] = "";
        }
        if (!("StartLine" in $$source)) {
            this["StartLine"] = 0;
        }
        if (!("StartCol" in $$source)) {
            this["StartCol"] = 0;
        }
        if (!("EndCol" in $$source)) {
            this["EndCol"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InspectField instance from a string or object.
     */
    static createFrom($$source: any = {}): InspectField {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new InspectField($$parsedSource as Partial<InspectField>);
    }
}

/**
 * InspectOperation represents the type of SQL operation
 */
export enum InspectOperation {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    InspectOpSelect = "select",
    InspectOpInsert = "insert",
    InspectOpUpdate = "update",
    InspectOpDelete = "delete",
    InspectOpCreate = "create",
    InspectOpAlter = "alter",
    InspectOpDrop = "drop",
    InspectOpTruncate = "truncate",
    InspectOpGrant = "grant",
    InspectOpRevoke = "revoke",
    InspectOpUnknown = "unknown",
};

/**
 * InspectStatement represents the structured analysis of a SQL statement
 */
export class InspectStatement {
    /**
     * The operation type
     */
    "Operation": InspectOperation;

    /**
     * Fields/columns involved (for SELECT, UPDATE SET, INSERT columns)
     */
    "Fields": InspectField[];

    /**
     * Tables involved
     */
    "Tables": InspectTable[];

    /**
     * Fields used in WHERE clause (for permission/filtering context)
     */
    "Where": InspectField[];

    /**
     * Nested CTEs and subqueries - allows recursive permission checking
     */
    "Subqueries": InspectStatement[];

    /** Creates a new InspectStatement instance. */
    constructor($$source: Partial<InspectStatement> = {}) {
        if (!("Operation" in $$source)) {
            this["Operation"] = InspectOperation.$zero;
        }
        if (!("Fields" in $$source)) {
            this["Fields"] = [];
        }
        if (!("Tables" in $$source)) {
            this["Tables"] = [];
        }
        if (!("Where" in $$source)) {
            this["Where"] = [];
        }
        if (!("Subqueries" in $$source)) {
            this["Subqueries"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InspectStatement instance from a string or object.
     */
    static createFrom($$source: any = {}): InspectStatement {
        const $$createField1_0 = $$createType12;
        const $$createField2_0 = $$createType14;
        const $$createField3_0 = $$createType12;
        const $$createField4_0 = $$createType16;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Fields" in $$parsedSource) {
            $$parsedSource["Fields"] = $$createField1_0($$parsedSource["Fields"]);
        }
        if ("Tables" in $$parsedSource) {
            $$parsedSource["Tables"] = $$createField2_0($$parsedSource["Tables"]);
        }
        if ("Where" in $$parsedSource) {
            $$parsedSource["Where"] = $$createField3_0($$parsedSource["Where"]);
        }
        if ("Subqueries" in $$parsedSource) {
            $$parsedSource["Subqueries"] = $$createField4_0($$parsedSource["Subqueries"]);
        }
        return new InspectStatement($$parsedSource as Partial<InspectStatement>);
    }
}

/**
 * InspectTable represents a resolved table reference in a SQL statement
 */
export class InspectTable {
    /**
     * Table name
     */
    "Name": string;

    /**
     * Optional alias (e.g., FROM t1 AS a)
     */
    "Alias": string | null;

    /**
     * Resolved schema name
     */
    "Schema": string;

    /**
     * 1-based line of the identifier token (0 = unknown)
     */
    "StartLine": number;

    /**
     * 0-based column
     */
    "StartCol": number;

    /**
     * 0-based exclusive end column
     */
    "EndCol": number;

    /** Creates a new InspectTable instance. */
    constructor($$source: Partial<InspectTable> = {}) {
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Alias" in $$source)) {
            this["Alias"] = null;
        }
        if (!("Schema" in $$source)) {
            this["Schema"] = "";
        }
        if (!("StartLine" in $$source)) {
            this["StartLine"] = 0;
        }
        if (!("StartCol" in $$source)) {
            this["StartCol"] = 0;
        }
        if (!("EndCol" in $$source)) {
            this["EndCol"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InspectTable instance from a string or object.
     */
    static createFrom($$source: any = {}): InspectTable {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new InspectTable($$parsedSource as Partial<InspectTable>);
    }
}

/**
 * Metadata is an in-memory catalog provided by the caller
 */
export class Metadata {
    "DefaultDB": string;
    "DefaultSchema": string;

    /**
     * Current active schema for the user/session (empty means use DefaultSchema)
     */
    "CurrentSchema": string;
    "Schemas": Schema[];

    /** Creates a new Metadata instance. */
    constructor($$source: Partial<Metadata> = {}) {
        if (!("DefaultDB" in $$source)) {
            this["DefaultDB"] = "";
        }
        if (!("DefaultSchema" in $$source)) {
            this["DefaultSchema"] = "";
        }
        if (!("CurrentSchema" in $$source)) {
            this["CurrentSchema"] = "";
        }
        if (!("Schemas" in $$source)) {
            this["Schemas"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Metadata instance from a string or object.
     */
    static createFrom($$source: any = {}): Metadata {
        const $$createField3_0 = $$createType18;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Schemas" in $$parsedSource) {
            $$parsedSource["Schemas"] = $$createField3_0($$parsedSource["Schemas"]);
        }
        return new Metadata($$parsedSource as Partial<Metadata>);
    }
}

/**
 * NodeType represents a normalized operation category in an execution plan.
 */
export enum NodeType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    NodeTypeScan = "scan",
    NodeTypeJoin = "join",
    NodeTypeAggregate = "aggregate",
    NodeTypeSort = "sort",
    NodeTypeFilter = "filter",
    NodeTypeSubquery = "subquery",
    NodeTypeInsert = "insert",
    NodeTypeUpdate = "update",
    NodeTypeDelete = "delete",
    NodeTypeOther = "other",
};

/**
 * PermissionEntry is a single rule. nil pointer fields mean wildcard.
 */
export class PermissionEntry {
    "DbInstanceID": string | null;
    "SchemaName": string | null;
    "TableName": string | null;
    "ColumnName": string | null;

    /**
     * "select" | "insert" | "update" | "delete" | "ddl"
     */
    "Action": string;

    /**
     * "allow" | "deny"
     */
    "Effect": string;
    "RoleName": string;

    /** Creates a new PermissionEntry instance. */
    constructor($$source: Partial<PermissionEntry> = {}) {
        if (!("DbInstanceID" in $$source)) {
            this["DbInstanceID"] = null;
        }
        if (!("SchemaName" in $$source)) {
            this["SchemaName"] = null;
        }
        if (!("TableName" in $$source)) {
            this["TableName"] = null;
        }
        if (!("ColumnName" in $$source)) {
            this["ColumnName"] = null;
        }
        if (!("Action" in $$source)) {
            this["Action"] = "";
        }
        if (!("Effect" in $$source)) {
            this["Effect"] = "";
        }
        if (!("RoleName" in $$source)) {
            this["RoleName"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PermissionEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): PermissionEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PermissionEntry($$parsedSource as Partial<PermissionEntry>);
    }
}

/**
 * Schema holds schema-level objects
 */
export class Schema {
    "Name": string;
    "Tables": Table[];
    "ForeignTables": Table[];
    "Views": Table[];
    "MaterializedViews": Table[];
    "Indexes": IndexInfo[];
    "Triggers": TriggerInfo[];
    "Stats": TableStats;
    "Types": Type[];
    "Functions": Function[];
    "Settings": Setting[];

    /** Creates a new Schema instance. */
    constructor($$source: Partial<Schema> = {}) {
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Tables" in $$source)) {
            this["Tables"] = [];
        }
        if (!("ForeignTables" in $$source)) {
            this["ForeignTables"] = [];
        }
        if (!("Views" in $$source)) {
            this["Views"] = [];
        }
        if (!("MaterializedViews" in $$source)) {
            this["MaterializedViews"] = [];
        }
        if (!("Indexes" in $$source)) {
            this["Indexes"] = [];
        }
        if (!("Triggers" in $$source)) {
            this["Triggers"] = [];
        }
        if (!("Stats" in $$source)) {
            this["Stats"] = {};
        }
        if (!("Types" in $$source)) {
            this["Types"] = [];
        }
        if (!("Functions" in $$source)) {
            this["Functions"] = [];
        }
        if (!("Settings" in $$source)) {
            this["Settings"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Schema instance from a string or object.
     */
    static createFrom($$source: any = {}): Schema {
        const $$createField1_0 = $$createType20;
        const $$createField2_0 = $$createType20;
        const $$createField3_0 = $$createType20;
        const $$createField4_0 = $$createType20;
        const $$createField5_0 = $$createType22;
        const $$createField6_0 = $$createType24;
        const $$createField7_0 = $$createType25;
        const $$createField8_0 = $$createType28;
        const $$createField9_0 = $$createType30;
        const $$createField10_0 = $$createType32;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Tables" in $$parsedSource) {
            $$parsedSource["Tables"] = $$createField1_0($$parsedSource["Tables"]);
        }
        if ("ForeignTables" in $$parsedSource) {
            $$parsedSource["ForeignTables"] = $$createField2_0($$parsedSource["ForeignTables"]);
        }
        if ("Views" in $$parsedSource) {
            $$parsedSource["Views"] = $$createField3_0($$parsedSource["Views"]);
        }
        if ("MaterializedViews" in $$parsedSource) {
            $$parsedSource["MaterializedViews"] = $$createField4_0($$parsedSource["MaterializedViews"]);
        }
        if ("Indexes" in $$parsedSource) {
            $$parsedSource["Indexes"] = $$createField5_0($$parsedSource["Indexes"]);
        }
        if ("Triggers" in $$parsedSource) {
            $$parsedSource["Triggers"] = $$createField6_0($$parsedSource["Triggers"]);
        }
        if ("Stats" in $$parsedSource) {
            $$parsedSource["Stats"] = $$createField7_0($$parsedSource["Stats"]);
        }
        if ("Types" in $$parsedSource) {
            $$parsedSource["Types"] = $$createField8_0($$parsedSource["Types"]);
        }
        if ("Functions" in $$parsedSource) {
            $$parsedSource["Functions"] = $$createField9_0($$parsedSource["Functions"]);
        }
        if ("Settings" in $$parsedSource) {
            $$parsedSource["Settings"] = $$createField10_0($$parsedSource["Settings"]);
        }
        return new Schema($$parsedSource as Partial<Schema>);
    }
}

export class Setting {
    "name": string;
    "description"?: string;
    "value"?: string;

    /** Creates a new Setting instance. */
    constructor($$source: Partial<Setting> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Setting instance from a string or object.
     */
    static createFrom($$source: any = {}): Setting {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Setting($$parsedSource as Partial<Setting>);
    }
}

/**
 * Table represents a relation with columns
 */
export class Table {
    "Name": string;
    "Columns": Column[];

    /**
     * Column names that make up the primary key (empty for views or tables without PK)
     */
    "PrimaryKey": string[];

    /**
     * DDL statement for the table/view (empty if not available)
     */
    "DDL": string;

    /**
     * Table COMMENT, if any (used for hover docs and schema-driven codegen)
     */
    "Description"?: string;

    /** Creates a new Table instance. */
    constructor($$source: Partial<Table> = {}) {
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Columns" in $$source)) {
            this["Columns"] = [];
        }
        if (!("PrimaryKey" in $$source)) {
            this["PrimaryKey"] = [];
        }
        if (!("DDL" in $$source)) {
            this["DDL"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Table instance from a string or object.
     */
    static createFrom($$source: any = {}): Table {
        const $$createField1_0 = $$createType34;
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Columns" in $$parsedSource) {
            $$parsedSource["Columns"] = $$createField1_0($$parsedSource["Columns"]);
        }
        if ("PrimaryKey" in $$parsedSource) {
            $$parsedSource["PrimaryKey"] = $$createField2_0($$parsedSource["PrimaryKey"]);
        }
        return new Table($$parsedSource as Partial<Table>);
    }
}

/**
 * TableStats represents statistics for a table or index
 *
 * table/index name -> stat value
 */
export type TableStats = { [_ in string]?: string };

/**
 * TriggerInfo represents a trigger in the database
 */
export class TriggerInfo {
    "Name": string;
    "TableName": string;
    "DDL": string;

    /** Creates a new TriggerInfo instance. */
    constructor($$source: Partial<TriggerInfo> = {}) {
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("TableName" in $$source)) {
            this["TableName"] = "";
        }
        if (!("DDL" in $$source)) {
            this["DDL"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TriggerInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): TriggerInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TriggerInfo($$parsedSource as Partial<TriggerInfo>);
    }
}

/**
 * Type is a database type (from introspection) for casts, DDL, and hover.
 */
export class Type {
    "schema": string;
    "name": string;
    "kind": string;
    "display": string;
    "description"?: string;
    "enumLabels"?: string[];

    /** Creates a new Type instance. */
    constructor($$source: Partial<Type> = {}) {
        if (!("schema" in $$source)) {
            this["schema"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("display" in $$source)) {
            this["display"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Type instance from a string or object.
     */
    static createFrom($$source: any = {}): Type {
        const $$createField5_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("enumLabels" in $$parsedSource) {
            $$parsedSource["enumLabels"] = $$createField5_0($$parsedSource["enumLabels"]);
        }
        return new Type($$parsedSource as Partial<Type>);
    }
}

// Private type creation functions
const $$createType0 = ForeignKeyRef.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = $Create.Map($Create.Any, $Create.Any);
const $$createType4 = ExplainNode.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = CacheStats.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = IndexColumnInfo.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = InspectField.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = InspectTable.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = InspectStatement.createFrom;
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = Schema.createFrom;
const $$createType18 = $Create.Array($$createType17);
const $$createType19 = Table.createFrom;
const $$createType20 = $Create.Array($$createType19);
const $$createType21 = IndexInfo.createFrom;
const $$createType22 = $Create.Array($$createType21);
const $$createType23 = TriggerInfo.createFrom;
const $$createType24 = $Create.Array($$createType23);
var $$createType25 = (function $$initCreateType25(...args: any[]): any {
    if ($$createType25 === $$initCreateType25) {
        $$createType25 = $$createType26;
    }
    return $$createType25(...args);
});
const $$createType26 = $Create.Map($Create.Any, $Create.Any);
const $$createType27 = Type.createFrom;
const $$createType28 = $Create.Array($$createType27);
const $$createType29 = Function.createFrom;
const $$createType30 = $Create.Array($$createType29);
const $$createType31 = Setting.createFrom;
const $$createType32 = $Create.Array($$createType31);
const $$createType33 = Column.createFrom;
const $$createType34 = $Create.Array($$createType33);
