// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {workspace} from '../models';
import {generated} from '../models';

export function AddUserToWorkspace(arg1:string):Promise<void>;

export function CreateWorkspace(arg1:workspace.CreateWorkspaceParams):Promise<generated.Workspace>;

export function CreateWorkspaceAndReload(arg1:string):Promise<void>;

export function DeleteWorkspace(arg1:string):Promise<void>;

export function EnsureWorkspaceFolderByID(arg1:string,arg2:string):Promise<void>;

export function ListWorkspaceUsers():Promise<Array<workspace.WorkspaceUserEntry>>;

export function ListWorkspacesForCurrentUser():Promise<Array<workspace.WorkspaceWithCurrent>>;

export function RemoveUserFromWorkspace(arg1:string):Promise<void>;

export function RemoveWorkspaceFolderByID(arg1:string):Promise<void>;

export function SearchUser(arg1:string):Promise<workspace.SearchUserResult>;

export function SetOrCreateCurrentWorkspace(arg1:workspace.SetOrCreateCurrentWorkspaceParams):Promise<generated.Workspace>;

export function SwitchWorkspace(arg1:string):Promise<void>;

export function UpdateName(arg1:string,arg2:string):Promise<void>;
