// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddUserToWorkspace(arg1) {
  return window['go']['workspace']['Workspace']['AddUserToWorkspace'](arg1);
}

export function CreateWorkspace(arg1) {
  return window['go']['workspace']['Workspace']['CreateWorkspace'](arg1);
}

export function CreateWorkspaceAndReload(arg1) {
  return window['go']['workspace']['Workspace']['CreateWorkspaceAndReload'](arg1);
}

export function DeleteWorkspace(arg1) {
  return window['go']['workspace']['Workspace']['DeleteWorkspace'](arg1);
}

export function EnsureWorkspaceFolderByID(arg1, arg2) {
  return window['go']['workspace']['Workspace']['EnsureWorkspaceFolderByID'](arg1, arg2);
}

export function ListWorkspaceUsers() {
  return window['go']['workspace']['Workspace']['ListWorkspaceUsers']();
}

export function ListWorkspacesForCurrentUser() {
  return window['go']['workspace']['Workspace']['ListWorkspacesForCurrentUser']();
}

export function RemoveUserFromWorkspace(arg1) {
  return window['go']['workspace']['Workspace']['RemoveUserFromWorkspace'](arg1);
}

export function RemoveWorkspaceFolderByID(arg1) {
  return window['go']['workspace']['Workspace']['RemoveWorkspaceFolderByID'](arg1);
}

export function SearchUser(arg1) {
  return window['go']['workspace']['Workspace']['SearchUser'](arg1);
}

export function SetOrCreateCurrentWorkspace(arg1) {
  return window['go']['workspace']['Workspace']['SetOrCreateCurrentWorkspace'](arg1);
}

export function SwitchWorkspace(arg1) {
  return window['go']['workspace']['Workspace']['SwitchWorkspace'](arg1);
}

export function UpdateName(arg1, arg2) {
  return window['go']['workspace']['Workspace']['UpdateName'](arg1, arg2);
}
