// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as graph$0 from "../graph/models.js";

/**
 * ReplaceParams contains parameters for replacing text
 */
export class ReplaceParams {
    "workspaceId": string;
    "pattern": string;
    "replacement": string;
    "useRegex": boolean;
    "caseSensitive": boolean;
    "wholeWord": boolean;
    "includePattern": string;
    "excludePattern": string;

    /**
     * Optional: replace only in this file
     */
    "filePath": string;

    /**
     * If true, return what would be replaced without actually replacing
     */
    "dryRun": boolean;

    /** Creates a new ReplaceParams instance. */
    constructor($$source: Partial<ReplaceParams> = {}) {
        if (!("workspaceId" in $$source)) {
            this["workspaceId"] = "";
        }
        if (!("pattern" in $$source)) {
            this["pattern"] = "";
        }
        if (!("replacement" in $$source)) {
            this["replacement"] = "";
        }
        if (!("useRegex" in $$source)) {
            this["useRegex"] = false;
        }
        if (!("caseSensitive" in $$source)) {
            this["caseSensitive"] = false;
        }
        if (!("wholeWord" in $$source)) {
            this["wholeWord"] = false;
        }
        if (!("includePattern" in $$source)) {
            this["includePattern"] = "";
        }
        if (!("excludePattern" in $$source)) {
            this["excludePattern"] = "";
        }
        if (!("filePath" in $$source)) {
            this["filePath"] = "";
        }
        if (!("dryRun" in $$source)) {
            this["dryRun"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReplaceParams instance from a string or object.
     */
    static createFrom($$source: any = {}): ReplaceParams {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReplaceParams($$parsedSource as Partial<ReplaceParams>);
    }
}

/**
 * ReplaceResult represents the result of a replace operation
 */
export class ReplaceResult {
    /**
     * Number of files modified
     */
    "filesModified": number;

    /**
     * Total number of replacements made
     */
    "totalReplacements": number;

    /**
     * List of modified file paths
     */
    "modifiedFiles": string[];

    /** Creates a new ReplaceResult instance. */
    constructor($$source: Partial<ReplaceResult> = {}) {
        if (!("filesModified" in $$source)) {
            this["filesModified"] = 0;
        }
        if (!("totalReplacements" in $$source)) {
            this["totalReplacements"] = 0;
        }
        if (!("modifiedFiles" in $$source)) {
            this["modifiedFiles"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReplaceResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ReplaceResult {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("modifiedFiles" in $$parsedSource) {
            $$parsedSource["modifiedFiles"] = $$createField2_0($$parsedSource["modifiedFiles"]);
        }
        return new ReplaceResult($$parsedSource as Partial<ReplaceResult>);
    }
}

/**
 * SearchFileResult represents all matches in a single file
 */
export class SearchFileResult {
    /**
     * Relative path from workspace root
     */
    "path": string;

    /**
     * All matches in this file
     */
    "matches": SearchMatch[];

    /** Creates a new SearchFileResult instance. */
    constructor($$source: Partial<SearchFileResult> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("matches" in $$source)) {
            this["matches"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchFileResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SearchFileResult {
        const $$createField1_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("matches" in $$parsedSource) {
            $$parsedSource["matches"] = $$createField1_0($$parsedSource["matches"]);
        }
        return new SearchFileResult($$parsedSource as Partial<SearchFileResult>);
    }
}

/**
 * SearchMatch represents a single match within a file
 */
export class SearchMatch {
    /**
     * Line number (1-indexed)
     */
    "line": number;

    /**
     * Column number (1-indexed)
     */
    "column": number;

    /**
     * The full line content
     */
    "lineText": string;

    /**
     * Start position of match within line
     */
    "matchStart": number;

    /**
     * End position of match within line
     */
    "matchEnd": number;

    /** Creates a new SearchMatch instance. */
    constructor($$source: Partial<SearchMatch> = {}) {
        if (!("line" in $$source)) {
            this["line"] = 0;
        }
        if (!("column" in $$source)) {
            this["column"] = 0;
        }
        if (!("lineText" in $$source)) {
            this["lineText"] = "";
        }
        if (!("matchStart" in $$source)) {
            this["matchStart"] = 0;
        }
        if (!("matchEnd" in $$source)) {
            this["matchEnd"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchMatch instance from a string or object.
     */
    static createFrom($$source: any = {}): SearchMatch {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SearchMatch($$parsedSource as Partial<SearchMatch>);
    }
}

/**
 * SearchParams contains parameters for searching files
 */
export class SearchParams {
    "workspaceId": string;
    "pattern": string;
    "useRegex": boolean;
    "caseSensitive": boolean;
    "wholeWord": boolean;

    /**
     * File pattern to include (e.g., "*.go")
     */
    "includePattern": string;

    /**
     * File pattern to exclude
     */
    "excludePattern": string;

    /** Creates a new SearchParams instance. */
    constructor($$source: Partial<SearchParams> = {}) {
        if (!("workspaceId" in $$source)) {
            this["workspaceId"] = "";
        }
        if (!("pattern" in $$source)) {
            this["pattern"] = "";
        }
        if (!("useRegex" in $$source)) {
            this["useRegex"] = false;
        }
        if (!("caseSensitive" in $$source)) {
            this["caseSensitive"] = false;
        }
        if (!("wholeWord" in $$source)) {
            this["wholeWord"] = false;
        }
        if (!("includePattern" in $$source)) {
            this["includePattern"] = "";
        }
        if (!("excludePattern" in $$source)) {
            this["excludePattern"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchParams instance from a string or object.
     */
    static createFrom($$source: any = {}): SearchParams {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SearchParams($$parsedSource as Partial<SearchParams>);
    }
}

/**
 * SearchResult represents the complete search results
 */
export class SearchResult {
    /**
     * Files with matches
     */
    "files": SearchFileResult[];

    /**
     * Total number of files with matches
     */
    "totalFiles": number;

    /**
     * Total number of matches across all files
     */
    "totalMatches": number;

    /** Creates a new SearchResult instance. */
    constructor($$source: Partial<SearchResult> = {}) {
        if (!("files" in $$source)) {
            this["files"] = [];
        }
        if (!("totalFiles" in $$source)) {
            this["totalFiles"] = 0;
        }
        if (!("totalMatches" in $$source)) {
            this["totalMatches"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SearchResult {
        const $$createField0_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("files" in $$parsedSource) {
            $$parsedSource["files"] = $$createField0_0($$parsedSource["files"]);
        }
        return new SearchResult($$parsedSource as Partial<SearchResult>);
    }
}

/**
 * SearchResultWithNodes represents search results mapped to graph nodes
 * This allows the frontend to directly use the results without transformation
 */
export class SearchResultWithNodes {
    /**
     * Root folder containing all results
     */
    "resultFolder": graph$0.FolderNode | null;

    /**
     * Total number of files with matches
     */
    "totalFiles": number;

    /**
     * Total number of matches across all files
     */
    "totalMatches": number;

    /** Creates a new SearchResultWithNodes instance. */
    constructor($$source: Partial<SearchResultWithNodes> = {}) {
        if (!("resultFolder" in $$source)) {
            this["resultFolder"] = null;
        }
        if (!("totalFiles" in $$source)) {
            this["totalFiles"] = 0;
        }
        if (!("totalMatches" in $$source)) {
            this["totalMatches"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchResultWithNodes instance from a string or object.
     */
    static createFrom($$source: any = {}): SearchResultWithNodes {
        const $$createField0_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("resultFolder" in $$parsedSource) {
            $$parsedSource["resultFolder"] = $$createField0_0($$parsedSource["resultFolder"]);
        }
        return new SearchResultWithNodes($$parsedSource as Partial<SearchResultWithNodes>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = SearchMatch.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = SearchFileResult.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = graph$0.FolderNode.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
