// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Search encapsulates all search-related operations using ripgrep.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Replace performs a search and replace operation
 */
export function Replace(params: $models.ReplaceParams): $CancellablePromise<$models.ReplaceResult | null> {
    return $Call.ByID(388485746, params).then(($result: any) => {
        return $$createType1($result);
    });
}

export function Search(params: $models.SearchParams): $CancellablePromise<$models.SearchResult | null> {
    return $Call.ByID(1181619462, params).then(($result: any) => {
        return $$createType3($result);
    });
}

export function SearchWithNodes(params: $models.SearchParams): $CancellablePromise<$models.SearchResultWithNodes | null> {
    return $Call.ByID(4039490743, params).then(($result: any) => {
        return $$createType5($result);
    });
}

export function SetContext(): $CancellablePromise<void> {
    return $Call.ByID(3908312649);
}

// Private type creation functions
const $$createType0 = $models.ReplaceResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.SearchResult.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $models.SearchResultWithNodes.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
