// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CommitChanges(arg1) {
  return window['go']['git']['Git']['CommitChanges'](arg1);
}

export function CompleteLinkExistingRepo(arg1) {
  return window['go']['git']['Git']['CompleteLinkExistingRepo'](arg1);
}

export function GetBranches() {
  return window['go']['git']['Git']['GetBranches']();
}

export function GetFileDiffContent(arg1) {
  return window['go']['git']['Git']['GetFileDiffContent'](arg1);
}

export function GetGitFileStatus() {
  return window['go']['git']['Git']['GetGitFileStatus']();
}

export function GetGitWorkspaceStatus() {
  return window['go']['git']['Git']['GetGitWorkspaceStatus']();
}

export function InitAndPublishRepo(arg1) {
  return window['go']['git']['Git']['InitAndPublishRepo'](arg1);
}

export function LinkExistingRepo(arg1) {
  return window['go']['git']['Git']['LinkExistingRepo'](arg1);
}

export function LinkExistingRepoForWorkspace(arg1, arg2) {
  return window['go']['git']['Git']['LinkExistingRepoForWorkspace'](arg1, arg2);
}

export function PullWithRebase() {
  return window['go']['git']['Git']['PullWithRebase']();
}

export function PullWorkspaceRepo() {
  return window['go']['git']['Git']['PullWorkspaceRepo']();
}

export function PushForceWithLease() {
  return window['go']['git']['Git']['PushForceWithLease']();
}

export function PushWorkspaceRepo() {
  return window['go']['git']['Git']['PushWorkspaceRepo']();
}

export function ReconcileWorkspaceRemote(arg1, arg2) {
  return window['go']['git']['Git']['ReconcileWorkspaceRemote'](arg1, arg2);
}

export function ResetBranchToRemote() {
  return window['go']['git']['Git']['ResetBranchToRemote']();
}

export function RevertAll() {
  return window['go']['git']['Git']['RevertAll']();
}

export function RevertFile(arg1) {
  return window['go']['git']['Git']['RevertFile'](arg1);
}

export function SetContext(arg1) {
  return window['go']['git']['Git']['SetContext'](arg1);
}

export function StageAll() {
  return window['go']['git']['Git']['StageAll']();
}

export function StageFile(arg1) {
  return window['go']['git']['Git']['StageFile'](arg1);
}

export function SwitchBranch(arg1) {
  return window['go']['git']['Git']['SwitchBranch'](arg1);
}

export function UnlinkRemote() {
  return window['go']['git']['Git']['UnlinkRemote']();
}

export function UnstageAll() {
  return window['go']['git']['Git']['UnstageAll']();
}

export function UnstageFile(arg1) {
  return window['go']['git']['Git']['UnstageFile'](arg1);
}
