// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {git} from '../models';
import {context} from '../models';

export function CommitChanges(arg1:git.CommitParams):Promise<void>;

export function CompleteLinkExistingRepo(arg1:string):Promise<void>;

export function GetBranches():Promise<Array<git.BranchInfo>>;

export function GetFileDiffContent(arg1:git.GetFileDiffContentParams):Promise<git.GetFileDiffContentResult>;

export function GetGitFileStatus():Promise<git.GitFileStatus>;

export function GetGitWorkspaceStatus():Promise<git.GitWorkspaceStatus>;

export function InitAndPublishRepo(arg1:git.InitAndPublishParams):Promise<void>;

export function LinkExistingRepo(arg1:git.LinkExistingParams):Promise<git.LinkStatus>;

export function LinkExistingRepoForWorkspace(arg1:string,arg2:git.LinkExistingParams):Promise<void>;

export function PullWithRebase():Promise<void>;

export function PullWorkspaceRepo():Promise<void>;

export function PushForceWithLease():Promise<void>;

export function PushWorkspaceRepo():Promise<void>;

export function ReconcileWorkspaceRemote(arg1:string,arg2:any):Promise<git.ReconcileResult>;

export function ResetBranchToRemote():Promise<void>;

export function RevertAll():Promise<void>;

export function RevertFile(arg1:git.RevertFileParams):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function StageAll():Promise<void>;

export function StageFile(arg1:git.StageFileParams):Promise<void>;

export function SwitchBranch(arg1:git.SwitchBranchParams):Promise<void>;

export function UnlinkRemote():Promise<void>;

export function UnstageAll():Promise<void>;

export function UnstageFile(arg1:git.UnstageFileParams):Promise<void>;
