// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Binding is a written binding once its chord has been parsed and resolved for
 * a platform. Key is canonical, so matching a keystroke is a string comparison.
 */
export class Binding {
    "key": string;
    "command": string;
    "when"?: string;

    /** Creates a new Binding instance. */
    constructor($$source: Partial<Binding> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("command" in $$source)) {
            this["command"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Binding instance from a string or object.
     */
    static createFrom($$source: any = {}): Binding {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Binding($$parsedSource as Partial<Binding>);
    }
}

/**
 * Problem is something wrong with a binding, kept rather than dropped in
 * silence: a binding that cannot be parsed does nothing at all, and a keymap
 * that says nothing about it leaves a person pressing a key that will never
 * work.
 */
export class Problem {
    /**
     * Level is "error" for a binding that was dropped, "migrated" for one that
     * was read as something else.
     */
    "level": string;
    "source": string;
    "key": string;
    "command"?: string;
    "message": string;

    /** Creates a new Problem instance. */
    constructor($$source: Partial<Problem> = {}) {
        if (!("level" in $$source)) {
            this["level"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Problem instance from a string or object.
     */
    static createFrom($$source: any = {}): Problem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Problem($$parsedSource as Partial<Problem>);
    }
}
