// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sql$0 from "../../../database/sql/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as core$0 from "../../../github.com/selectDb/dialect/core/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as graph$0 from "../graph/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CancelQuery aborts the in-flight query for the given DB instance and file.
 */
export function CancelQuery(params: $models.CancelQueryParams): $CancellablePromise<void> {
    return $Call.ByID(2953678029, params);
}

/**
 * ChooseSSHKeyFile opens a native file picker and returns the chosen private key path.
 */
export function ChooseSSHKeyFile(): $CancellablePromise<string> {
    return $Call.ByID(2983131019);
}

export function Explain(params: $models.ExplainParams): $CancellablePromise<graph$0.ExplainResult> {
    return $Call.ByID(3158486816, params).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Export runs the query with full results, formats the output, and saves via OS save dialog.
 */
export function Export(params: $models.ExportParams): $CancellablePromise<void> {
    return $Call.ByID(1003354207, params);
}

/**
 * GenerateSelectSQL builds a preview SELECT for a single relation, using the
 * database instance's dialect for identifier quoting.
 */
export function GenerateSelectSQL(params: $models.GenerateSelectSQLParams): $CancellablePromise<$models.GenerateSelectSQLResult> {
    return $Call.ByID(2222436010, params).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GenerateUpdateSQL builds a single SQL string of UPDATE statements (one per row),
 * ordered by table then by row, using the file's dialect and schema metadata for quoting and literal formatting.
 */
export function GenerateUpdateSQL(params: $models.GenerateUpdateSQLParams): $CancellablePromise<$models.GenerateUpdateSQLResult> {
    return $Call.ByID(1195042649, params).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetMeta satisfies sqllang.MetadataFunc.
 */
export function GetMeta(node: graph$0.DBInstanceNode | null, noCache: boolean): $CancellablePromise<core$0.Metadata | null> {
    return $Call.ByID(1766662838, node, noCache).then(($result: any) => {
        return $$createType4($result);
    });
}

export function GetOrOpenConn(workspaceID: string, dbType: string, dsn: string, folderID: string, sshConfig: graph$0.DBInstanceSSHConfig | null): $CancellablePromise<sql$0.DB | null> {
    return $Call.ByID(4218675072, workspaceID, dbType, dsn, folderID, sshConfig).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * GetResultPage returns a page from the streaming cache. The returned Status
 * indicates whether the page is "ready", "partial" (fewer rows than pageSize
 * because the stream is still filling), or "pending" (no rows yet for this
 * window).
 */
export function GetResultPage(params: $models.GetResultPageParams): $CancellablePromise<graph$0.QueryResult> {
    return $Call.ByID(3703585705, params).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * InspectStatement satisfies sqllang.InspectFunc.
 * TODO: move to dialect/ when metadata cache is shared with remote backend.
 */
export function InspectStatement(statement: string, dbInstance: graph$0.DBInstanceNode | null): $CancellablePromise<core$0.InspectStatement[]> {
    return $Call.ByID(3779236896, statement, dbInstance).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * LookupForeignKey runs a dialect-aware SELECT against the FK target table and
 * returns the rows the picker should show. The frontend never sees the SQL.
 */
export function LookupForeignKey(params: $models.LookupForeignKeyParams): $CancellablePromise<graph$0.QueryResult> {
    return $Call.ByID(3038363876, params).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * Ping checks if the database instance is reachable.
 */
export function Ping(params: $models.PingParams): $CancellablePromise<string> {
    return $Call.ByID(1825352989, params);
}

export function Plan(params: $models.PlanParams): $CancellablePromise<graph$0.ExplainResult> {
    return $Call.ByID(2724910294, params).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Query is the legacy synchronous entry point. It blocks until all rows are
 * available, then returns the full Result. Used by Export and any call site
 * that explicitly needs ForExport semantics.
 * 
 * Interactive callers should prefer StartQuery, which streams progress and
 * hands back rows page-by-page from the streaming cache.
 */
export function Query(params: $models.QueryParams): $CancellablePromise<graph$0.QueryResult> {
    return $Call.ByID(2964708639, params).then(($result: any) => {
        return $$createType7($result);
    });
}

export function QuerySchema(queryParams: $models.QuerySchemaParams): $CancellablePromise<void> {
    return $Call.ByID(241241184, queryParams);
}

export function SetContext(): $CancellablePromise<void> {
    return $Call.ByID(2068689542);
}

/**
 * SetSSHKeyPassphrase stores (or clears, when empty) the passphrase for an
 * encrypted SSH key file, keyed by its path. Held in memory only.
 */
export function SetSSHKeyPassphrase(keyPath: string, passphrase: string): $CancellablePromise<void> {
    return $Call.ByID(1408567570, keyPath, passphrase);
}

/**
 * StartQuery validates inputs and kicks off a streaming execution.
 * Emits Wails events keyed by executionId; returns immediately.
 */
export function StartQuery(params: $models.StartQueryParams): $CancellablePromise<$models.StartQueryResult> {
    return $Call.ByID(3919096057, params).then(($result: any) => {
        return $$createType10($result);
    });
}

// Private type creation functions
const $$createType0 = graph$0.ExplainResult.createFrom;
const $$createType1 = $models.GenerateSelectSQLResult.createFrom;
const $$createType2 = $models.GenerateUpdateSQLResult.createFrom;
const $$createType3 = core$0.Metadata.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = sql$0.DB.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = graph$0.QueryResult.createFrom;
const $$createType8 = core$0.InspectStatement.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = $models.StartQueryResult.createFrom;
