// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as graph$0 from "../graph/models.js";

export class CancelQueryParams {
    "DbInstanceID": string;
    "FileID": string;

    /** Creates a new CancelQueryParams instance. */
    constructor($$source: Partial<CancelQueryParams> = {}) {
        if (!("DbInstanceID" in $$source)) {
            this["DbInstanceID"] = "";
        }
        if (!("FileID" in $$source)) {
            this["FileID"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CancelQueryParams instance from a string or object.
     */
    static createFrom($$source: any = {}): CancelQueryParams {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CancelQueryParams($$parsedSource as Partial<CancelQueryParams>);
    }
}

export class ExplainParams {
    "FileID": string;
    "Statement": string;
    "DbInstanceID": string;
    "FolderID": string;
    "RuntimeVars": { [_ in string]?: string };

    /** Creates a new ExplainParams instance. */
    constructor($$source: Partial<ExplainParams> = {}) {
        if (!("FileID" in $$source)) {
            this["FileID"] = "";
        }
        if (!("Statement" in $$source)) {
            this["Statement"] = "";
        }
        if (!("DbInstanceID" in $$source)) {
            this["DbInstanceID"] = "";
        }
        if (!("FolderID" in $$source)) {
            this["FolderID"] = "";
        }
        if (!("RuntimeVars" in $$source)) {
            this["RuntimeVars"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExplainParams instance from a string or object.
     */
    static createFrom($$source: any = {}): ExplainParams {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("RuntimeVars" in $$parsedSource) {
            $$parsedSource["RuntimeVars"] = $$createField4_0($$parsedSource["RuntimeVars"]);
        }
        return new ExplainParams($$parsedSource as Partial<ExplainParams>);
    }
}

export class ExportParams {
    /**
     * temp or disk file identifier
     */
    "FileID": string;

    /**
     * SQL content to execute
     */
    "Statement": string;
    "DbInstanceID": string;
    "FolderID": string;

    /**
     * csv_semicolon | csv_comma | json
     */
    "Format": string;
    "Filename": string;

    /**
     * user-supplied values for unresolved $variables
     */
    "RuntimeVars": { [_ in string]?: string };

    /** Creates a new ExportParams instance. */
    constructor($$source: Partial<ExportParams> = {}) {
        if (!("FileID" in $$source)) {
            this["FileID"] = "";
        }
        if (!("Statement" in $$source)) {
            this["Statement"] = "";
        }
        if (!("DbInstanceID" in $$source)) {
            this["DbInstanceID"] = "";
        }
        if (!("FolderID" in $$source)) {
            this["FolderID"] = "";
        }
        if (!("Format" in $$source)) {
            this["Format"] = "";
        }
        if (!("Filename" in $$source)) {
            this["Filename"] = "";
        }
        if (!("RuntimeVars" in $$source)) {
            this["RuntimeVars"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExportParams instance from a string or object.
     */
    static createFrom($$source: any = {}): ExportParams {
        const $$createField6_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("RuntimeVars" in $$parsedSource) {
            $$parsedSource["RuntimeVars"] = $$createField6_0($$parsedSource["RuntimeVars"]);
        }
        return new ExportParams($$parsedSource as Partial<ExportParams>);
    }
}

/**
 * GenerateSelectSQLParams is the payload for GenerateSelectSQL. Like the FK
 * lookup it is deliberately structured (no SQL strings on the wire) so quoting
 * stays dialect-aware and stays out of the frontend.
 */
export class GenerateSelectSQLParams {
    "databaseId": string;
    "schema": string;
    "table": string;

    /**
     * Limit is the row cap of the generated statement. Values <= 0 fall back to
     * DefaultSelectPreviewLimit.
     */
    "limit": number;

    /** Creates a new GenerateSelectSQLParams instance. */
    constructor($$source: Partial<GenerateSelectSQLParams> = {}) {
        if (!("databaseId" in $$source)) {
            this["databaseId"] = "";
        }
        if (!("schema" in $$source)) {
            this["schema"] = "";
        }
        if (!("table" in $$source)) {
            this["table"] = "";
        }
        if (!("limit" in $$source)) {
            this["limit"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GenerateSelectSQLParams instance from a string or object.
     */
    static createFrom($$source: any = {}): GenerateSelectSQLParams {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GenerateSelectSQLParams($$parsedSource as Partial<GenerateSelectSQLParams>);
    }
}

/**
 * GenerateSelectSQLResult is the output of GenerateSelectSQL.
 */
export class GenerateSelectSQLResult {
    "sql": string;

    /** Creates a new GenerateSelectSQLResult instance. */
    constructor($$source: Partial<GenerateSelectSQLResult> = {}) {
        if (!("sql" in $$source)) {
            this["sql"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GenerateSelectSQLResult instance from a string or object.
     */
    static createFrom($$source: any = {}): GenerateSelectSQLResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GenerateSelectSQLResult($$parsedSource as Partial<GenerateSelectSQLResult>);
    }
}

/**
 * GenerateUpdateSQLParams is the input for GenerateUpdateSQL.
 */
export class GenerateUpdateSQLParams {
    "databaseId": string;
    "edits": TableEditInput[];

    /** Creates a new GenerateUpdateSQLParams instance. */
    constructor($$source: Partial<GenerateUpdateSQLParams> = {}) {
        if (!("databaseId" in $$source)) {
            this["databaseId"] = "";
        }
        if (!("edits" in $$source)) {
            this["edits"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GenerateUpdateSQLParams instance from a string or object.
     */
    static createFrom($$source: any = {}): GenerateUpdateSQLParams {
        const $$createField1_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("edits" in $$parsedSource) {
            $$parsedSource["edits"] = $$createField1_0($$parsedSource["edits"]);
        }
        return new GenerateUpdateSQLParams($$parsedSource as Partial<GenerateUpdateSQLParams>);
    }
}

/**
 * GenerateUpdateSQLResult is the output of GenerateUpdateSQL.
 */
export class GenerateUpdateSQLResult {
    "sql": string;

    /** Creates a new GenerateUpdateSQLResult instance. */
    constructor($$source: Partial<GenerateUpdateSQLResult> = {}) {
        if (!("sql" in $$source)) {
            this["sql"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GenerateUpdateSQLResult instance from a string or object.
     */
    static createFrom($$source: any = {}): GenerateUpdateSQLResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GenerateUpdateSQLResult($$parsedSource as Partial<GenerateUpdateSQLResult>);
    }
}

export class GetResultPageParams {
    "DbInstanceID": string;
    "FileID": string;
    "ResultID": string;
    "Page": number;

    /** Creates a new GetResultPageParams instance. */
    constructor($$source: Partial<GetResultPageParams> = {}) {
        if (!("DbInstanceID" in $$source)) {
            this["DbInstanceID"] = "";
        }
        if (!("FileID" in $$source)) {
            this["FileID"] = "";
        }
        if (!("ResultID" in $$source)) {
            this["ResultID"] = "";
        }
        if (!("Page" in $$source)) {
            this["Page"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GetResultPageParams instance from a string or object.
     */
    static createFrom($$source: any = {}): GetResultPageParams {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GetResultPageParams($$parsedSource as Partial<GetResultPageParams>);
    }
}

/**
 * LookupForeignKeyParams is the payload from the frontend's FK picker. It is
 * deliberately structured (no SQL strings on the wire) so the dialect-specific
 * SQL building happens entirely in the corresponding dialect package.
 */
export class LookupForeignKeyParams {
    "databaseId": string;
    "schema": string;
    "table": string;
    "fkColumn": string;
    "displayColumns": string[];
    "query": string;
    "currentValue": string;
    "limit": number;

    /** Creates a new LookupForeignKeyParams instance. */
    constructor($$source: Partial<LookupForeignKeyParams> = {}) {
        if (!("databaseId" in $$source)) {
            this["databaseId"] = "";
        }
        if (!("schema" in $$source)) {
            this["schema"] = "";
        }
        if (!("table" in $$source)) {
            this["table"] = "";
        }
        if (!("fkColumn" in $$source)) {
            this["fkColumn"] = "";
        }
        if (!("displayColumns" in $$source)) {
            this["displayColumns"] = [];
        }
        if (!("query" in $$source)) {
            this["query"] = "";
        }
        if (!("currentValue" in $$source)) {
            this["currentValue"] = "";
        }
        if (!("limit" in $$source)) {
            this["limit"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LookupForeignKeyParams instance from a string or object.
     */
    static createFrom($$source: any = {}): LookupForeignKeyParams {
        const $$createField4_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("displayColumns" in $$parsedSource) {
            $$parsedSource["displayColumns"] = $$createField4_0($$parsedSource["displayColumns"]);
        }
        return new LookupForeignKeyParams($$parsedSource as Partial<LookupForeignKeyParams>);
    }
}

export class PingParams {
    "DbInstanceID": string;
    "db_type": string;
    "dsn": string;
    "folder_id": string;
    "ssh"?: graph$0.DBInstanceSSHConfig | null;
    "proxified": boolean;
    "no_cache"?: boolean;

    /** Creates a new PingParams instance. */
    constructor($$source: Partial<PingParams> = {}) {
        if (!("DbInstanceID" in $$source)) {
            this["DbInstanceID"] = "";
        }
        if (!("db_type" in $$source)) {
            this["db_type"] = "";
        }
        if (!("dsn" in $$source)) {
            this["dsn"] = "";
        }
        if (!("folder_id" in $$source)) {
            this["folder_id"] = "";
        }
        if (!("proxified" in $$source)) {
            this["proxified"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PingParams instance from a string or object.
     */
    static createFrom($$source: any = {}): PingParams {
        const $$createField4_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ssh" in $$parsedSource) {
            $$parsedSource["ssh"] = $$createField4_0($$parsedSource["ssh"]);
        }
        return new PingParams($$parsedSource as Partial<PingParams>);
    }
}

export class PlanParams {
    "FileID": string;
    "Statement": string;
    "DbInstanceID": string;
    "FolderID": string;
    "RuntimeVars": { [_ in string]?: string };

    /** Creates a new PlanParams instance. */
    constructor($$source: Partial<PlanParams> = {}) {
        if (!("FileID" in $$source)) {
            this["FileID"] = "";
        }
        if (!("Statement" in $$source)) {
            this["Statement"] = "";
        }
        if (!("DbInstanceID" in $$source)) {
            this["DbInstanceID"] = "";
        }
        if (!("FolderID" in $$source)) {
            this["FolderID"] = "";
        }
        if (!("RuntimeVars" in $$source)) {
            this["RuntimeVars"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlanParams instance from a string or object.
     */
    static createFrom($$source: any = {}): PlanParams {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("RuntimeVars" in $$parsedSource) {
            $$parsedSource["RuntimeVars"] = $$createField4_0($$parsedSource["RuntimeVars"]);
        }
        return new PlanParams($$parsedSource as Partial<PlanParams>);
    }
}

export class QueryParams {
    "FileID": string;
    "Statement": string;
    "DbInstanceID": string;
    "FolderID": string;
    "ForExport": boolean;
    "RuntimeVars": { [_ in string]?: string };

    /** Creates a new QueryParams instance. */
    constructor($$source: Partial<QueryParams> = {}) {
        if (!("FileID" in $$source)) {
            this["FileID"] = "";
        }
        if (!("Statement" in $$source)) {
            this["Statement"] = "";
        }
        if (!("DbInstanceID" in $$source)) {
            this["DbInstanceID"] = "";
        }
        if (!("FolderID" in $$source)) {
            this["FolderID"] = "";
        }
        if (!("ForExport" in $$source)) {
            this["ForExport"] = false;
        }
        if (!("RuntimeVars" in $$source)) {
            this["RuntimeVars"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QueryParams instance from a string or object.
     */
    static createFrom($$source: any = {}): QueryParams {
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("RuntimeVars" in $$parsedSource) {
            $$parsedSource["RuntimeVars"] = $$createField5_0($$parsedSource["RuntimeVars"]);
        }
        return new QueryParams($$parsedSource as Partial<QueryParams>);
    }
}

export class QuerySchemaParams {
    "DatabaseInstanceID": string;
    "NoCache": boolean;

    /** Creates a new QuerySchemaParams instance. */
    constructor($$source: Partial<QuerySchemaParams> = {}) {
        if (!("DatabaseInstanceID" in $$source)) {
            this["DatabaseInstanceID"] = "";
        }
        if (!("NoCache" in $$source)) {
            this["NoCache"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QuerySchemaParams instance from a string or object.
     */
    static createFrom($$source: any = {}): QuerySchemaParams {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new QuerySchemaParams($$parsedSource as Partial<QuerySchemaParams>);
    }
}

/**
 * StartQueryParams kicks off a streaming query. The returned ExecutionID is the
 * key used to correlate Wails events ("query:started", "query:progress",
 * "query:done", "query:error") and to fetch pages via GetResultPage.
 */
export class StartQueryParams {
    "FileID": string;
    "Statement": string;
    "DbInstanceID": string;
    "FolderID": string;
    "RuntimeVars": { [_ in string]?: string };

    /** Creates a new StartQueryParams instance. */
    constructor($$source: Partial<StartQueryParams> = {}) {
        if (!("FileID" in $$source)) {
            this["FileID"] = "";
        }
        if (!("Statement" in $$source)) {
            this["Statement"] = "";
        }
        if (!("DbInstanceID" in $$source)) {
            this["DbInstanceID"] = "";
        }
        if (!("FolderID" in $$source)) {
            this["FolderID"] = "";
        }
        if (!("RuntimeVars" in $$source)) {
            this["RuntimeVars"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StartQueryParams instance from a string or object.
     */
    static createFrom($$source: any = {}): StartQueryParams {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("RuntimeVars" in $$parsedSource) {
            $$parsedSource["RuntimeVars"] = $$createField4_0($$parsedSource["RuntimeVars"]);
        }
        return new StartQueryParams($$parsedSource as Partial<StartQueryParams>);
    }
}

/**
 * StartQueryResult is returned synchronously from StartQuery. The query runs
 * in a background goroutine; results arrive via Wails events.
 */
export class StartQueryResult {
    "executionId": string;
    "dbInstanceId": string;
    "fileId": string;
    "errors"?: string[];

    /** Creates a new StartQueryResult instance. */
    constructor($$source: Partial<StartQueryResult> = {}) {
        if (!("executionId" in $$source)) {
            this["executionId"] = "";
        }
        if (!("dbInstanceId" in $$source)) {
            this["dbInstanceId"] = "";
        }
        if (!("fileId" in $$source)) {
            this["fileId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StartQueryResult instance from a string or object.
     */
    static createFrom($$source: any = {}): StartQueryResult {
        const $$createField3_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("errors" in $$parsedSource) {
            $$parsedSource["errors"] = $$createField3_0($$parsedSource["errors"]);
        }
        return new StartQueryResult($$parsedSource as Partial<StartQueryResult>);
    }
}

/**
 * TableEditInput is the payload for a single cell edit (mirrors frontend TableEdit).
 */
export class TableEditInput {
    "databaseId": string;
    "schema": string;
    "table": string;
    "column": string;
    "value": string;
    "rowIndex": number;
    "columnIndex": number;
    "primaryKeyValues": { [_ in string]?: any };

    /** Creates a new TableEditInput instance. */
    constructor($$source: Partial<TableEditInput> = {}) {
        if (!("databaseId" in $$source)) {
            this["databaseId"] = "";
        }
        if (!("schema" in $$source)) {
            this["schema"] = "";
        }
        if (!("table" in $$source)) {
            this["table"] = "";
        }
        if (!("column" in $$source)) {
            this["column"] = "";
        }
        if (!("value" in $$source)) {
            this["value"] = "";
        }
        if (!("rowIndex" in $$source)) {
            this["rowIndex"] = 0;
        }
        if (!("columnIndex" in $$source)) {
            this["columnIndex"] = 0;
        }
        if (!("primaryKeyValues" in $$source)) {
            this["primaryKeyValues"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TableEditInput instance from a string or object.
     */
    static createFrom($$source: any = {}): TableEditInput {
        const $$createField7_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("primaryKeyValues" in $$parsedSource) {
            $$parsedSource["primaryKeyValues"] = $$createField7_0($$parsedSource["primaryKeyValues"]);
        }
        return new TableEditInput($$parsedSource as Partial<TableEditInput>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = TableEditInput.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = graph$0.DBInstanceSSHConfig.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $Create.Map($Create.Any, $Create.Any);
