// Code generated by apigen. DO NOT EDIT.

package types

import "time"

// GroupToRoleRow is a group_to_role row for sync.
type GroupToRoleRow struct {
	ID          string     `json:"id"`
	GroupID     string     `json:"group_id"`
	RoleID      string     `json:"role_id"`
	WorkspaceID string     `json:"workspace_id"`
	UpdatedAt   time.Time  `json:"updated_at"`
	DeletedAt   *time.Time `json:"deleted_at,omitempty"`
}
