// Code generated by apigen. DO NOT EDIT.

package types

import "time"

// GroupRow is a group row for sync.
type GroupRow struct {
	ID          string     `json:"id"`
	WorkspaceID string     `json:"workspace_id"`
	Name        string     `json:"name"`
	Source      string     `json:"source"`
	ExternalID  string     `json:"external_id"`
	UpdatedAt   time.Time  `json:"updated_at"`
	DeletedAt   *time.Time `json:"deleted_at,omitempty"`
}
