// Code generated by apigen. DO NOT EDIT.

package types

import "time"

// PermissionRow is a permission row for sync.
type PermissionRow struct {
	ID           string     `json:"id"`
	RoleID       string     `json:"role_id"`
	WorkspaceID  string     `json:"workspace_id"`
	DbInstanceID string     `json:"db_instance_id"`
	SchemaName   string     `json:"schema_name"`
	TableName    string     `json:"table_name"`
	ColumnName   string     `json:"column_name"`
	Action       string     `json:"action"`
	Effect       string     `json:"effect"`
	UpdatedAt    time.Time  `json:"updated_at"`
	DeletedAt    *time.Time `json:"deleted_at,omitempty"`
}
