// Code generated by apigen. DO NOT EDIT.

package types

import "time"

// RoleRow is a role row for sync.
type RoleRow struct {
	ID          string     `json:"id"`
	WorkspaceID string     `json:"workspace_id"`
	Name        string     `json:"name"`
	UpdatedAt   time.Time  `json:"updated_at"`
	DeletedAt   *time.Time `json:"deleted_at,omitempty"`
}
