// Code generated by apigen. DO NOT EDIT.

package types

import "time"

// UserToRoleRow is a user_to_role row for sync.
type UserToRoleRow struct {
	ID          string     `json:"id"`
	UserID      string     `json:"user_id"`
	RoleID      string     `json:"role_id"`
	WorkspaceID string     `json:"workspace_id"`
	UpdatedAt   time.Time  `json:"updated_at"`
	DeletedAt   *time.Time `json:"deleted_at,omitempty"`
}
