// Code generated by apigen. DO NOT EDIT.

package types

import "time"

// UserToGroupRow is a user_to_group row for sync.
type UserToGroupRow struct {
	ID          string     `json:"id"`
	UserID      string     `json:"user_id"`
	GroupID     string     `json:"group_id"`
	WorkspaceID string     `json:"workspace_id"`
	Source      string     `json:"source"`
	UpdatedAt   time.Time  `json:"updated_at"`
	DeletedAt   *time.Time `json:"deleted_at,omitempty"`
}
