// Code generated by apigen. DO NOT EDIT.

package types

import "time"

// WorkspaceToUserRow is a workspace_to_user row for sync.
type WorkspaceToUserRow struct {
	ID          string     `json:"id"`
	WorkspaceID string     `json:"workspace_id"`
	UserID      string     `json:"user_id"`
	UpdatedAt   time.Time  `json:"updated_at"`
	DeletedAt   *time.Time `json:"deleted_at,omitempty"`
}
