// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function DeleteDatasource(id: string): $CancellablePromise<void> {
    return $Call.ByID(1291883610, id);
}

export function GetDatasource(id: string): $CancellablePromise<$models.GetResult | null> {
    return $Call.ByID(1365518261, id).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ListDatasources returns every proxified connection stored for the workspace,
 * including ones no workspace file names any more.
 * 
 * That last case is the reason this exists. The directory naming a connection
 * is replicated through git, so it can be deleted on another machine, in a
 * branch, or outside the app, while the credential stays on the server. Without
 * this list such a connection cannot be seen or revoked, because the id needed
 * to name it lived in the file that was deleted.
 */
export function ListDatasources(): $CancellablePromise<$models.ListedDatasource[]> {
    return $Call.ByID(3057265278).then(($result: any) => {
        return $$createType3($result);
    });
}

export function UpsertDatasource(params: $models.UpsertParams): $CancellablePromise<void> {
    return $Call.ByID(3159418018, params);
}

// Private type creation functions
const $$createType0 = $models.GetResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.ListedDatasource.createFrom;
const $$createType3 = $Create.Array($$createType2);
