// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function DeleteDatasource(id: string): $CancellablePromise<void> {
    return $Call.ByID(1291883610, id);
}

export function GetDatasource(id: string): $CancellablePromise<$models.GetResult | null> {
    return $Call.ByID(1365518261, id).then(($result: any) => {
        return $$createType1($result);
    });
}

export function UpsertDatasource(params: $models.UpsertParams): $CancellablePromise<void> {
    return $Call.ByID(3159418018, params);
}

// Private type creation functions
const $$createType0 = $models.GetResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
