// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class GetResult {
    "name": string;
    "dsn": string;
    "ssh": string;
    "max_open_conns": number;
    "max_idle_conns": number;
    "conn_max_lifetime": number;
    "conn_max_idle_time": number;

    /** Creates a new GetResult instance. */
    constructor($$source: Partial<GetResult> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("dsn" in $$source)) {
            this["dsn"] = "";
        }
        if (!("ssh" in $$source)) {
            this["ssh"] = "";
        }
        if (!("max_open_conns" in $$source)) {
            this["max_open_conns"] = 0;
        }
        if (!("max_idle_conns" in $$source)) {
            this["max_idle_conns"] = 0;
        }
        if (!("conn_max_lifetime" in $$source)) {
            this["conn_max_lifetime"] = 0;
        }
        if (!("conn_max_idle_time" in $$source)) {
            this["conn_max_idle_time"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GetResult instance from a string or object.
     */
    static createFrom($$source: any = {}): GetResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GetResult($$parsedSource as Partial<GetResult>);
    }
}

export class UpsertParams {
    "id": string;
    "db_type": string;
    "name": string;
    "dsn": string;

    /**
     * JSON-encoded SSH config
     */
    "ssh": string;
    "max_open_conns": number;
    "max_idle_conns": number;
    "conn_max_lifetime": number;
    "conn_max_idle_time": number;

    /** Creates a new UpsertParams instance. */
    constructor($$source: Partial<UpsertParams> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("db_type" in $$source)) {
            this["db_type"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("dsn" in $$source)) {
            this["dsn"] = "";
        }
        if (!("ssh" in $$source)) {
            this["ssh"] = "";
        }
        if (!("max_open_conns" in $$source)) {
            this["max_open_conns"] = 0;
        }
        if (!("max_idle_conns" in $$source)) {
            this["max_idle_conns"] = 0;
        }
        if (!("conn_max_lifetime" in $$source)) {
            this["conn_max_lifetime"] = 0;
        }
        if (!("conn_max_idle_time" in $$source)) {
            this["conn_max_idle_time"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpsertParams instance from a string or object.
     */
    static createFrom($$source: any = {}): UpsertParams {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpsertParams($$parsedSource as Partial<UpsertParams>);
    }
}
