package syncer

import (
	"backend/internal/apigen/codegen"
	"backend/internal/apigen/schema"
	"fmt"
	"go/format"
	"strings"
)

// EmitSyncGlue renders the four syncer files a synced entity needs — Apply
// (LWW upsert via patch.Apply), ApplyDelete (soft delete), FetchCurrent, and
// GetChangesSince (+ the row mapper) — from the entity model. It references
// sqlc's generated types/methods (generated.<Model>, Upsert<Sing>Params, …);
// `go build` against db/generated is what validates those references.
//
// Single-column PK and text-only patchable fields for now (role); composite
// keys and other kinds arrive with the tables that need them.
//
// scoped is the set of workspace-scoped tables (those carrying the tenant
// column): an FK pointing at one of them gets a cross-workspace guard in Apply.
func EmitSyncGlue(e schema.Entity, scoped map[string]bool) ([]codegen.GenFile, error) {
	d := newGlueData(e, scoped)
	files := []codegen.GenFile{
		{Name: "getsince.go", Content: codegen.Render(glueGetSinceTmpl, d)},
		{Name: "fetch_current.go", Content: codegen.Render(glueFetchCurrentTmpl, d)},
		{Name: "apply_delete.go", Content: codegen.Render(glueApplyDeleteTmpl, d)},
		{Name: "apply.go", Content: codegen.Render(glueApplyTmpl, d)},
	}
	for i, f := range files {
		formatted, err := format.Source([]byte(f.Content))
		if err != nil {
			return nil, fmt.Errorf("%s: %w", f.Name, err)
		}
		files[i].Content = string(formatted)
	}
	return files, nil
}

const genHeader = "// Code generated by apigen. DO NOT EDIT.\n\n"

// kv is one "Key: Val" line in a struct literal (merge params, row mapper).
type kv struct{ Key, Val string }

// fkItem is one non-tenant FK the apply handler parses from the payload (only
// when the field is present — a partial update may omit it, leaving the existing
// value). Scoped FKs (target carries workspace_id) additionally get the
// cross-workspace guard via scope.<ScopeFn>.
type fkItem struct {
	Var, Column, Pkg string
	Scoped           bool
	ScopeFn, Target  string
}

// rowField is one column projected onto the types.<Sing>Row wire struct.
type rowField struct{ Name, Type, Tag string }

// glueData is the view every syncer-glue template renders. Per-field decisions
// (which columns are identity vs. patchable, which FKs need a scope guard) are
// resolved here in Go; the templates own only the file skeleton.
type glueData struct {
	Pkg, Model, Sing, Plur       string
	RowType, MapperFn            string
	Table                        string
	PKField, TenantField         string
	CursorField, SoftDeleteField string
	NeedScope                    bool
	FKs                          []fkItem
	Merge                        []kv
	RowMap                       []kv
	// Audit: emit an audit.EmitChange on apply/delete. Target is the row id
	// (AuditDeleteByID) or, for a junction row, an FK read from the payload on
	// apply and from the fetched pre-delete row on delete. A lifecycle entity
	// sets AuditSplit: apply picks AuditCreateSpec on insert, AuditUpdateSpec on
	// update (via res.Created); a junction has AuditCreateSpec == AuditUpdateSpec
	// and emits the one grant/add spec unconditionally.
	Audit              bool
	AuditSplit         bool
	AuditCreateSpec    string
	AuditUpdateSpec    string
	AuditDeleteSpec    string
	AuditApplyTarget   string
	AuditDeleteByID    bool
	AuditDeleteRowExpr string
}

func newGlueData(e schema.Entity, scoped map[string]bool) glueData {
	model := codegen.Pascal(e.Schema) + codegen.Pascal(e.Table)
	sing := codegen.Pascal(e.Table)
	d := glueData{
		Pkg: e.Table, Model: model, Sing: sing, Plur: sing + "s",
		RowType:  "types." + sing + "Row",
		MapperFn: strings.ToLower(model[:1]) + model[1:] + "ToTypesRow", // appRoleToTypesRow
		Table:    e.Table,
		PKField:  codegen.GoField(e.PrimaryKey[0]), TenantField: codegen.GoField(schema.TenantColumn),
		CursorField: codegen.GoField(schema.CursorColumn), SoftDeleteField: codegen.GoField(schema.SoftDeleteColumn),
	}

	// Non-tenant FKs are parsed from the payload (identity, passed through on
	// insert, never updated on conflict). The parse is conditional on the field
	// being present so a partial update that omits an FK keeps the existing value.
	for _, f := range e.Fields {
		if f.FK == nil || f.Column == schema.TenantColumn {
			continue
		}
		item := fkItem{Var: fkVar(f.Column), Column: f.Column, Pkg: e.Table}
		// Cross-workspace guard: any FK whose target is itself workspace-scoped
		// must belong to the caller's workspace, else a *.manage holder could
		// point a write at a row in another workspace (privilege escalation).
		// Derived from the target carrying the tenant column — no hand-maintained
		// list. A global target (e.g. user, which has no workspace_id) is skipped.
		// The guard calls scope.<Target>InWorkspace, generated by EmitScope.
		if scoped[f.FK.Table] {
			item.Scoped = true
			item.ScopeFn = codegen.Pascal(f.FK.Table) + "InWorkspace"
			item.Target = f.FK.Table
			d.NeedScope = true
		}
		d.FKs = append(d.FKs, item)
	}

	// Merge (upsert params): id + workspace are identity; then each column —
	// FKs pass through their parsed local, patchables take the payload value.
	d.Merge = []kv{{d.PKField, "idUUID"}, {d.TenantField, "workspaceUUID"}}
	for _, f := range e.Fields {
		switch {
		case f.IsPK, f.Column == schema.TenantColumn, f.Column == schema.CursorColumn, f.Column == schema.SoftDeleteColumn:
			continue
		case f.FK != nil:
			d.Merge = append(d.Merge, kv{codegen.GoField(f.Column),
				fmt.Sprintf("utils.PatchUUID(payload, %q, existing.%s, %s)", f.Column, codegen.GoField(f.Column), fkVar(f.Column))})
		case f.Patchable:
			d.Merge = append(d.Merge, kv{codegen.GoField(f.Column), patchExpr(f)})
		}
	}

	// Row mapper: every column except soft-delete (a pointer, handled by the
	// template tail) reads its plain value via the matching accessor.
	for _, f := range e.Fields {
		if f.Column == schema.SoftDeleteColumn {
			continue
		}
		d.RowMap = append(d.RowMap, kv{codegen.GoField(f.Column), fmt.Sprintf("row.%s.%s()", codegen.GoField(f.Column), accessor(f.Kind))})
	}

	// Audit: the target id is the row's own id, or a junction FK. When it's the
	// FK, read it from the payload on apply and from the pre-delete row on delete.
	if a, ok := auditSpecs[e.Table]; ok {
		d.Audit = true
		d.AuditCreateSpec, d.AuditUpdateSpec, d.AuditDeleteSpec = a.Create, a.Update, a.Delete
		d.AuditSplit = a.Create != a.Update
		if a.TargetCol == e.PrimaryKey[0] {
			d.AuditApplyTarget, d.AuditDeleteByID = "id", true
		} else {
			d.AuditApplyTarget = fmt.Sprintf("utils.MapGetString(payload, %q)", a.TargetCol)
			d.AuditDeleteRowExpr = fmt.Sprintf("row.%s.String()", codegen.GoField(a.TargetCol))
		}
	}
	return d
}

// accessor is the db_types.JSONNull* reader that yields the plain Go value the
// types.<Row> field expects.
func accessor(k schema.Kind) string {
	switch k {
	case schema.KindUUID, schema.KindInet:
		return "String"
	case schema.KindText:
		return "ValueOrEmpty"
	default: // time, int, bool
		return "ValueOrZero"
	}
}

// patchExpr is the merge value for a patchable (non-FK, non-system) text field:
// PatchNullStr for a nullable column, PatchStrDefault for a NOT NULL column
// with a DB default (so a client-omitted value falls back to that default
// instead of writing NULL), PatchStr otherwise.
func patchExpr(f schema.Field) string {
	switch {
	case f.Nullable:
		return fmt.Sprintf("utils.PatchNullStr(payload, %q, existing.%s)", f.Column, codegen.GoField(f.Column))
	case f.Default != "":
		return fmt.Sprintf("utils.PatchStrDefault(payload, %q, existing.%s, %q)", f.Column, codegen.GoField(f.Column), f.Default)
	default:
		return fmt.Sprintf("utils.PatchStr(payload, %q, existing.%s)", f.Column, codegen.GoField(f.Column))
	}
}

// fkVar is the local variable name for a parsed FK uuid (user_id -> userUUID).
func fkVar(col string) string {
	parts := strings.Split(strings.TrimSuffix(col, "_id"), "_")
	for i, p := range parts {
		if i > 0 && p != "" {
			parts[i] = strings.ToUpper(p[:1]) + p[1:]
		}
	}
	return strings.Join(parts, "") + "UUID"
}

var glueGetSinceTmpl = mustParse("getsince.go.tmpl")

var glueFetchCurrentTmpl = mustParse("fetchcurrent.go.tmpl")

var glueApplyDeleteTmpl = mustParse("applydelete.go.tmpl")

var glueApplyTmpl = mustParse("apply.go.tmpl")
