package syncer

import (
	"backend/internal/apigen/codegen"
	"backend/internal/apigen/schema"
	"fmt"
	"go/format"
	"strings"
	"text/template"
)

// EmitSyncGlue renders the four syncer files a synced entity needs — Apply
// (LWW upsert via patch.Apply), ApplyDelete (soft delete), FetchCurrent, and
// GetChangesSince (+ the row mapper) — from the entity model. It references
// sqlc's generated types/methods (generated.<Model>, Upsert<Sing>Params, …);
// `go build` against db/generated is what validates those references.
//
// Single-column PK and text-only patchable fields for now (role); composite
// keys and other kinds arrive with the tables that need them.
//
// scoped is the set of workspace-scoped tables (those carrying the tenant
// column): an FK pointing at one of them gets a cross-workspace guard in Apply.
func EmitSyncGlue(e schema.Entity, scoped map[string]bool) ([]codegen.GenFile, error) {
	d := newGlueData(e, scoped)
	files := []codegen.GenFile{
		{Name: "getsince.go", Content: codegen.Render(glueGetSinceTmpl, d)},
		{Name: "fetch_current.go", Content: codegen.Render(glueFetchCurrentTmpl, d)},
		{Name: "apply_delete.go", Content: codegen.Render(glueApplyDeleteTmpl, d)},
		{Name: "apply.go", Content: codegen.Render(glueApplyTmpl, d)},
	}
	for i, f := range files {
		formatted, err := format.Source([]byte(f.Content))
		if err != nil {
			return nil, fmt.Errorf("%s: %w", f.Name, err)
		}
		files[i].Content = string(formatted)
	}
	return files, nil
}

const genHeader = "// Code generated by apigen. DO NOT EDIT.\n\n"

// kv is one "Key: Val" line in a struct literal (merge params, row mapper).
type kv struct{ Key, Val string }

// fkParseItem parses one non-tenant FK from the payload into a *UUID local.
type fkParseItem struct{ Var, Column, Pkg string }

// scopeItem is one cross-workspace guard for a referenced FK.
type scopeItem struct{ Fn, Var, Column, Table, Pkg string }

// rowField is one column projected onto the types.<Sing>Row wire struct.
type rowField struct{ Name, Type, Tag string }

// glueData is the view every syncer-glue template renders. Per-field decisions
// (which columns are identity vs. patchable, which FKs need a scope guard) are
// resolved here in Go; the templates own only the file skeleton.
type glueData struct {
	Pkg, Model, Sing, Plur       string
	RowType, MapperFn            string
	Table                        string
	PKField, TenantField         string
	CursorField, SoftDeleteField string
	NeedScope                    bool
	FKParse                      []fkParseItem
	Scope                        []scopeItem
	Merge                        []kv
	RowMap                       []kv
	// Audit: emit an audit.EmitChange on apply/delete. Target is the row id
	// (AuditDeleteByID) or, for a junction row, an FK read from the payload on
	// apply and from the fetched pre-delete row on delete. A lifecycle entity
	// sets AuditSplit: apply picks AuditCreateSpec on insert, AuditUpdateSpec on
	// update (via res.Created); a junction has AuditCreateSpec == AuditUpdateSpec
	// and emits the one grant/add spec unconditionally.
	Audit              bool
	AuditSplit         bool
	AuditCreateSpec    string
	AuditUpdateSpec    string
	AuditDeleteSpec    string
	AuditApplyTarget   string
	AuditDeleteByID    bool
	AuditDeleteRowExpr string
}

func newGlueData(e schema.Entity, scoped map[string]bool) glueData {
	model := codegen.Pascal(e.Schema) + codegen.Pascal(e.Table)
	sing := codegen.Pascal(e.Table)
	d := glueData{
		Pkg: e.Table, Model: model, Sing: sing, Plur: sing + "s",
		RowType:  "types." + sing + "Row",
		MapperFn: strings.ToLower(model[:1]) + model[1:] + "ToTypesRow", // appRoleToTypesRow
		Table:    e.Table,
		PKField:  codegen.GoField(e.PrimaryKey[0]), TenantField: codegen.GoField(schema.TenantColumn),
		CursorField: codegen.GoField(schema.CursorColumn), SoftDeleteField: codegen.GoField(schema.SoftDeleteColumn),
	}

	// FK columns other than the tenant are parsed from the payload up front and
	// passed through as identity — like id and workspace.
	for _, f := range e.Fields {
		if f.FK == nil || f.Column == schema.TenantColumn {
			continue
		}
		d.FKParse = append(d.FKParse, fkParseItem{Var: fkVar(f.Column), Column: f.Column, Pkg: e.Table})
		// Cross-workspace guard: any FK whose target is itself workspace-scoped
		// must belong to the caller's workspace, else a *.manage holder could
		// point a write at a row in another workspace (privilege escalation).
		// Derived from the target carrying the tenant column — no hand-maintained
		// list. A global target (e.g. user, which has no workspace_id) is skipped.
		// The guard calls scope.<Target>InWorkspace; that helper must exist, so a
		// new scoped target fails the build loudly rather than going unguarded.
		if scoped[f.FK.Table] {
			fn := codegen.Pascal(f.FK.Table) + "InWorkspace"
			d.Scope = append(d.Scope, scopeItem{Fn: fn, Var: fkVar(f.Column), Column: f.Column, Table: f.FK.Table, Pkg: e.Table})
		}
	}
	d.NeedScope = len(d.Scope) > 0

	// Merge (upsert params): id + workspace are identity; then each column —
	// FKs pass through their parsed local, patchables take the payload value.
	d.Merge = []kv{{d.PKField, "idUUID"}, {d.TenantField, "workspaceUUID"}}
	for _, f := range e.Fields {
		switch {
		case f.IsPK, f.Column == schema.TenantColumn, f.Column == schema.CursorColumn, f.Column == schema.SoftDeleteColumn:
			continue
		case f.FK != nil:
			d.Merge = append(d.Merge, kv{codegen.GoField(f.Column),
				fmt.Sprintf("utils.PatchUUID(payload, %q, existing.%s, %s)", f.Column, codegen.GoField(f.Column), fkVar(f.Column))})
		case f.Patchable:
			d.Merge = append(d.Merge, kv{codegen.GoField(f.Column), patchExpr(f)})
		}
	}

	// Row mapper: every column except soft-delete (a pointer, handled by the
	// template tail) reads its plain value via the matching accessor.
	for _, f := range e.Fields {
		if f.Column == schema.SoftDeleteColumn {
			continue
		}
		d.RowMap = append(d.RowMap, kv{codegen.GoField(f.Column), fmt.Sprintf("row.%s.%s()", codegen.GoField(f.Column), accessor(f.Kind))})
	}

	// Audit: the target id is the row's own id, or a junction FK. When it's the
	// FK, read it from the payload on apply and from the pre-delete row on delete.
	if a, ok := auditSpecs[e.Table]; ok {
		d.Audit = true
		d.AuditCreateSpec, d.AuditUpdateSpec, d.AuditDeleteSpec = a.Create, a.Update, a.Delete
		d.AuditSplit = a.Create != a.Update
		if a.TargetCol == e.PrimaryKey[0] {
			d.AuditApplyTarget, d.AuditDeleteByID = "id", true
		} else {
			d.AuditApplyTarget = fmt.Sprintf("utils.MapGetString(payload, %q)", a.TargetCol)
			d.AuditDeleteRowExpr = fmt.Sprintf("row.%s.String()", codegen.GoField(a.TargetCol))
		}
	}
	return d
}

// accessor is the db_types.JSONNull* reader that yields the plain Go value the
// types.<Row> field expects.
func accessor(k schema.Kind) string {
	switch k {
	case schema.KindUUID, schema.KindInet:
		return "String"
	case schema.KindText:
		return "ValueOrEmpty"
	default: // time, int, bool
		return "ValueOrZero"
	}
}

// patchExpr is the merge value for a patchable (non-FK, non-system) text field:
// PatchNullStr for a nullable column, PatchStrDefault for a NOT NULL column
// with a DB default (so a client-omitted value falls back to that default
// instead of writing NULL), PatchStr otherwise.
func patchExpr(f schema.Field) string {
	switch {
	case f.Nullable:
		return fmt.Sprintf("utils.PatchNullStr(payload, %q, existing.%s)", f.Column, codegen.GoField(f.Column))
	case f.Default != "":
		return fmt.Sprintf("utils.PatchStrDefault(payload, %q, existing.%s, %q)", f.Column, codegen.GoField(f.Column), f.Default)
	default:
		return fmt.Sprintf("utils.PatchStr(payload, %q, existing.%s)", f.Column, codegen.GoField(f.Column))
	}
}

// fkVar is the local variable name for a parsed FK uuid (user_id -> userUUID).
func fkVar(col string) string {
	parts := strings.Split(strings.TrimSuffix(col, "_id"), "_")
	for i, p := range parts {
		if i > 0 && p != "" {
			parts[i] = strings.ToUpper(p[:1]) + p[1:]
		}
	}
	return strings.Join(parts, "") + "UUID"
}

var glueGetSinceTmpl = template.Must(template.New("getsince").Parse(genHeader +
	`package {{.Pkg}}

import (
	"context"
	"time"

	"backend/db"
	"backend/db/db_types"
	"backend/db/generated"
	"backend/internal/syncer/types"
)

func GetChangesSince(ctx context.Context, userID string, since time.Time) ([]{{.RowType}}, error) {
	userUUID, err := db_types.NewJSONNullUUIDFromString(userID)
	if err != nil {
		return nil, err
	}

	rows, err := db.Queries.Get{{.Plur}}ForUserSince(ctx, generated.Get{{.Plur}}ForUserSinceParams{
		UserID:    userUUID,
		UpdatedAt: db_types.NewJSONNullTimeFromTime(since),
	})
	if err != nil {
		return nil, err
	}

	out := make([]{{.RowType}}, 0, len(rows))
	for _, r := range rows {
		out = append(out, {{.MapperFn}}(r))
	}
	return out, nil
}

func {{.MapperFn}}(row generated.{{.Model}}) {{.RowType}} {
	r := {{.RowType}}{
{{- range .RowMap}}
		{{.Key}}: {{.Val}},
{{- end}}
	}
	if row.{{.SoftDeleteField}}.Valid {
		t := row.{{.SoftDeleteField}}.ValueOrZero()
		r.{{.SoftDeleteField}} = &t
	}
	return r
}
`))

var glueFetchCurrentTmpl = template.Must(template.New("fetchcurrent").Parse(genHeader +
	`package {{.Pkg}}

import (
	"context"
	"database/sql"
	"errors"

	"backend/db"
	"backend/db/db_types"
	"backend/db/generated"
	"backend/internal/syncer/types"
)

func FetchCurrent(ctx context.Context, c types.Commit) (*types.RestoredItem, error) {
	idUUID, err := db_types.NewJSONNullUUIDFromString(c.ObjectID)
	if err != nil {
		return nil, nil
	}
	workspaceUUID, err := db_types.NewJSONNullUUIDFromString(c.WorkspaceID)
	if err != nil {
		return nil, nil
	}
	row, err := db.Queries.Get{{.Sing}}ByID(ctx, generated.Get{{.Sing}}ByIDParams{ {{.PKField}}: idUUID, {{.TenantField}}: workspaceUUID})
	if errors.Is(err, sql.ErrNoRows) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	payload, err := types.ToRestoredPayload({{.MapperFn}}(row))
	if err != nil {
		return nil, err
	}
	return &types.RestoredItem{
		ObjectID:      c.ObjectID,
		TableName:     {{printf "%q" .Table}},
		ServerPayload: payload,
		UpdatedAt:     row.{{.CursorField}}.ValueOrZero(),
	}, nil
}
`))

var glueApplyDeleteTmpl = template.Must(template.New("applydelete").Parse(genHeader +
	`package {{.Pkg}}

import (
	"context"
	"fmt"

	"backend/db"
	"backend/db/db_types"
	"backend/db/generated"
{{- if .Audit}}
	"backend/internal/audit"
{{- end}}
	"backend/internal/syncer/types"
	"backend/internal/utils"
)

func ApplyDelete(ctx context.Context, userID string, c types.Commit) (bool, *types.RestoredItem, error) {
	payload, _ := c.Payload.(map[string]any)
	id := utils.MapGetString(payload, "id")
	if id == "" {
		id = c.ObjectID
	}
	workspaceID := c.WorkspaceID
	if id == "" || workspaceID == "" {
		return false, nil, fmt.Errorf("{{.Pkg}}: missing id or workspace_id")
	}
	idUUID, err := db_types.NewJSONNullUUIDFromString(id)
	if err != nil {
		return false, nil, fmt.Errorf("{{.Pkg}}: invalid id %q: %w", id, err)
	}
	workspaceUUID, err := db_types.NewJSONNullUUIDFromString(workspaceID)
	if err != nil {
		return false, nil, fmt.Errorf("{{.Pkg}}: invalid workspace_id %q: %w", workspaceID, err)
	}
{{- if .Audit}}
	// Fetch the pre-delete row for the audit before-image{{if not .AuditDeleteByID}} and target{{end}}.
	row, fetchErr := db.Queries.Get{{.Sing}}ByID(ctx, generated.Get{{.Sing}}ByIDParams{ {{.PKField}}: idUUID, {{.TenantField}}: workspaceUUID})
{{- end}}
	if err := db.Queries.Set{{.Sing}}DeletedAt(ctx, generated.Set{{.Sing}}DeletedAtParams{
		{{.PKField}}:          idUUID,
		{{.TenantField}}: workspaceUUID,
	}); err != nil {
		return false, nil, fmt.Errorf("{{.Pkg}}: set deleted_at: %w", err)
	}
{{- if .Audit}}
	var before any
{{- if not .AuditDeleteByID}}
	target := ""
{{- end}}
	if fetchErr == nil {
		before = row
{{- if not .AuditDeleteByID}}
		target = {{.AuditDeleteRowExpr}}
{{- end}}
	}
	audit.EmitChange(ctx, {{.AuditDeleteSpec}}, workspaceID, {{if .AuditDeleteByID}}id{{else}}target{{end}}, before, nil)
{{- end}}
	return true, nil, nil
}
`))

var glueApplyTmpl = template.Must(template.New("apply").Parse(genHeader +
	`package {{.Pkg}}

import (
	"context"
	"fmt"
	"time"

	"backend/db"
	"backend/db/db_types"
	"backend/db/generated"
{{- if .Audit}}
	"backend/internal/audit"
{{- end}}
	"backend/internal/syncer/patch"
{{- if .NeedScope}}
	"backend/internal/syncer/scope"
{{- end}}
	"backend/internal/syncer/types"
	"backend/internal/utils"
)

func Apply(ctx context.Context, userID string, c types.Commit, lastPulledAt time.Time) (bool, *types.RestoredItem, error) {
	payload, ok := c.Payload.(map[string]any)
	if !ok {
		return false, nil, fmt.Errorf("{{.Pkg}}: payload must be an object")
	}

	id := utils.MapGetString(payload, "id")
	workspaceID := c.WorkspaceID
	if id == "" || workspaceID == "" {
		return false, nil, fmt.Errorf("{{.Pkg}}: missing id or workspace_id")
	}

	idUUID, err := db_types.NewJSONNullUUIDFromString(id)
	if err != nil {
		return false, nil, fmt.Errorf("{{.Pkg}}: invalid id %q: %w", id, err)
	}
	workspaceUUID, err := db_types.NewJSONNullUUIDFromString(workspaceID)
	if err != nil {
		return false, nil, fmt.Errorf("{{.Pkg}}: invalid workspace_id %q: %w", workspaceID, err)
	}

{{range .FKParse -}}
	{{.Var}}, err := db_types.NewJSONNullUUIDFromString(utils.MapGetString(payload, {{printf "%q" .Column}}))
	if err != nil {
		return false, nil, fmt.Errorf("{{.Pkg}}: invalid {{.Column}}: %w", err)
	}
{{end -}}
{{range .Scope -}}
	if ok, err := scope.{{.Fn}}(ctx, {{.Var}}, workspaceUUID); err != nil {
		return false, nil, fmt.Errorf("{{.Pkg}}: validate {{.Table}}: %w", err)
	} else if !ok {
		// FK doesn't resolve to a row in this workspace (missing, soft-deleted, or
		// in another workspace). A typed FieldError so the REST layer surfaces a
		// precise, safe 422; the message never reveals cross-workspace existence.
		return false, nil, &types.FieldError{Field: {{printf "%q" .Column}}, Message: "does not reference a {{.Table}} in this workspace"}
	}
{{end -}}
	res, err := patch.Apply(ctx, c, patch.Handler[generated.{{.Model}}, generated.Upsert{{.Sing}}Params]{
		TableName: {{printf "%q" .Table}},
		Fetch: func(ctx context.Context) (generated.{{.Model}}, error) {
			return db.Queries.Get{{.Sing}}ByID(ctx, generated.Get{{.Sing}}ByIDParams{ {{.PKField}}: idUUID, {{.TenantField}}: workspaceUUID})
		},
		UpdatedAt: func(row generated.{{.Model}}) time.Time {
			return row.{{.CursorField}}.ValueOrZero()
		},
		DeletedAt: func(row generated.{{.Model}}) *time.Time {
			if row.{{.SoftDeleteField}}.Valid {
				t := row.{{.SoftDeleteField}}.ValueOrZero()
				return &t
			}
			return nil
		},
		Restored: func(row generated.{{.Model}}) (interface{}, error) {
			return types.ToRestoredPayload({{.MapperFn}}(row))
		},
		Merge: func(existing generated.{{.Model}}, isNew bool, payload map[string]any) (generated.Upsert{{.Sing}}Params, error) {
			if !isNew && existing.{{.TenantField}} != workspaceUUID {
				return generated.Upsert{{.Sing}}Params{}, fmt.Errorf("{{.Pkg}}: belongs to another workspace")
			}
			return generated.Upsert{{.Sing}}Params{
{{- range .Merge}}
				{{.Key}}: {{.Val}},
{{- end}}
			}, nil
		},
		Upsert: func(ctx context.Context, params generated.Upsert{{.Sing}}Params) error {
			return db.Queries.Upsert{{.Sing}}(ctx, params)
		},
	})
{{- if .Audit}}
	if res.Applied {
{{- if .AuditSplit}}
		spec := {{.AuditCreateSpec}}
		if !res.Created {
			spec = {{.AuditUpdateSpec}}
		}
		audit.EmitChange(ctx, spec, c.WorkspaceID, {{.AuditApplyTarget}}, res.Before, res.After)
{{- else}}
		audit.EmitChange(ctx, {{.AuditCreateSpec}}, c.WorkspaceID, {{.AuditApplyTarget}}, res.Before, res.After)
{{- end}}
	}
{{- end}}
	return res.Applied, res.Restored, err
}
`))
