// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForLogin() {
  return window['go']['system']['System']['CheckForLogin']();
}

export function CheckForLogout() {
  return window['go']['system']['System']['CheckForLogout']();
}

export function GetAppEnv() {
  return window['go']['system']['System']['GetAppEnv']();
}

export function GetConfig() {
  return window['go']['system']['System']['GetConfig']();
}

export function GetDefaultConfigContent() {
  return window['go']['system']['System']['GetDefaultConfigContent']();
}

export function GetDefaultLintContent() {
  return window['go']['system']['System']['GetDefaultLintContent']();
}

export function GetDefaultThemeContent() {
  return window['go']['system']['System']['GetDefaultThemeContent']();
}

export function GetDefaultUserConfigContent() {
  return window['go']['system']['System']['GetDefaultUserConfigContent']();
}

export function GetLint() {
  return window['go']['system']['System']['GetLint']();
}

export function GetThemeVariables() {
  return window['go']['system']['System']['GetThemeVariables']();
}

export function LoadAllDatabaseSchemas(arg1) {
  return window['go']['system']['System']['LoadAllDatabaseSchemas'](arg1);
}

export function Logout() {
  return window['go']['system']['System']['Logout']();
}

export function OpenURL(arg1) {
  return window['go']['system']['System']['OpenURL'](arg1);
}

export function ResetConfig() {
  return window['go']['system']['System']['ResetConfig']();
}

export function ResetLint() {
  return window['go']['system']['System']['ResetLint']();
}

export function ResetUserConfig() {
  return window['go']['system']['System']['ResetUserConfig']();
}

export function ResetTheme() {
  return window['go']['system']['System']['ResetTheme']();
}

export function RevealInExplorer(arg1) {
  return window['go']['system']['System']['RevealInExplorer'](arg1);
}

export function SetContext(arg1) {
  return window['go']['system']['System']['SetContext'](arg1);
}

export function StartDatabaseWatcher() {
  return window['go']['system']['System']['StartDatabaseWatcher']();
}

export function StartFileWatcher(arg1) {
  return window['go']['system']['System']['StartFileWatcher'](arg1);
}

export function WatchNetworkQuality() {
  return window['go']['system']['System']['WatchNetworkQuality']();
}

export function WindowClose() {
  return window['go']['system']['System']['WindowClose']();
}

export function WindowMinimise() {
  return window['go']['system']['System']['WindowMinimise']();
}

export function WindowToggleFullscreen() {
  return window['go']['system']['System']['WindowToggleFullscreen']();
}
