// Code generated by apigen. DO NOT EDIT.

// Package scope holds the cross-workspace foreign-key guards the generated
// syncer Apply calls: <Target>InWorkspace reports whether a referenced row
// exists in the caller's workspace, so a write can't point an FK at a row in
// another workspace. One guard per workspace-scoped FK target.
package scope

import (
	"context"
	"database/sql"
	"errors"

	"backend/db"
	"backend/db/db_types"
	"backend/db/generated"
)

// GroupInWorkspace reports whether groupID exists and belongs to
// workspaceID (a workspace-scoped by-id lookup).
func GroupInWorkspace(ctx context.Context, groupID, workspaceID db_types.JSONNullUUID) (bool, error) {
	_, err := db.Queries.GetGroupByID(ctx, generated.GetGroupByIDParams{ID: groupID, WorkspaceID: workspaceID})
	if errors.Is(err, sql.ErrNoRows) {
		return false, nil
	}
	if err != nil {
		return false, err
	}
	return true, nil
}

// PrincipalSnapshotInWorkspace reports whether principalSnapshotID exists and belongs to
// workspaceID (a workspace-scoped by-id lookup).
func PrincipalSnapshotInWorkspace(ctx context.Context, principalSnapshotID, workspaceID db_types.JSONNullUUID) (bool, error) {
	_, err := db.Queries.GetPrincipalSnapshotByID(ctx, generated.GetPrincipalSnapshotByIDParams{ID: principalSnapshotID, WorkspaceID: workspaceID})
	if errors.Is(err, sql.ErrNoRows) {
		return false, nil
	}
	if err != nil {
		return false, err
	}
	return true, nil
}

// RoleInWorkspace reports whether roleID exists and belongs to
// workspaceID (a workspace-scoped by-id lookup).
func RoleInWorkspace(ctx context.Context, roleID, workspaceID db_types.JSONNullUUID) (bool, error) {
	_, err := db.Queries.GetRoleByID(ctx, generated.GetRoleByIDParams{ID: roleID, WorkspaceID: workspaceID})
	if errors.Is(err, sql.ErrNoRows) {
		return false, nil
	}
	if err != nil {
		return false, err
	}
	return true, nil
}
