// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Apply() {
  return window['go']['updater']['Updater']['Apply']();
}

export function CheckVersion() {
  return window['go']['updater']['Updater']['CheckVersion']();
}

export function SetContext(arg1) {
  return window['go']['updater']['Updater']['SetContext'](arg1);
}
