// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCurrentUser() {
  return window['go']['user']['User']['GetCurrentUser']();
}

export function GetCurrentUserAvatar(arg1) {
  return window['go']['user']['User']['GetCurrentUserAvatar'](arg1);
}
