// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {generated} from '../models';

export function GetCurrentUser():Promise<generated.User>;

export function GetCurrentUserAvatar(arg1:string):Promise<string>;
