// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Manifest holds the result of fetching a backend server's version endpoint.
 * Returned by GetServerManifest for the frontend to show server status and version warnings.
 */
export class Manifest {
    "live": boolean;
    "backend_version": string;
    "min_app_version": string;
    "latest_app_version": string;
    "warning": string;

    /** Creates a new Manifest instance. */
    constructor($$source: Partial<Manifest> = {}) {
        if (!("live" in $$source)) {
            this["live"] = false;
        }
        if (!("backend_version" in $$source)) {
            this["backend_version"] = "";
        }
        if (!("min_app_version" in $$source)) {
            this["min_app_version"] = "";
        }
        if (!("latest_app_version" in $$source)) {
            this["latest_app_version"] = "";
        }
        if (!("warning" in $$source)) {
            this["warning"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Manifest instance from a string or object.
     */
    static createFrom($$source: any = {}): Manifest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Manifest($$parsedSource as Partial<Manifest>);
    }
}
