// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Server provides server selection and management (domain-based, no meta DB).
 * DB operations are injected to avoid import cycles.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateServer creates a new server folder and its DB for the given domain.
 */
export function CreateServer(domain: string): $CancellablePromise<void> {
    return $Call.ByID(2784074795, domain);
}

/**
 * GetCurrentServer returns the current server domain, or empty if none.
 */
export function GetCurrentServer(): $CancellablePromise<string> {
    return $Call.ByID(3809107618);
}

/**
 * GetDefaultServer returns the default server domain for the current APP_ENV, or empty if none.
 */
export function GetDefaultServer(): $CancellablePromise<string> {
    return $Call.ByID(2839585978);
}

/**
 * GetServerManifest fetches the manifest (version) from the given server domain.
 * If the server is unreachable, Live is false and other fields are empty.
 * If the server's backend version is older than the desktop app version, Warning is set.
 */
export function GetServerManifest(domain: string): $CancellablePromise<$models.Manifest | null> {
    return $Call.ByID(2732474158, domain).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ListServers returns the list of server domains (folders that contain a db.sqlite).
 */
export function ListServers(): $CancellablePromise<string[]> {
    return $Call.ByID(3797823172).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * RemoveServer removes the server folder for the given domain.
 * If it was the current server, current is cleared or set to another existing server.
 */
export function RemoveServer(domain: string): $CancellablePromise<void> {
    return $Call.ByID(1781699399, domain);
}

/**
 * SetCurrentServer sets the current server to the given domain, opens its DB, and updates root.
 */
export function SetCurrentServer(domain: string): $CancellablePromise<void> {
    return $Call.ByID(3531693438, domain);
}

// Private type creation functions
const $$createType0 = $models.Manifest.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($Create.Any);
