// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {search} from '../models';
import {context} from '../models';

export function Replace(arg1:search.ReplaceParams):Promise<search.ReplaceResult>;

export function Search(arg1:search.SearchParams):Promise<search.SearchResult>;

export function SearchWithNodes(arg1:search.SearchParams):Promise<search.SearchResultWithNodes>;

export function SetContext(arg1:context.Context):Promise<void>;
