// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Replace(arg1) {
  return window['go']['search']['Search']['Replace'](arg1);
}

export function Search(arg1) {
  return window['go']['search']['Search']['Search'](arg1);
}

export function SearchWithNodes(arg1) {
  return window['go']['search']['Search']['SearchWithNodes'](arg1);
}

export function SetContext(arg1) {
  return window['go']['search']['Search']['SetContext'](arg1);
}
