// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateHistory(arg1) {
  return window['go']['history']['History']['CreateHistory'](arg1);
}

export function ListHistory(arg1) {
  return window['go']['history']['History']['ListHistory'](arg1);
}
