// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {history} from '../models';

export function CreateHistory(arg1:history.CreateQueryHistoryParams):Promise<void>;

export function ListHistory(arg1:history.ListHistoryParams):Promise<Array<history.HistoryEntry>>;

export function PruneOnStartup():Promise<void>;
