// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as tokenanalyzer$0 from "../../../github.com/selectDb/dialect/core/tokenanalyzer/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as generated$0 from "../db/generated/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function BuildWorkspaceGraph(): $CancellablePromise<void> {
    return $Call.ByID(3294711261);
}

/**
 * BuildWorkspaceGraphFromFS is the exported entry point for tests that need to
 * populate a Graph from a known workspace root without the full server setup.
 */
export function BuildWorkspaceGraphFromFS(fsCtx: $models.WorkspaceFS | null): $CancellablePromise<void> {
    return $Call.ByID(2358214, fsCtx);
}

/**
 * FileDatabases returns the databases a file is bound to. It answers from the
 * graph when the file's folder has been resolved, and from the file's sidecar
 * when it has not, so callers get the same answer either way without pulling
 * the whole folder into memory.
 */
export function FileDatabases(fileURI: string): $CancellablePromise<$models.DatabaseRef[]> {
    return $Call.ByID(2279693242, fileURI).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * FindDbItemNodeById walks the schema item tree of a DB instance and returns the
 * node with the given ID, or nil if not found.
 */
export function FindDbItemNodeById(dbInstanceID: string, nodeID: string): $CancellablePromise<$models.DBInstanceItemNode | null> {
    return $Call.ByID(1698115212, dbInstanceID, nodeID).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetDBInstanceNodeByID returns the DBInstanceNode with the given ID from the
 * current WorkspaceGraph, or nil if no such node exists. A db instance answers
 * to both its config ID and its URI.
 */
export function GetDBInstanceNodeByID(ID: string): $CancellablePromise<$models.DBInstanceNode | null> {
    return $Call.ByID(1444826651, ID).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GetEnvFilePath returns the path to the .env file for a given folder URI.
 */
export function GetEnvFilePath(folderURI: string): $CancellablePromise<string> {
    return $Call.ByID(1163996644, folderURI);
}

/**
 * GetFileNodeByID returns the FileNode with the given ID from the
 * current WorkspaceGraph, or nil if no such node exists.
 * 
 * A file whose folder has never been opened is not in the graph yet, so a miss
 * resolves the folders along the file's path before giving up. That keeps
 * callers — a link into a file, a tab restored from the last session — working
 * without knowing which folders have been opened.
 */
export function GetFileNodeByID(fileID: string): $CancellablePromise<$models.FileNode | null> {
    return $Call.ByID(793692664, fileID).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * GetFolderNodeByID returns the FolderNode with the given ID from the current
 * graph, or nil when the ID is unknown or names something else.
 */
export function GetFolderNodeByID(id: string): $CancellablePromise<$models.FolderNode | null> {
    return $Call.ByID(4046279042, id).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * GetLintFilePath returns the path to the .lint file for the current workspace.
 */
export function GetLintFilePath(): $CancellablePromise<string> {
    return $Call.ByID(1594017646);
}

/**
 * GetThemeFilePath returns the path to the per-user .theme file. The theme is
 * personal to the user and lives outside every workspace, so a team cannot
 * dictate appearance through the shared repo.
 */
export function GetThemeFilePath(): $CancellablePromise<string> {
    return $Call.ByID(4131437934);
}

/**
 * GetUriSqlFileRefs returns SQL files in the same folder as the given URI (same-folder only).
 * Each candidate includes a short preview of the file content for the suggestion menu.
 */
export function GetUriSqlFileRefs(uri: string): $CancellablePromise<$models.SqlFileCandidate[]> {
    return $Call.ByID(1615993196, uri).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * GetUriVariables returns all available environment variables for a given URI,
 * walking up the folder hierarchy to collect variables. Child folder variables
 * take precedence over parent folder variables.
 */
export function GetUriVariables(uri: string): $CancellablePromise<$models.VariableCandidate[]> {
    return $Call.ByID(1674050077, uri).then(($result: any) => {
        return $$createType13($result);
    });
}

/**
 * GetWorkspaceGraph returns the workspace graph, building it on first use.
 * 
 * It also guarantees the graph is indexed: WorkspaceGraph is an exported field,
 * so a graph can be assigned rather than built, and every lookup goes through
 * the index.
 */
export function GetWorkspaceGraph(): $CancellablePromise<$models.WorkspaceNode | null> {
    return $Call.ByID(977516625).then(($result: any) => {
        return $$createType15($result);
    });
}

/**
 * InvalidateWorkspaceGraph clears the cached graph so the next GetWorkspaceGraph
 * rebuilds from the current server's DB and filesystem. Call when switching server.
 */
export function InvalidateWorkspaceGraph(): $CancellablePromise<void> {
    return $Call.ByID(44666656);
}

/**
 * ListWorkspaceFiles returns a node for every file in the workspace, without
 * adding any of them to the graph.
 * 
 * The graph holds the files of the folders that have been opened, which is what
 * the tree shows. A picker is the other case: it searches the whole workspace by
 * name, so it needs every file whether or not its folder has been opened. This
 * walks for them and leaves the graph as it is.
 */
export function ListWorkspaceFiles(): $CancellablePromise<($models.FileNode | null)[]> {
    return $Call.ByID(1349016154).then(($result: any) => {
        return $$createType16($result);
    });
}

/**
 * LoadConfig returns the merged personal config: built-in defaults overlaid with
 * the per-user .config (keybindings and editor snippets).
 */
export function LoadConfig(): $CancellablePromise<$models.ConfigResponse | null> {
    return $Call.ByID(2766015104).then(($result: any) => {
        return $$createType18($result);
    });
}

/**
 * LoadFolderEnvFile loads the .env file for a folder and updates its Variables map.
 */
export function LoadFolderEnvFile(folderNode: $models.FolderNode | null, wfs: $models.WorkspaceFS | null): $CancellablePromise<void> {
    return $Call.ByID(821143247, folderNode, wfs);
}

/**
 * LoadWorkspaceLint reads and parses the workspace .lint file.
 */
export function LoadWorkspaceLint(): $CancellablePromise<tokenanalyzer$0.LintFile> {
    return $Call.ByID(2616540178).then(($result: any) => {
        return $$createType20($result);
    });
}

/**
 * LoadWorkspaceTheme loads theme variables by merging the built-in defaults with
 * the per-user .theme overrides. The workspace layer is intentionally dropped:
 * appearance is the user's to own and follows them across every workspace.
 */
export function LoadWorkspaceTheme(): $CancellablePromise<$models.ThemeVariables | null> {
    return $Call.ByID(716865576).then(($result: any) => {
        return $$createType22($result);
    });
}

export function Mutate(commit: generated$0.MutationCommit): $CancellablePromise<void> {
    return $Call.ByID(3885302872, commit);
}

/**
 * NodeKind returns what the graph holds under an ID — "file", "folder" or
 * "db_instance" — and "" when it holds nothing. It answers the question a
 * filesystem event asks about a path that has just disappeared, where the node
 * is all that is left to say what it was.
 */
export function NodeKind(id: string): $CancellablePromise<string> {
    return $Call.ByID(3877926180, id);
}

export function RebuildWorkspaceGraph(): $CancellablePromise<void> {
    return $Call.ByID(3446660490);
}

/**
 * ResetWorkspaceLint writes the default .lint content to the workspace file.
 */
export function ResetWorkspaceLint(): $CancellablePromise<void> {
    return $Call.ByID(820951547);
}

/**
 * ResetWorkspaceTheme writes the default theme content to the per-user .theme file.
 */
export function ResetWorkspaceTheme(): $CancellablePromise<void> {
    return $Call.ByID(4215275803);
}

/**
 * ResolveFolder reads the files of the folder with the given URI, emits the
 * updated graph, and returns the folder. The frontend calls it when a folder is
 * opened; it is a no-op for a folder that is already resolved, and returns nil
 * for an unknown URI or a node that is not a folder, so callers do not have to
 * check first.
 * 
 * The folder comes back rather than only reaching the caller through the graph
 * event, because a caller that acts on what is in a folder — naming a new file
 * so it does not land on an existing one — needs it before the next render.
 */
export function ResolveFolder(folderURI: string): $CancellablePromise<$models.FolderNode | null> {
    return $Call.ByID(2843403334, folderURI).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * ResolveVariable resolves a $varName reference: env vars walk the folder tree (precedence),
 * SQL file refs use same-folder only.
 * Implements sqllang.VarReplacer.
 */
export function ResolveVariable(varName: string, folderID: string): $CancellablePromise<[string, boolean]> {
    return $Call.ByID(283933314, varName, folderID);
}

/**
 * UpdateWorkspaceExecutionLimits persists new execution limits on the current
 * workspace row (a tracked write that syncs to the team) and updates the
 * in-memory workspace node so the change takes effect immediately. It returns
 * the normalized values that were stored.
 */
export function UpdateWorkspaceExecutionLimits(statementTimeoutMs: number, maxResultSizeMB: number): $CancellablePromise<[number, number]> {
    return $Call.ByID(432308134, statementTimeoutMs, maxResultSizeMB);
}

/**
 * WorkspaceExecutionLimits returns the current workspace statement timeout (ms)
 * and max result size (MB), falling back to defaults when no workspace is loaded.
 */
export function WorkspaceExecutionLimits(): $CancellablePromise<[number, number]> {
    return $Call.ByID(3903243627);
}

// Private type creation functions
const $$createType0 = $models.DatabaseRef.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.DBInstanceItemNode.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $models.DBInstanceNode.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $models.FileNode.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $models.FolderNode.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = $models.SqlFileCandidate.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = $models.VariableCandidate.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = $models.WorkspaceNode.createFrom;
const $$createType15 = $Create.Nullable($$createType14);
const $$createType16 = $Create.Array($$createType7);
const $$createType17 = $models.ConfigResponse.createFrom;
const $$createType18 = $Create.Nullable($$createType17);
const $$createType19 = tokenanalyzer$0.LintConfigEntry.createFrom;
const $$createType20 = $Create.Array($$createType19);
const $$createType21 = $models.ThemeVariables.createFrom;
const $$createType22 = $Create.Nullable($$createType21);
