// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as core$0 from "../../../github.com/selectDb/dialect/core/models.js";

/**
 * ColumnMetadata contains editability information for a single column
 */
export class ColumnMetadata {
    /**
     * Whether this column's table has all primary keys present in result (enables editing)
     */
    "hasAllPrimaryKeys": boolean;

    /**
     * Whether this specific column is a primary key for its table
     */
    "isPrimaryKey": boolean;

    /**
     * Whether this specific column is a foreign key
     */
    "isForeignKey"?: boolean;

    /**
     * Database ID (only if hasAllPrimaryKeys)
     */
    "databaseId"?: string;

    /**
     * Schema name (only if hasAllPrimaryKeys)
     */
    "schema"?: string;

    /**
     * Table name (only if hasAllPrimaryKeys)
     */
    "table"?: string;

    /**
     * Original column name (before alias)
     */
    "originalColumnName"?: string;

    /**
     * Primary key column names for this table
     */
    "primaryKeys"?: string[];

    /**
     * Indices in result where primary key columns appear
     */
    "primaryKeysIdxs"?: number[];

    /**
     * Native column type (e.g. varchar(255), int4, mood)
     */
    "dataType"?: string;

    /**
     * Allowed values when the column is an enumerated type; drives the cell picker
     */
    "enumValues"?: string[];

    /** Creates a new ColumnMetadata instance. */
    constructor($$source: Partial<ColumnMetadata> = {}) {
        if (!("hasAllPrimaryKeys" in $$source)) {
            this["hasAllPrimaryKeys"] = false;
        }
        if (!("isPrimaryKey" in $$source)) {
            this["isPrimaryKey"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ColumnMetadata instance from a string or object.
     */
    static createFrom($$source: any = {}): ColumnMetadata {
        const $$createField7_0 = $$createType0;
        const $$createField8_0 = $$createType1;
        const $$createField10_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("primaryKeys" in $$parsedSource) {
            $$parsedSource["primaryKeys"] = $$createField7_0($$parsedSource["primaryKeys"]);
        }
        if ("primaryKeysIdxs" in $$parsedSource) {
            $$parsedSource["primaryKeysIdxs"] = $$createField8_0($$parsedSource["primaryKeysIdxs"]);
        }
        if ("enumValues" in $$parsedSource) {
            $$parsedSource["enumValues"] = $$createField10_0($$parsedSource["enumValues"]);
        }
        return new ColumnMetadata($$parsedSource as Partial<ColumnMetadata>);
    }
}

export class ConfigResponse {
    "keybindings": Keybinding[];
    "editor_snippets": EditorSnippet[];

    /** Creates a new ConfigResponse instance. */
    constructor($$source: Partial<ConfigResponse> = {}) {
        if (!("keybindings" in $$source)) {
            this["keybindings"] = [];
        }
        if (!("editor_snippets" in $$source)) {
            this["editor_snippets"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConfigResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): ConfigResponse {
        const $$createField0_0 = $$createType3;
        const $$createField1_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("keybindings" in $$parsedSource) {
            $$parsedSource["keybindings"] = $$createField0_0($$parsedSource["keybindings"]);
        }
        if ("editor_snippets" in $$parsedSource) {
            $$parsedSource["editor_snippets"] = $$createField1_0($$parsedSource["editor_snippets"]);
        }
        return new ConfigResponse($$parsedSource as Partial<ConfigResponse>);
    }
}

export class DBInstanceItemNode {
    "id": string;
    "uri": string;
    "type": string;
    "name": string;
    "path": string;
    "badges": string[];
    "metadata": any;
    "parent_id": string;
    "children": (DBInstanceItemNode | null)[];

    /** Creates a new DBInstanceItemNode instance. */
    constructor($$source: Partial<DBInstanceItemNode> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("uri" in $$source)) {
            this["uri"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("badges" in $$source)) {
            this["badges"] = [];
        }
        if (!("metadata" in $$source)) {
            this["metadata"] = null;
        }
        if (!("parent_id" in $$source)) {
            this["parent_id"] = "";
        }
        if (!("children" in $$source)) {
            this["children"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DBInstanceItemNode instance from a string or object.
     */
    static createFrom($$source: any = {}): DBInstanceItemNode {
        const $$createField5_0 = $$createType0;
        const $$createField8_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("badges" in $$parsedSource) {
            $$parsedSource["badges"] = $$createField5_0($$parsedSource["badges"]);
        }
        if ("children" in $$parsedSource) {
            $$parsedSource["children"] = $$createField8_0($$parsedSource["children"]);
        }
        return new DBInstanceItemNode($$parsedSource as Partial<DBInstanceItemNode>);
    }
}

export class DBInstanceNode {
    "id": string;
    "uri": string;
    "type": string;
    "name": string;
    "db_type": string;
    "dsn": string;
    "proxified"?: boolean;
    "ssh"?: DBInstanceSSHConfig | null;
    "folder_id": string;
    "workspace_id": string;
    "children": (DBInstanceItemNode | null)[];
    "files": (FileNode | null)[];
    "folders": (FolderNode | null)[];

    /** Creates a new DBInstanceNode instance. */
    constructor($$source: Partial<DBInstanceNode> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("uri" in $$source)) {
            this["uri"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("db_type" in $$source)) {
            this["db_type"] = "";
        }
        if (!("dsn" in $$source)) {
            this["dsn"] = "";
        }
        if (!("folder_id" in $$source)) {
            this["folder_id"] = "";
        }
        if (!("workspace_id" in $$source)) {
            this["workspace_id"] = "";
        }
        if (!("children" in $$source)) {
            this["children"] = [];
        }
        if (!("files" in $$source)) {
            this["files"] = [];
        }
        if (!("folders" in $$source)) {
            this["folders"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DBInstanceNode instance from a string or object.
     */
    static createFrom($$source: any = {}): DBInstanceNode {
        const $$createField7_0 = $$createType10;
        const $$createField10_0 = $$createType8;
        const $$createField11_0 = $$createType13;
        const $$createField12_0 = $$createType16;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ssh" in $$parsedSource) {
            $$parsedSource["ssh"] = $$createField7_0($$parsedSource["ssh"]);
        }
        if ("children" in $$parsedSource) {
            $$parsedSource["children"] = $$createField10_0($$parsedSource["children"]);
        }
        if ("files" in $$parsedSource) {
            $$parsedSource["files"] = $$createField11_0($$parsedSource["files"]);
        }
        if ("folders" in $$parsedSource) {
            $$parsedSource["folders"] = $$createField12_0($$parsedSource["folders"]);
        }
        return new DBInstanceNode($$parsedSource as Partial<DBInstanceNode>);
    }
}

/**
 * DBInstanceSSHConfig describes SSH tunneling configuration for a DB instance.
 * All sensitive values are expected to be provided via .env variables and
 * referenced using $VAR tokens.
 */
export class DBInstanceSSHConfig {
    "enabled": boolean;
    "host": string;
    "port": number;
    "user": string;

    /**
     * "password" | "private_key" | "agent" | "key_file"
     */
    "auth_method": string;
    "password": string;
    "private_key": string;

    /**
     * path to a private key file (desktop key_file auth)
     */
    "key_path": string;

    /**
     * pinned bastion public key
     */
    "host_key": string;

    /** Creates a new DBInstanceSSHConfig instance. */
    constructor($$source: Partial<DBInstanceSSHConfig> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("user" in $$source)) {
            this["user"] = "";
        }
        if (!("auth_method" in $$source)) {
            this["auth_method"] = "";
        }
        if (!("password" in $$source)) {
            this["password"] = "";
        }
        if (!("private_key" in $$source)) {
            this["private_key"] = "";
        }
        if (!("key_path" in $$source)) {
            this["key_path"] = "";
        }
        if (!("host_key" in $$source)) {
            this["host_key"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DBInstanceSSHConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): DBInstanceSSHConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DBInstanceSSHConfig($$parsedSource as Partial<DBInstanceSSHConfig>);
    }
}

/**
 * DatabaseRef is a single database reference in file metadata.
 */
export class DatabaseRef {
    "name": string;
    "id": string;

    /** Creates a new DatabaseRef instance. */
    constructor($$source: Partial<DatabaseRef> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("id" in $$source)) {
            this["id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DatabaseRef instance from a string or object.
     */
    static createFrom($$source: any = {}): DatabaseRef {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DatabaseRef($$parsedSource as Partial<DatabaseRef>);
    }
}

export class EditorSnippet {
    "prefix": string;
    "body": string;
    "description"?: string;

    /** Creates a new EditorSnippet instance. */
    constructor($$source: Partial<EditorSnippet> = {}) {
        if (!("prefix" in $$source)) {
            this["prefix"] = "";
        }
        if (!("body" in $$source)) {
            this["body"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EditorSnippet instance from a string or object.
     */
    static createFrom($$source: any = {}): EditorSnippet {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EditorSnippet($$parsedSource as Partial<EditorSnippet>);
    }
}

export class ExplainResult {
    "id"?: string;
    "root"?: core$0.ExplainNode | null;
    "totalCost"?: number | null;
    "raw"?: string;
    "errors"?: string[];

    /**
     * 1-based character offset when the DB reports an error location (e.g. Postgres)
     */
    "errorPosition"?: number | null;
    "durationMs"?: number;

    /** Creates a new ExplainResult instance. */
    constructor($$source: Partial<ExplainResult> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExplainResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ExplainResult {
        const $$createField1_0 = $$createType18;
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("root" in $$parsedSource) {
            $$parsedSource["root"] = $$createField1_0($$parsedSource["root"]);
        }
        if ("errors" in $$parsedSource) {
            $$parsedSource["errors"] = $$createField4_0($$parsedSource["errors"]);
        }
        return new ExplainResult($$parsedSource as Partial<ExplainResult>);
    }
}

export class FileNode {
    "id": string;
    "uri": string;
    "type": string;
    "name": string;
    "folder_id": string;
    "databases"?: DatabaseRef[];
    "queryResults"?: { [_ in string]?: QueryResult | null };
    "planResults"?: { [_ in string]?: ExplainResult | null };
    "explainResults"?: { [_ in string]?: ExplainResult | null };
    "badges": string[];

    /** Creates a new FileNode instance. */
    constructor($$source: Partial<FileNode> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("uri" in $$source)) {
            this["uri"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("folder_id" in $$source)) {
            this["folder_id"] = "";
        }
        if (!("badges" in $$source)) {
            this["badges"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileNode instance from a string or object.
     */
    static createFrom($$source: any = {}): FileNode {
        const $$createField5_0 = $$createType20;
        const $$createField6_0 = $$createType23;
        const $$createField7_0 = $$createType26;
        const $$createField8_0 = $$createType26;
        const $$createField9_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("databases" in $$parsedSource) {
            $$parsedSource["databases"] = $$createField5_0($$parsedSource["databases"]);
        }
        if ("queryResults" in $$parsedSource) {
            $$parsedSource["queryResults"] = $$createField6_0($$parsedSource["queryResults"]);
        }
        if ("planResults" in $$parsedSource) {
            $$parsedSource["planResults"] = $$createField7_0($$parsedSource["planResults"]);
        }
        if ("explainResults" in $$parsedSource) {
            $$parsedSource["explainResults"] = $$createField8_0($$parsedSource["explainResults"]);
        }
        if ("badges" in $$parsedSource) {
            $$parsedSource["badges"] = $$createField9_0($$parsedSource["badges"]);
        }
        return new FileNode($$parsedSource as Partial<FileNode>);
    }
}

export class FolderNode {
    "id": string;
    "uri": string;
    "type": string;
    "name": string;
    "folder_id": string;
    "files": (FileNode | null)[];
    "folders": (FolderNode | null)[];
    "db_instances": (DBInstanceNode | null)[];
    "variables"?: { [_ in string]?: string };
    "badges": string[];

    /** Creates a new FolderNode instance. */
    constructor($$source: Partial<FolderNode> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("uri" in $$source)) {
            this["uri"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("folder_id" in $$source)) {
            this["folder_id"] = "";
        }
        if (!("files" in $$source)) {
            this["files"] = [];
        }
        if (!("folders" in $$source)) {
            this["folders"] = [];
        }
        if (!("db_instances" in $$source)) {
            this["db_instances"] = [];
        }
        if (!("badges" in $$source)) {
            this["badges"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FolderNode instance from a string or object.
     */
    static createFrom($$source: any = {}): FolderNode {
        const $$createField5_0 = $$createType13;
        const $$createField6_0 = $$createType16;
        const $$createField7_0 = $$createType29;
        const $$createField8_0 = $$createType30;
        const $$createField9_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("files" in $$parsedSource) {
            $$parsedSource["files"] = $$createField5_0($$parsedSource["files"]);
        }
        if ("folders" in $$parsedSource) {
            $$parsedSource["folders"] = $$createField6_0($$parsedSource["folders"]);
        }
        if ("db_instances" in $$parsedSource) {
            $$parsedSource["db_instances"] = $$createField7_0($$parsedSource["db_instances"]);
        }
        if ("variables" in $$parsedSource) {
            $$parsedSource["variables"] = $$createField8_0($$parsedSource["variables"]);
        }
        if ("badges" in $$parsedSource) {
            $$parsedSource["badges"] = $$createField9_0($$parsedSource["badges"]);
        }
        return new FolderNode($$parsedSource as Partial<FolderNode>);
    }
}

export class Keybinding {
    "key": string;
    "command": string;
    "when"?: string;

    /** Creates a new Keybinding instance. */
    constructor($$source: Partial<Keybinding> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("command" in $$source)) {
            this["command"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Keybinding instance from a string or object.
     */
    static createFrom($$source: any = {}): Keybinding {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Keybinding($$parsedSource as Partial<Keybinding>);
    }
}

export class QueryResult {
    "id"?: string;
    "columns"?: string[];
    "rows"?: any[][];
    "affectedRows"?: number;
    "rowCount": number;
    "durationMs"?: number;
    "errors"?: string[];

    /**
     * 1-based character offset when the DB reports an error location
     */
    "errorPosition"?: number | null;
    "explain"?: ExplainResult | null;
    "page": number;
    "pageSize": number;

    /**
     * Streaming watermark (rows safe to read from index 0). Only meaningful on
     * page responses; "ready" / "partial" / "pending" disambiguates RowCount.
     */
    "available"?: number;
    "status"?: string;

    /**
     * Per-column editable metadata - populated for each column that can be edited
     */
    "columnMetadata"?: ColumnMetadata[];

    /** Creates a new QueryResult instance. */
    constructor($$source: Partial<QueryResult> = {}) {
        if (!("rowCount" in $$source)) {
            this["rowCount"] = 0;
        }
        if (!("page" in $$source)) {
            this["page"] = 0;
        }
        if (!("pageSize" in $$source)) {
            this["pageSize"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QueryResult instance from a string or object.
     */
    static createFrom($$source: any = {}): QueryResult {
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType32;
        const $$createField6_0 = $$createType0;
        const $$createField8_0 = $$createType25;
        const $$createField13_0 = $$createType34;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField1_0($$parsedSource["columns"]);
        }
        if ("rows" in $$parsedSource) {
            $$parsedSource["rows"] = $$createField2_0($$parsedSource["rows"]);
        }
        if ("errors" in $$parsedSource) {
            $$parsedSource["errors"] = $$createField6_0($$parsedSource["errors"]);
        }
        if ("explain" in $$parsedSource) {
            $$parsedSource["explain"] = $$createField8_0($$parsedSource["explain"]);
        }
        if ("columnMetadata" in $$parsedSource) {
            $$parsedSource["columnMetadata"] = $$createField13_0($$parsedSource["columnMetadata"]);
        }
        return new QueryResult($$parsedSource as Partial<QueryResult>);
    }
}

/**
 * SqlFileCandidate represents a SQL file in the same folder that can be referenced as $name
 */
export class SqlFileCandidate {
    /**
     * file name without .sql
     */
    "name": string;

    /**
     * relative path from workspace root for display
     */
    "path": string;

    /**
     * full URI
     */
    "uri": string;

    /**
     * first SqlFilePreviewLen chars of file content
     */
    "preview": string;

    /** Creates a new SqlFileCandidate instance. */
    constructor($$source: Partial<SqlFileCandidate> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("uri" in $$source)) {
            this["uri"] = "";
        }
        if (!("preview" in $$source)) {
            this["preview"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SqlFileCandidate instance from a string or object.
     */
    static createFrom($$source: any = {}): SqlFileCandidate {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SqlFileCandidate($$parsedSource as Partial<SqlFileCandidate>);
    }
}

export class ThemeVariables {
    "shared": { [_ in string]?: string };
    "light": { [_ in string]?: string };
    "dark": { [_ in string]?: string };

    /** Creates a new ThemeVariables instance. */
    constructor($$source: Partial<ThemeVariables> = {}) {
        if (!("shared" in $$source)) {
            this["shared"] = {};
        }
        if (!("light" in $$source)) {
            this["light"] = {};
        }
        if (!("dark" in $$source)) {
            this["dark"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ThemeVariables instance from a string or object.
     */
    static createFrom($$source: any = {}): ThemeVariables {
        const $$createField0_0 = $$createType30;
        const $$createField1_0 = $$createType30;
        const $$createField2_0 = $$createType30;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("shared" in $$parsedSource) {
            $$parsedSource["shared"] = $$createField0_0($$parsedSource["shared"]);
        }
        if ("light" in $$parsedSource) {
            $$parsedSource["light"] = $$createField1_0($$parsedSource["light"]);
        }
        if ("dark" in $$parsedSource) {
            $$parsedSource["dark"] = $$createField2_0($$parsedSource["dark"]);
        }
        return new ThemeVariables($$parsedSource as Partial<ThemeVariables>);
    }
}

export class UserNode {
    "id": string;
    "type": string;
    "name": string;

    /** Creates a new UserNode instance. */
    constructor($$source: Partial<UserNode> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UserNode instance from a string or object.
     */
    static createFrom($$source: any = {}): UserNode {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UserNode($$parsedSource as Partial<UserNode>);
    }
}

/**
 * VariableCandidate represents a single environment variable with its value and source
 */
export class VariableCandidate {
    "name": string;
    "value": string;

    /**
     * The folder name where this variable is defined
     */
    "source": string;

    /**
     * URI of the .env file where this variable is defined
     */
    "source_uri": string;

    /** Creates a new VariableCandidate instance. */
    constructor($$source: Partial<VariableCandidate> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("value" in $$source)) {
            this["value"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("source_uri" in $$source)) {
            this["source_uri"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VariableCandidate instance from a string or object.
     */
    static createFrom($$source: any = {}): VariableCandidate {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VariableCandidate($$parsedSource as Partial<VariableCandidate>);
    }
}

/**
 * WorkspaceFS encapsulates common path/URI computations for a single
 * workspace so that both the initial graph build and the filesystem watcher
 * share the exact same mapping logic.
 */
export class WorkspaceFS {
    "WorkspaceID": string;
    "WorkspaceRoot": string;
    "RootURI": string;

    /** Creates a new WorkspaceFS instance. */
    constructor($$source: Partial<WorkspaceFS> = {}) {
        if (!("WorkspaceID" in $$source)) {
            this["WorkspaceID"] = "";
        }
        if (!("WorkspaceRoot" in $$source)) {
            this["WorkspaceRoot"] = "";
        }
        if (!("RootURI" in $$source)) {
            this["RootURI"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkspaceFS instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkspaceFS {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorkspaceFS($$parsedSource as Partial<WorkspaceFS>);
    }
}

export class WorkspaceNode {
    "id": string;
    "type": string;
    "name": string;
    "is_owner": boolean;

    /**
     * Logo is the base64 of a 128x128 PNG, empty when unset. Stored bare rather
     * than as a data URL so a row can never carry its own media type into an
     * <img src>; the frontend adds the "data:image/png;base64," prefix.
     */
    "logo": string;

    /**
     * Execution limits are team policy stored on the workspace row (synced via
     * the backend), not in a workspace file.
     */
    "statement_timeout_ms": number;
    "max_result_size_mb": number;
    "user": UserNode | null;
    "folders": (FolderNode | null)[];
    "db_instances": (DBInstanceNode | null)[];

    /** Creates a new WorkspaceNode instance. */
    constructor($$source: Partial<WorkspaceNode> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("is_owner" in $$source)) {
            this["is_owner"] = false;
        }
        if (!("logo" in $$source)) {
            this["logo"] = "";
        }
        if (!("statement_timeout_ms" in $$source)) {
            this["statement_timeout_ms"] = 0;
        }
        if (!("max_result_size_mb" in $$source)) {
            this["max_result_size_mb"] = 0;
        }
        if (!("user" in $$source)) {
            this["user"] = null;
        }
        if (!("folders" in $$source)) {
            this["folders"] = [];
        }
        if (!("db_instances" in $$source)) {
            this["db_instances"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkspaceNode instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkspaceNode {
        const $$createField6_0 = $$createType36;
        const $$createField7_0 = $$createType16;
        const $$createField8_0 = $$createType29;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("user" in $$parsedSource) {
            $$parsedSource["user"] = $$createField6_0($$parsedSource["user"]);
        }
        if ("folders" in $$parsedSource) {
            $$parsedSource["folders"] = $$createField7_0($$parsedSource["folders"]);
        }
        if ("db_instances" in $$parsedSource) {
            $$parsedSource["db_instances"] = $$createField8_0($$parsedSource["db_instances"]);
        }
        return new WorkspaceNode($$parsedSource as Partial<WorkspaceNode>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = Keybinding.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = EditorSnippet.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = DBInstanceItemNode.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = DBInstanceSSHConfig.createFrom;
const $$createType10 = $Create.Nullable($$createType9);
const $$createType11 = FileNode.createFrom;
const $$createType12 = $Create.Nullable($$createType11);
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = FolderNode.createFrom;
const $$createType15 = $Create.Nullable($$createType14);
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = core$0.ExplainNode.createFrom;
const $$createType18 = $Create.Nullable($$createType17);
const $$createType19 = DatabaseRef.createFrom;
const $$createType20 = $Create.Array($$createType19);
const $$createType21 = QueryResult.createFrom;
const $$createType22 = $Create.Nullable($$createType21);
const $$createType23 = $Create.Map($Create.Any, $$createType22);
const $$createType24 = ExplainResult.createFrom;
const $$createType25 = $Create.Nullable($$createType24);
const $$createType26 = $Create.Map($Create.Any, $$createType25);
const $$createType27 = DBInstanceNode.createFrom;
const $$createType28 = $Create.Nullable($$createType27);
const $$createType29 = $Create.Array($$createType28);
const $$createType30 = $Create.Map($Create.Any, $Create.Any);
const $$createType31 = $Create.Array($Create.Any);
const $$createType32 = $Create.Array($$createType31);
const $$createType33 = ColumnMetadata.createFrom;
const $$createType34 = $Create.Array($$createType33);
const $$createType35 = UserNode.createFrom;
const $$createType36 = $Create.Nullable($$createType35);
