// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddUserToGroup(arg1, arg2) {
  return window['go']['group']['Group']['AddUserToGroup'](arg1, arg2);
}

export function AttachRoleToGroup(arg1, arg2) {
  return window['go']['group']['Group']['AttachRoleToGroup'](arg1, arg2);
}

export function CreateGroup(arg1) {
  return window['go']['group']['Group']['CreateGroup'](arg1);
}

export function DeleteGroup(arg1) {
  return window['go']['group']['Group']['DeleteGroup'](arg1);
}

export function DetachRoleFromGroup(arg1) {
  return window['go']['group']['Group']['DetachRoleFromGroup'](arg1);
}

export function ListGroupMembers(arg1) {
  return window['go']['group']['Group']['ListGroupMembers'](arg1);
}

export function ListGroupRoles(arg1) {
  return window['go']['group']['Group']['ListGroupRoles'](arg1);
}

export function ListGroups() {
  return window['go']['group']['Group']['ListGroups']();
}

export function RemoveUserFromGroup(arg1) {
  return window['go']['group']['Group']['RemoveUserFromGroup'](arg1);
}

export function RenameGroup(arg1, arg2) {
  return window['go']['group']['Group']['RenameGroup'](arg1, arg2);
}
