// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {group} from '../models';
import {generated} from '../models';

export function AddUserToGroup(arg1:string,arg2:string):Promise<void>;

export function AttachRoleToGroup(arg1:string,arg2:string):Promise<void>;

export function CreateGroup(arg1:string):Promise<generated.Group>;

export function DeleteGroup(arg1:string):Promise<void>;

export function DetachRoleFromGroup(arg1:string):Promise<void>;

export function ListGroupMembers(arg1:string):Promise<Array<group.GroupUserEntry>>;

export function ListGroupRoles(arg1:string):Promise<Array<group.GroupRoleEntry>>;

export function ListGroups():Promise<Array<generated.ListGroupsByWorkspaceRow>>;

export function RemoveUserFromGroup(arg1:string):Promise<void>;

export function RenameGroup(arg1:string,arg2:string):Promise<void>;
