// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FSProvider defines an abstract filesystem API over selectdb:// URIs:
 * 
 * 	selectdb://workspaces/<workspaceId>/path/inside
 * 
 * The id is looked up, since a workspace lives wherever the user opened it. The
 * lookup is injected so this package and the graph resolve ids the same way.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Delete(params: $models.DeleteParams): $CancellablePromise<void> {
    return $Call.ByID(1470766170, params);
}

/**
 * ExecuteCommand executes a command in the workspace root directory.
 * Commands are executed with a timeout (default 30 seconds).
 * The working directory is set to the workspace root, or a subdirectory if workingDir is provided.
 */
export function ExecuteCommand(params: $models.ExecuteCommandParams): $CancellablePromise<$models.CommandResult> {
    return $Call.ByID(4089439265, params).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetOSPathFromURI resolves a logical URI to an absolute OS path.
 * 
 * Two URI namespaces are supported, both under the "selectdb://" scheme:
 * 
 *   - selectdb://workspaces/<id>/...  -> under that workspace's folder.
 *   - selectdb://user/...             -> under the per-user config dir, for
 *     personal files (.theme, .config) that live outside every workspace.
 */
export function GetOSPathFromURI(URI: string): $CancellablePromise<string> {
    return $Call.ByID(2881077120, URI);
}

export function Mkdir(params: $models.MkdirParams): $CancellablePromise<void> {
    return $Call.ByID(2118319240, params);
}

export function ReadDirectory(params: $models.ReadDirectoryParams): $CancellablePromise<$models.DirEntry[]> {
    return $Call.ByID(3973682456, params).then(($result: any) => {
        return $$createType2($result);
    });
}

export function ReadFile(params: $models.ReadFileParams): $CancellablePromise<string> {
    return $Call.ByID(4023950643, params);
}

export function Rename(params: $models.RenameParams): $CancellablePromise<void> {
    return $Call.ByID(3172507235, params);
}

export function Stat(uri: string): $CancellablePromise<$models.FileStat> {
    return $Call.ByID(251770855, uri).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * WorkspaceURIPrefix returns the prefix every workspace URI starts with,
 * "selectdb://workspaces/".
 * 
 * The frontend has to recognise a workspace URI — to tell a folder on disk from
 * a row in the search or git tree, say. This is how it asks, rather than
 * restating the scheme in TypeScript where it can drift from the Go side.
 */
export function WorkspaceURIPrefix(): $CancellablePromise<string> {
    return $Call.ByID(178242900);
}

/**
 * Write replaces the file at the URI. Its folder must exist: writes are
 * debounced, so one can land after what it was editing was deleted, and a write
 * that makes its own folder puts the deleted thing back. Making a file is a
 * Mkdir and then a Write.
 */
export function Write(params: $models.WriteParams): $CancellablePromise<void> {
    return $Call.ByID(2205286156, params);
}

// Private type creation functions
const $$createType0 = $models.CommandResult.createFrom;
const $$createType1 = $models.DirEntry.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $models.FileStat.createFrom;
