// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class CommandResult {
    "stdout": string;
    "stderr": string;
    "exitCode": number;
    "error"?: string;

    /** Creates a new CommandResult instance. */
    constructor($$source: Partial<CommandResult> = {}) {
        if (!("stdout" in $$source)) {
            this["stdout"] = "";
        }
        if (!("stderr" in $$source)) {
            this["stderr"] = "";
        }
        if (!("exitCode" in $$source)) {
            this["exitCode"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CommandResult instance from a string or object.
     */
    static createFrom($$source: any = {}): CommandResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CommandResult($$parsedSource as Partial<CommandResult>);
    }
}

export class DeleteParams {
    "uri": string;
    "recursive": boolean;

    /** Creates a new DeleteParams instance. */
    constructor($$source: Partial<DeleteParams> = {}) {
        if (!("uri" in $$source)) {
            this["uri"] = "";
        }
        if (!("recursive" in $$source)) {
            this["recursive"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeleteParams instance from a string or object.
     */
    static createFrom($$source: any = {}): DeleteParams {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DeleteParams($$parsedSource as Partial<DeleteParams>);
    }
}

/**
 * DirEntry describes a single entry in a directory listing.
 */
export class DirEntry {
    "Name": string;
    "Type": FileType;

    /** Creates a new DirEntry instance. */
    constructor($$source: Partial<DirEntry> = {}) {
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Type" in $$source)) {
            this["Type"] = FileType.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DirEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): DirEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DirEntry($$parsedSource as Partial<DirEntry>);
    }
}

export class ExecuteCommandParams {
    "workspaceId": string;

    /**
     * Command to execute (e.g., "grep", "cat", "ls")
     */
    "command": string;

    /**
     * Command arguments
     */
    "args": string[];

    /**
     * Optional: relative path from workspace root
     */
    "workingDir"?: string;

    /**
     * Optional: timeout in seconds (default: 30)
     */
    "timeout"?: number;

    /** Creates a new ExecuteCommandParams instance. */
    constructor($$source: Partial<ExecuteCommandParams> = {}) {
        if (!("workspaceId" in $$source)) {
            this["workspaceId"] = "";
        }
        if (!("command" in $$source)) {
            this["command"] = "";
        }
        if (!("args" in $$source)) {
            this["args"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExecuteCommandParams instance from a string or object.
     */
    static createFrom($$source: any = {}): ExecuteCommandParams {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("args" in $$parsedSource) {
            $$parsedSource["args"] = $$createField2_0($$parsedSource["args"]);
        }
        return new ExecuteCommandParams($$parsedSource as Partial<ExecuteCommandParams>);
    }
}

/**
 * FileStat contains basic metadata about a filesystem entry.
 */
export class FileStat {
    "Type": FileType;
    "Size": number;
    "Mtime": string;

    /** Creates a new FileStat instance. */
    constructor($$source: Partial<FileStat> = {}) {
        if (!("Type" in $$source)) {
            this["Type"] = FileType.$zero;
        }
        if (!("Size" in $$source)) {
            this["Size"] = 0;
        }
        if (!("Mtime" in $$source)) {
            this["Mtime"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileStat instance from a string or object.
     */
    static createFrom($$source: any = {}): FileStat {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileStat($$parsedSource as Partial<FileStat>);
    }
}

export enum FileType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    FileTypeUnknown = 0,
    FileTypeFile = 1,
    FileTypeDirectory = 2,
};

export class MkdirParams {
    "uri": string;

    /** Creates a new MkdirParams instance. */
    constructor($$source: Partial<MkdirParams> = {}) {
        if (!("uri" in $$source)) {
            this["uri"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MkdirParams instance from a string or object.
     */
    static createFrom($$source: any = {}): MkdirParams {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MkdirParams($$parsedSource as Partial<MkdirParams>);
    }
}

export class ReadDirectoryParams {
    "uri": string;

    /** Creates a new ReadDirectoryParams instance. */
    constructor($$source: Partial<ReadDirectoryParams> = {}) {
        if (!("uri" in $$source)) {
            this["uri"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReadDirectoryParams instance from a string or object.
     */
    static createFrom($$source: any = {}): ReadDirectoryParams {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReadDirectoryParams($$parsedSource as Partial<ReadDirectoryParams>);
    }
}

export class ReadFileParams {
    "uri": string;
    "startLine"?: number | null;
    "endLine"?: number | null;

    /** Creates a new ReadFileParams instance. */
    constructor($$source: Partial<ReadFileParams> = {}) {
        if (!("uri" in $$source)) {
            this["uri"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReadFileParams instance from a string or object.
     */
    static createFrom($$source: any = {}): ReadFileParams {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReadFileParams($$parsedSource as Partial<ReadFileParams>);
    }
}

export class RenameParams {
    "old_uri": string;
    "new_uri": string;

    /** Creates a new RenameParams instance. */
    constructor($$source: Partial<RenameParams> = {}) {
        if (!("old_uri" in $$source)) {
            this["old_uri"] = "";
        }
        if (!("new_uri" in $$source)) {
            this["new_uri"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RenameParams instance from a string or object.
     */
    static createFrom($$source: any = {}): RenameParams {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RenameParams($$parsedSource as Partial<RenameParams>);
    }
}

export class WriteParams {
    "uri": string;
    "content": string;

    /** Creates a new WriteParams instance. */
    constructor($$source: Partial<WriteParams> = {}) {
        if (!("uri" in $$source)) {
            this["uri"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WriteParams instance from a string or object.
     */
    static createFrom($$source: any = {}): WriteParams {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WriteParams($$parsedSource as Partial<WriteParams>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
