// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {graph} from '../models';
import {tokenanalyzer} from '../models';
import {context} from '../models';
import {generated} from '../models';

export function BuildWorkspaceGraph():Promise<void>;

export function BuildWorkspaceGraphFromFS(arg1:graph.WorkspaceFS):Promise<void>;

export function FindDbItemNodeById(arg1:string,arg2:string):Promise<graph.DBInstanceItemNode>;

export function GetDBInstanceNodeByID(arg1:string):Promise<graph.DBInstanceNode>;

export function GetEnvFilePath(arg1:string):Promise<string>;

export function GetFileNodeByID(arg1:string):Promise<graph.FileNode>;

export function GetLintFilePath():Promise<string>;

export function GetThemeFilePath():Promise<string>;

export function GetUriSqlFileRefs(arg1:string):Promise<Array<graph.SqlFileCandidate>>;

export function GetUriVariables(arg1:string):Promise<Array<graph.VariableCandidate>>;

export function GetWorkspaceGraph():Promise<graph.WorkspaceNode>;

export function InvalidateWorkspaceGraph():Promise<void>;

export function LoadConfig():Promise<graph.ConfigResponse>;

export function LoadFolderEnvFile(arg1:graph.FolderNode,arg2:graph.WorkspaceFS):Promise<void>;

export function LoadWorkspaceLint():Promise<Array<tokenanalyzer.LintConfigEntry>>;

export function LoadWorkspaceTheme():Promise<graph.ThemeVariables>;

export function Mutate(arg1:context.Context,arg2:generated.MutationCommit):Promise<void>;

export function RebuildWorkspaceGraph():Promise<void>;

export function ResetWorkspaceLint():Promise<void>;

export function ResetWorkspaceTheme():Promise<void>;

export function ResolveVariable(arg1:string,arg2:string):Promise<string>;

export function UpdateWorkspaceExecutionLimits(arg1:number,arg2:number):Promise<number>;

export function WorkspaceExecutionLimits():Promise<number|number>;
