// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BuildWorkspaceGraph() {
  return window['go']['graph']['Graph']['BuildWorkspaceGraph']();
}

export function BuildWorkspaceGraphFromFS(arg1) {
  return window['go']['graph']['Graph']['BuildWorkspaceGraphFromFS'](arg1);
}

export function FindDbItemNodeById(arg1, arg2) {
  return window['go']['graph']['Graph']['FindDbItemNodeById'](arg1, arg2);
}

export function GetDBInstanceNodeByID(arg1) {
  return window['go']['graph']['Graph']['GetDBInstanceNodeByID'](arg1);
}

export function GetEnvFilePath(arg1) {
  return window['go']['graph']['Graph']['GetEnvFilePath'](arg1);
}

export function GetFileNodeByID(arg1) {
  return window['go']['graph']['Graph']['GetFileNodeByID'](arg1);
}

export function GetLintFilePath() {
  return window['go']['graph']['Graph']['GetLintFilePath']();
}

export function GetThemeFilePath() {
  return window['go']['graph']['Graph']['GetThemeFilePath']();
}

export function GetUriSqlFileRefs(arg1) {
  return window['go']['graph']['Graph']['GetUriSqlFileRefs'](arg1);
}

export function GetUriVariables(arg1) {
  return window['go']['graph']['Graph']['GetUriVariables'](arg1);
}

export function GetWorkspaceGraph() {
  return window['go']['graph']['Graph']['GetWorkspaceGraph']();
}

export function InvalidateWorkspaceGraph() {
  return window['go']['graph']['Graph']['InvalidateWorkspaceGraph']();
}

export function LoadConfig() {
  return window['go']['graph']['Graph']['LoadConfig']();
}

export function LoadFolderEnvFile(arg1, arg2) {
  return window['go']['graph']['Graph']['LoadFolderEnvFile'](arg1, arg2);
}

export function LoadWorkspaceLint() {
  return window['go']['graph']['Graph']['LoadWorkspaceLint']();
}

export function LoadWorkspaceTheme() {
  return window['go']['graph']['Graph']['LoadWorkspaceTheme']();
}

export function Mutate(arg1, arg2) {
  return window['go']['graph']['Graph']['Mutate'](arg1, arg2);
}

export function RebuildWorkspaceGraph() {
  return window['go']['graph']['Graph']['RebuildWorkspaceGraph']();
}

export function ResetWorkspaceLint() {
  return window['go']['graph']['Graph']['ResetWorkspaceLint']();
}

export function ResetWorkspaceTheme() {
  return window['go']['graph']['Graph']['ResetWorkspaceTheme']();
}

export function ResolveVariable(arg1, arg2) {
  return window['go']['graph']['Graph']['ResolveVariable'](arg1, arg2);
}

export function UpdateWorkspaceExecutionLimits(arg1, arg2) {
  return window['go']['graph']['Graph']['UpdateWorkspaceExecutionLimits'](arg1, arg2);
}

export function WorkspaceExecutionLimits() {
  return window['go']['graph']['Graph']['WorkspaceExecutionLimits']();
}
