package sqlite

import core "github.com/selectDb/dialect/core"

// sqliteTypes returns the five SQLite type affinities.
// SQLite has no queryable type catalog; affinities are hardcoded in the engine.
var sqliteTypes = []core.Type{
	{Name: "TEXT", Kind: "affinity", Display: "TEXT", Description: "Stores strings using the database encoding (UTF-8, UTF-16BE, or UTF-16LE)."},
	{Name: "INTEGER", Kind: "affinity", Display: "INTEGER", Description: "Stores signed integers in 1–8 bytes depending on magnitude."},
	{Name: "REAL", Kind: "affinity", Display: "REAL", Description: "Stores floating-point values as 8-byte IEEE 754 numbers."},
	{Name: "NUMERIC", Kind: "affinity", Display: "NUMERIC", Description: "Stores numeric values as INTEGER or REAL when lossless, otherwise as TEXT."},
	{Name: "BLOB", Kind: "affinity", Display: "BLOB", Description: "Stores data exactly as supplied, with no conversion."},
}

// sqliteFunctions is the hardcoded catalog of SQLite built-in functions.
// SQLite has no queryable function catalog; this list is derived from the official documentation.
// OIDs are stable sequential integers used as node identifiers, they have no meaning outside this app.
var sqliteFunctions = []core.Function{
	// ── Core scalar ──────────────────────────────────────────────────────────
	{OID: 1, Name: "abs", Args: "X", Result: "numeric", Kind: "function",
		Description: "Returns the absolute value of the numeric argument X. Returns NULL if X is NULL. Returns 0.0 if X is not a number."},
	{OID: 2, Name: "changes", Args: "", Result: "integer", Kind: "function",
		Description: "Returns the number of database rows changed by the most recent INSERT, UPDATE, or DELETE statement."},
	{OID: 3, Name: "char", Args: "X1, X2, ...", Result: "text", Kind: "function",
		Description: "Returns a string composed of characters having the unicode code point values of each argument."},
	{OID: 4, Name: "coalesce", Args: "X, Y, ...", Result: "any", Kind: "function",
		Description: "Returns a copy of its first non-NULL argument. Returns NULL if all arguments are NULL."},
	{OID: 5, Name: "format", Args: "FORMAT, ...", Result: "text", Kind: "function",
		Description: "Returns a string formed by substituting the following arguments into the FORMAT string (printf-style)."},
	{OID: 6, Name: "glob", Args: "X, Y", Result: "integer", Kind: "function",
		Description: "Equivalent to the expression 'Y GLOB X'. Note the argument order is reversed."},
	{OID: 7, Name: "hex", Args: "X", Result: "text", Kind: "function",
		Description: "Interprets its argument as a BLOB and returns an upper-case hexadecimal string of its content."},
	{OID: 8, Name: "ifnull", Args: "X, Y", Result: "any", Kind: "function",
		Description: "Returns a copy of its first non-NULL argument. Returns NULL if both arguments are NULL. Equivalent to coalesce(X,Y)."},
	{OID: 9, Name: "iif", Args: "X, Y, Z", Result: "any", Kind: "function",
		Description: "Returns Y if X is truthy, otherwise Z. Equivalent to CASE WHEN X THEN Y ELSE Z END."},
	{OID: 10, Name: "instr", Args: "X, Y", Result: "integer", Kind: "function",
		Description: "Finds the first occurrence of string Y within string X and returns the number of prior characters plus 1. Returns 0 if Y does not occur in X."},
	{OID: 11, Name: "last_insert_rowid", Args: "", Result: "integer", Kind: "function",
		Description: "Returns the ROWID of the last successful INSERT into a rowid table."},
	{OID: 12, Name: "length", Args: "X", Result: "integer", Kind: "function",
		Description: "Returns the number of characters (not bytes) in string X prior to the first NUL character. If X is a BLOB, returns the number of bytes."},
	{OID: 13, Name: "like", Args: "X, Y", Result: "integer", Kind: "function",
		Description: "Equivalent to the expression 'Y LIKE X'. A third escape character argument is also accepted."},
	{OID: 14, Name: "likelihood", Args: "X, Y", Result: "any", Kind: "function",
		Description: "Returns argument X unchanged. Y is a floating-point constant between 0.0 and 1.0 that hints the query planner about the expected truth probability of X."},
	{OID: 15, Name: "likely", Args: "X", Result: "any", Kind: "function",
		Description: "Returns argument X unchanged and hints the query planner that X is likely to be true."},
	{OID: 16, Name: "lower", Args: "X", Result: "text", Kind: "function",
		Description: "Returns a copy of string X with all ASCII characters converted to lower case."},
	{OID: 17, Name: "ltrim", Args: "X [, Y]", Result: "text", Kind: "function",
		Description: "Returns X with leading whitespace removed. If Y is specified, removes any characters in Y from the left of X."},
	{OID: 18, Name: "max", Args: "X, Y, ...", Result: "any", Kind: "function",
		Description: "Returns the argument with the maximum value (scalar form). NULL arguments are ignored. Returns NULL if all arguments are NULL."},
	{OID: 19, Name: "min", Args: "X, Y, ...", Result: "any", Kind: "function",
		Description: "Returns the argument with the minimum value (scalar form). NULL arguments are ignored. Returns NULL if all arguments are NULL."},
	{OID: 20, Name: "nullif", Args: "X, Y", Result: "any", Kind: "function",
		Description: "Returns its first argument if both arguments are different, otherwise returns NULL."},
	{OID: 21, Name: "octet_length", Args: "X", Result: "integer", Kind: "function",
		Description: "Returns the number of bytes in the encoding of string X. Returns NULL if X is NULL."},
	{OID: 22, Name: "printf", Args: "FORMAT, ...", Result: "text", Kind: "function",
		Description: "Alias for format(). Deprecated in favour of format()."},
	{OID: 23, Name: "quote", Args: "X", Result: "text", Kind: "function",
		Description: "Returns the text of an SQL literal that is the value of its argument. Strings are surrounded by single quotes with escaping; BLOBs are encoded as X'…'."},
	{OID: 24, Name: "random", Args: "", Result: "integer", Kind: "function",
		Description: "Returns a pseudo-random integer between -9223372036854775808 and +9223372036854775807."},
	{OID: 25, Name: "randomblob", Args: "N", Result: "blob", Kind: "function",
		Description: "Returns an N-byte BLOB containing pseudo-random bytes."},
	{OID: 26, Name: "replace", Args: "X, Y, Z", Result: "text", Kind: "function",
		Description: "Returns a copy of string X with all occurrences of string Y replaced by string Z."},
	{OID: 27, Name: "round", Args: "X [, Y]", Result: "real", Kind: "function",
		Description: "Rounds X to Y digits to the right of the decimal point. If Y is omitted, rounds to the nearest integer."},
	{OID: 28, Name: "rtrim", Args: "X [, Y]", Result: "text", Kind: "function",
		Description: "Returns X with trailing whitespace removed. If Y is specified, removes any characters in Y from the right of X."},
	{OID: 29, Name: "sign", Args: "X", Result: "integer", Kind: "function",
		Description: "Returns -1, 0, or +1 depending on whether the numeric argument X is negative, zero, or positive. Returns NULL if X is NULL."},
	{OID: 30, Name: "soundex", Args: "X", Result: "text", Kind: "function",
		Description: "Returns the Soundex encoding of string X as a four-character string beginning with a capital letter."},
	{OID: 31, Name: "sqlite_version", Args: "", Result: "text", Kind: "function",
		Description: "Returns the version string for the SQLite library (e.g. '3.46.0')."},
	{OID: 32, Name: "sqlite_source_id", Args: "", Result: "text", Kind: "function",
		Description: "Returns a string that identifies the specific version of the SQLite source code including the date, time, and a SHA3 hash of the check-in."},
	{OID: 33, Name: "sqlite_compileoption_get", Args: "N", Result: "text", Kind: "function",
		Description: "Returns the N-th compile-time option used to build SQLite, or NULL if N is out of range."},
	{OID: 34, Name: "sqlite_compileoption_used", Args: "X", Result: "integer", Kind: "function",
		Description: "Returns 1 if the compile-time option named X was used, 0 if not."},
	{OID: 35, Name: "sqlite_offset", Args: "X", Result: "integer", Kind: "function",
		Description: "Returns the byte offset in the database file for the beginning of the record from which X is read."},
	{OID: 36, Name: "substr", Args: "X, Y [, Z]", Result: "text", Kind: "function",
		Description: "Returns a substring of X starting at the Y-th character (1-based). If Z is given, returns at most Z characters. Negative Y counts from the right."},
	{OID: 37, Name: "substring", Args: "X, Y [, Z]", Result: "text", Kind: "function",
		Description: "Alias for substr(). Accepts the same arguments."},
	{OID: 38, Name: "total_changes", Args: "", Result: "integer", Kind: "function",
		Description: "Returns the total number of row changes caused by INSERT, UPDATE, or DELETE since the database connection was opened."},
	{OID: 39, Name: "trim", Args: "X [, Y]", Result: "text", Kind: "function",
		Description: "Returns X with leading and trailing whitespace removed. If Y is specified, removes any characters in Y from both ends of X."},
	{OID: 40, Name: "typeof", Args: "X", Result: "text", Kind: "function",
		Description: "Returns the data type of the expression X: 'null', 'integer', 'real', 'text', or 'blob'."},
	{OID: 41, Name: "unhex", Args: "X [, Y]", Result: "blob", Kind: "function",
		Description: "Returns the BLOB value encoded by the hexadecimal string X. If Y is provided, characters in Y are ignored inside X."},
	{OID: 42, Name: "unicode", Args: "X", Result: "integer", Kind: "function",
		Description: "Returns the numeric unicode code point of the first character of string X."},
	{OID: 43, Name: "unlikely", Args: "X", Result: "any", Kind: "function",
		Description: "Returns argument X unchanged and hints the query planner that X is unlikely to be true."},
	{OID: 44, Name: "upper", Args: "X", Result: "text", Kind: "function",
		Description: "Returns a copy of string X with all ASCII characters converted to upper case."},
	{OID: 45, Name: "zeroblob", Args: "N", Result: "blob", Kind: "function",
		Description: "Returns a BLOB consisting of N bytes of 0x00. SQLite manages these internally without allocating the full N bytes."},

	// ── Aggregate ────────────────────────────────────────────────────────────
	{OID: 46, Name: "avg", Args: "X", Result: "real", Kind: "aggregate",
		Description: "Returns the average value of all non-NULL values of X. Returns NULL if there are no non-NULL values."},
	{OID: 47, Name: "count", Args: "* | X", Result: "integer", Kind: "aggregate",
		Description: "count(*) returns the total number of rows. count(X) returns the number of rows where X is not NULL."},
	{OID: 48, Name: "group_concat", Args: "X [, Y]", Result: "text", Kind: "aggregate",
		Description: "Returns a string that is the concatenation of all non-NULL values of X. Y is the separator (default ',')."},
	{OID: 49, Name: "string_agg", Args: "X, Y", Result: "text", Kind: "aggregate",
		Description: "Alias for group_concat(X, Y). Added in SQLite 3.44.0."},
	{OID: 50, Name: "sum", Args: "X", Result: "numeric", Kind: "aggregate",
		Description: "Returns the sum of all non-NULL values of X. Returns NULL if there are no non-NULL values. Integer inputs return an integer result if possible."},
	{OID: 51, Name: "total", Args: "X", Result: "real", Kind: "aggregate",
		Description: "Returns the sum of all non-NULL values of X as a real. Returns 0.0 if there are no non-NULL values (never returns NULL)."},
	{OID: 52, Name: "max", Args: "X", Result: "any", Kind: "aggregate",
		Description: "Returns the maximum value of all non-NULL values of X. Returns NULL if all values are NULL."},
	{OID: 53, Name: "min", Args: "X", Result: "any", Kind: "aggregate",
		Description: "Returns the minimum value of all non-NULL values of X. Returns NULL if all values are NULL."},

	// ── Date / time ──────────────────────────────────────────────────────────
	{OID: 54, Name: "date", Args: "timevalue [, modifier, ...]", Result: "text", Kind: "function",
		Description: "Returns the date in 'YYYY-MM-DD' format. Accepts an optional list of modifiers (e.g. '+1 day', 'start of month')."},
	{OID: 55, Name: "time", Args: "timevalue [, modifier, ...]", Result: "text", Kind: "function",
		Description: "Returns the time in 'HH:MM:SS' format. Accepts an optional list of modifiers."},
	{OID: 56, Name: "datetime", Args: "timevalue [, modifier, ...]", Result: "text", Kind: "function",
		Description: "Returns the date and time as 'YYYY-MM-DD HH:MM:SS'. Accepts an optional list of modifiers."},
	{OID: 57, Name: "julianday", Args: "timevalue [, modifier, ...]", Result: "real", Kind: "function",
		Description: "Returns the Julian day number, the fractional number of days since noon in Greenwich on November 24, 4714 BC."},
	{OID: 58, Name: "unixepoch", Args: "timevalue [, modifier, ...]", Result: "integer", Kind: "function",
		Description: "Returns the Unix timestamp (seconds since 1970-01-01 00:00:00 UTC). Added in SQLite 3.38.0."},
	{OID: 59, Name: "strftime", Args: "FORMAT, timevalue [, modifier, ...]", Result: "text", Kind: "function",
		Description: "Returns the date formatted according to FORMAT string. Supports %Y, %m, %d, %H, %M, %S, %s, %j, %w, %W, %f, and others."},
	{OID: 60, Name: "timediff", Args: "A, B", Result: "text", Kind: "function",
		Description: "Returns a string describing the time difference between time values A and B in the form '+YYYY-MM-DD HH:MM:SS.SSS'. Added in SQLite 3.43.0."},

	// ── Math (3.35.0+) ───────────────────────────────────────────────────────
	{OID: 61, Name: "acos", Args: "X", Result: "real", Kind: "function",
		Description: "Returns the arccosine of X in radians. X must be between -1.0 and 1.0."},
	{OID: 62, Name: "acosh", Args: "X", Result: "real", Kind: "function",
		Description: "Returns the hyperbolic arccosine of X. X must be ≥ 1.0."},
	{OID: 63, Name: "asin", Args: "X", Result: "real", Kind: "function",
		Description: "Returns the arcsine of X in radians. X must be between -1.0 and 1.0."},
	{OID: 64, Name: "asinh", Args: "X", Result: "real", Kind: "function",
		Description: "Returns the hyperbolic arcsine of X."},
	{OID: 65, Name: "atan", Args: "X", Result: "real", Kind: "function",
		Description: "Returns the arctangent of X in radians."},
	{OID: 66, Name: "atan2", Args: "Y, X", Result: "real", Kind: "function",
		Description: "Returns the arctangent of Y/X in radians, using the signs of both arguments to determine the quadrant."},
	{OID: 67, Name: "atanh", Args: "X", Result: "real", Kind: "function",
		Description: "Returns the hyperbolic arctangent of X. X must be between -1.0 and 1.0."},
	{OID: 68, Name: "ceil", Args: "X", Result: "real", Kind: "function",
		Description: "Returns the smallest integer value not less than X."},
	{OID: 69, Name: "ceiling", Args: "X", Result: "real", Kind: "function",
		Description: "Alias for ceil(X)."},
	{OID: 70, Name: "cos", Args: "X", Result: "real", Kind: "function",
		Description: "Returns the cosine of X, where X is in radians."},
	{OID: 71, Name: "cosh", Args: "X", Result: "real", Kind: "function",
		Description: "Returns the hyperbolic cosine of X."},
	{OID: 72, Name: "degrees", Args: "X", Result: "real", Kind: "function",
		Description: "Converts radians to degrees."},
	{OID: 73, Name: "exp", Args: "X", Result: "real", Kind: "function",
		Description: "Returns the value of e (2.71828…) raised to the power X."},
	{OID: 74, Name: "floor", Args: "X", Result: "real", Kind: "function",
		Description: "Returns the largest integer value not greater than X."},
	{OID: 75, Name: "ln", Args: "X", Result: "real", Kind: "function",
		Description: "Returns the natural (base-e) logarithm of X."},
	{OID: 76, Name: "log", Args: "X [, B]", Result: "real", Kind: "function",
		Description: "Returns the base-10 logarithm of X (one-argument form). With two arguments, returns the base-B logarithm of X."},
	{OID: 77, Name: "log2", Args: "X", Result: "real", Kind: "function",
		Description: "Returns the base-2 logarithm of X."},
	{OID: 78, Name: "log10", Args: "X", Result: "real", Kind: "function",
		Description: "Returns the base-10 logarithm of X."},
	{OID: 79, Name: "mod", Args: "X, Y", Result: "real", Kind: "function",
		Description: "Returns the remainder after dividing X by Y."},
	{OID: 80, Name: "pi", Args: "", Result: "real", Kind: "function",
		Description: "Returns the mathematical constant π (3.14159265358979…)."},
	{OID: 81, Name: "pow", Args: "X, Y", Result: "real", Kind: "function",
		Description: "Returns the value of X raised to the power Y."},
	{OID: 82, Name: "power", Args: "X, Y", Result: "real", Kind: "function",
		Description: "Alias for pow(X, Y)."},
	{OID: 83, Name: "radians", Args: "X", Result: "real", Kind: "function",
		Description: "Converts degrees to radians."},
	{OID: 84, Name: "sin", Args: "X", Result: "real", Kind: "function",
		Description: "Returns the sine of X, where X is in radians."},
	{OID: 85, Name: "sinh", Args: "X", Result: "real", Kind: "function",
		Description: "Returns the hyperbolic sine of X."},
	{OID: 86, Name: "sqrt", Args: "X", Result: "real", Kind: "function",
		Description: "Returns the square root of X."},
	{OID: 87, Name: "tan", Args: "X", Result: "real", Kind: "function",
		Description: "Returns the tangent of X, where X is in radians."},
	{OID: 88, Name: "tanh", Args: "X", Result: "real", Kind: "function",
		Description: "Returns the hyperbolic tangent of X."},
	{OID: 89, Name: "trunc", Args: "X", Result: "real", Kind: "function",
		Description: "Returns the integer part of X by rounding toward zero."},

	// ── JSON (3.38.0+) ───────────────────────────────────────────────────────
	{OID: 90, Name: "json", Args: "X", Result: "text", Kind: "function",
		Description: "Verifies that X is well-formed JSON and returns a minified version of it. Raises an error if X is not valid JSON."},
	{OID: 91, Name: "json_array", Args: "value, ...", Result: "text", Kind: "function",
		Description: "Returns a well-formed JSON array from its arguments."},
	{OID: 92, Name: "json_array_length", Args: "X [, P]", Result: "integer", Kind: "function",
		Description: "Returns the number of elements in the JSON array X, or in the array at path P within X."},
	{OID: 93, Name: "json_error_position", Args: "X", Result: "integer", Kind: "function",
		Description: "Returns the character position of the first syntax error in X, or 0 if X is well-formed JSON."},
	{OID: 94, Name: "json_extract", Args: "X, P, ...", Result: "any", Kind: "function",
		Description: "Extracts and returns one or more values from well-formed JSON X at the given paths P."},
	{OID: 95, Name: "json_insert", Args: "X, P, V, ...", Result: "text", Kind: "function",
		Description: "Inserts values into JSON X at paths P only when the path does not already exist."},
	{OID: 96, Name: "json_object", Args: "label, value, ...", Result: "text", Kind: "function",
		Description: "Returns a well-formed JSON object from alternating label/value pairs."},
	{OID: 97, Name: "json_patch", Args: "X, Y", Result: "text", Kind: "function",
		Description: "Applies RFC 7396 MergePatch Y to JSON document X and returns the result."},
	{OID: 98, Name: "json_pretty", Args: "X", Result: "text", Kind: "function",
		Description: "Returns a pretty-printed (indented) version of the JSON value X. Added in SQLite 3.46.0."},
	{OID: 99, Name: "json_quote", Args: "X", Result: "text", Kind: "function",
		Description: "Converts the SQL value X into its JSON representation."},
	{OID: 100, Name: "json_remove", Args: "X, P, ...", Result: "text", Kind: "function",
		Description: "Removes the values at paths P from JSON document X and returns the modified document."},
	{OID: 101, Name: "json_replace", Args: "X, P, V, ...", Result: "text", Kind: "function",
		Description: "Replaces values in JSON X at paths P only when the path already exists."},
	{OID: 102, Name: "json_set", Args: "X, P, V, ...", Result: "text", Kind: "function",
		Description: "Inserts or replaces values in JSON X at paths P (combines json_insert and json_replace behaviour)."},
	{OID: 103, Name: "json_type", Args: "X [, P]", Result: "text", Kind: "function",
		Description: "Returns the type of the outermost JSON value X, or of the element at path P: 'null', 'true', 'false', 'integer', 'real', 'text', 'array', or 'object'."},
	{OID: 104, Name: "json_valid", Args: "X [, flags]", Result: "integer", Kind: "function",
		Description: "Returns 1 if X is well-formed JSON, 0 otherwise. Optional flags control what is considered valid (e.g. JSON5 extensions)."},
	{OID: 105, Name: "json_group_array", Args: "X", Result: "text", Kind: "aggregate",
		Description: "Aggregate function that returns a JSON array built from all non-NULL values of X in the group."},
	{OID: 106, Name: "json_group_object", Args: "name, value", Result: "text", Kind: "aggregate",
		Description: "Aggregate function that returns a JSON object built from alternating name/value pairs across the group."},

	// ── Window ───────────────────────────────────────────────────────────────
	{OID: 107, Name: "row_number", Args: "", Result: "integer", Kind: "window",
		Description: "Returns the number of the current row within its partition, counting from 1."},
	{OID: 108, Name: "rank", Args: "", Result: "integer", Kind: "window",
		Description: "Returns the rank of the current row with gaps: if two rows tie at rank N, the next rank is N+2."},
	{OID: 109, Name: "dense_rank", Args: "", Result: "integer", Kind: "window",
		Description: "Returns the rank of the current row without gaps: tied rows share the same rank and the next rank is incremented by 1."},
	{OID: 110, Name: "percent_rank", Args: "", Result: "real", Kind: "window",
		Description: "Returns the relative rank of the current row: (rank - 1) / (total rows in partition - 1)."},
	{OID: 111, Name: "cume_dist", Args: "", Result: "real", Kind: "window",
		Description: "Returns the cumulative distribution: the fraction of partition rows with values ≤ the current row's value."},
	{OID: 112, Name: "ntile", Args: "N", Result: "integer", Kind: "window",
		Description: "Divides the partition into N buckets and returns the bucket number (1-based) for the current row."},
	{OID: 113, Name: "lag", Args: "expr [, offset [, default]]", Result: "any", Kind: "window",
		Description: "Returns the value of expr from the row that is offset rows before the current row in the partition. Returns default (or NULL) if the offset row does not exist."},
	{OID: 114, Name: "lead", Args: "expr [, offset [, default]]", Result: "any", Kind: "window",
		Description: "Returns the value of expr from the row that is offset rows after the current row in the partition. Returns default (or NULL) if the offset row does not exist."},
	{OID: 115, Name: "first_value", Args: "expr", Result: "any", Kind: "window",
		Description: "Returns the value of expr from the first row of the window frame."},
	{OID: 116, Name: "last_value", Args: "expr", Result: "any", Kind: "window",
		Description: "Returns the value of expr from the last row of the window frame."},
	{OID: 117, Name: "nth_value", Args: "expr, N", Result: "any", Kind: "window",
		Description: "Returns the value of expr from the N-th row of the window frame (1-based). Returns NULL if there is no N-th row."},
}
