package testutil

import (
	"slices"

	core "github.com/selectDb/dialect/core"
)

// PermCase is one statement and the rights it requires. The expectation is
// written before anything is measured: a case states what SQL means, not what
// the inspectors currently report.
//
// Needs is the exact set: every right in it is necessary, which the runner
// checks by withholding each one in turn, and together they are sufficient.
//
// Op is the operation the case expects the inspector to read, which is what
// separates a statement it understood from one it gave up on. Leave it out
// where the floor is the right answer.
//
// On names the dialects that parse the SQL. None means all of them.
type PermCase struct {
	Name   string
	SQL    string
	Needs  []Right
	Denied []Right
	Op     core.InspectOperation
	On     []string
	Why    string
}

// The tables of GetInspectTestMetadata. mainT1 and mainT2 share a schema and
// otherT3 does not, which is what the cross-schema cases turn on.
var (
	mainT1  = func(action string) Right { return Right{Action: action, Schema: "main", Table: "t1"} }
	mainT2  = func(action string) Right { return Right{Action: action, Schema: "main", Table: "t2"} }
	otherT3 = func(action string) Right { return Right{Action: action, Schema: "other", Table: "t3"} }
	mainV1  = func(action string) Right { return Right{Action: action, Schema: "main", Table: "v1"} }
)

// rowRights are the four row actions on every table. Denying them is how a case
// says the statement takes more than rows, however many tables it reaches.
var rowRights = []Right{
	{Action: core.ActionSelect},
	{Action: core.ActionInsert},
	{Action: core.ActionUpdate},
	{Action: core.ActionDelete},
}

// PermCasesFor are the cases a dialect parses.
func PermCasesFor(dialect string) []PermCase {
	var cases []PermCase
	for _, testCase := range permCases() {
		if len(testCase.On) == 0 || slices.Contains(testCase.On, dialect) {
			cases = append(cases, testCase)
		}
	}
	return cases
}

// permCases is every case, each naming the dialects that parse it. A case
// naming none holds for all of them, so a dialect added later opts into the
// rest one case at a time rather than inheriting whatever a condition did not
// exclude.
func permCases() []PermCase {
	return []PermCase{
		// --- the four data statements, which are the floor every other case
		// is measured against
		{
			Name:  "a select reads",
			SQL:   "SELECT c1 FROM t1",
			Needs: []Right{mainT1(core.ActionSelect)},
			Op:    core.InspectOpSelect,
			Why:   "it returns rows of t1",
		},
		{
			Name:  "an insert writes",
			SQL:   "INSERT INTO t1 (c1) VALUES (1)",
			Needs: []Right{mainT1(core.ActionInsert)},
			Op:    core.InspectOpInsert,
			Why:   "it adds a row and reads nothing",
		},
		{
			Name:  "an update writes",
			SQL:   "UPDATE t1 SET c1 = 1",
			Needs: []Right{mainT1(core.ActionUpdate)},
			Op:    core.InspectOpUpdate,
			Why:   "it changes rows and returns none",
		},
		{
			Name:  "a delete writes",
			SQL:   "DELETE FROM t1",
			Needs: []Right{mainT1(core.ActionDelete)},
			Op:    core.InspectOpDelete,
			Why:   "it removes rows and returns none",
		},
		{
			Name:  "a join through aliases",
			SQL:   "SELECT a.c1 FROM t1 a JOIN t2 b ON a.c1 = b.c1",
			Needs: []Right{mainT1(core.ActionSelect), mainT2(core.ActionSelect)},
			Op:    core.InspectOpSelect,
			Why:   "a and b are names for t1 and t2, and the join reads both",
		},
		{
			Name:  "an update filtered on a column it does not write",
			SQL:   "UPDATE t1 SET c2 = 'x' WHERE c1 = 1",
			Needs: []Right{mainT1(core.ActionUpdate), mainT1(core.ActionSelect)},
			Op:    core.InspectOpUpdate,
			Why:   "it writes c2 and reads c1 to choose the rows",
		},
		{
			Name:  "a filtered delete",
			SQL:   "DELETE FROM t1 WHERE c1 = 1",
			Needs: []Right{mainT1(core.ActionDelete), mainT1(core.ActionSelect)},
			Op:    core.InspectOpDelete,
			Why:   "it removes rows chosen by reading c1",
		},

		// --- a write carrying a read
		{
			Name:  "an insert from a select reads what it copies",
			SQL:   "INSERT INTO t1 (c1) SELECT c1 FROM t2",
			Needs: []Right{mainT1(core.ActionInsert), mainT2(core.ActionSelect)},
			Op:    core.InspectOpInsert,
			Why:   "holding insert alone would copy t2 into a table the role can read",
		},
		{
			Name: "an insert from a compound select reads every branch",
			SQL:  "INSERT INTO t1 (c1) SELECT c1 FROM t2 UNION SELECT c1 FROM other.t3",
			Needs: []Right{
				mainT1(core.ActionInsert),
				mainT2(core.ActionSelect),
				otherT3(core.ActionSelect),
			},
			Op:  core.InspectOpInsert,
			Why: "every branch is copied into t1, and the statement is still the insert that copies them",
		},
		{
			Name: "an insert from a compound select joined by EXCEPT",
			SQL:  "INSERT INTO t1 (c1) SELECT c1 FROM t2 EXCEPT SELECT c1 FROM other.t3",
			Needs: []Right{
				mainT1(core.ActionInsert),
				mainT2(core.ActionSelect),
				otherT3(core.ActionSelect),
			},
			Op:  core.InspectOpInsert,
			Why: "every set operator joins branches of one source query, not only UNION",
		},
		{
			Name: "a statement after a compound one is its own statement",
			SQL:  "INSERT INTO t1 (c1) SELECT c1 FROM t2 UNION SELECT 1; UPDATE other.t3 SET c1 = 2",
			Needs: []Right{
				mainT1(core.ActionInsert),
				mainT2(core.ActionSelect),
				otherT3(core.ActionUpdate),
			},
			Op:  core.InspectOpInsert,
			Why: "a compound query ends at the semicolon, so the update after it is a write of its own and not a branch the insert reads",
		},
		{
			On:   []string{"mysql", "sqlite"},
			Name: "REPLACE from a compound select reads every branch",
			SQL:  "REPLACE INTO t1 (c1) SELECT c1 FROM t2 UNION SELECT c1 FROM other.t3",
			Needs: []Right{
				mainT1(core.ActionInsert),
				mainT1(core.ActionDelete),
				mainT2(core.ActionSelect),
				otherT3(core.ActionSelect),
			},
			Op:  core.InspectOpInsert,
			Why: "it destroys rows of t1 and reads both branches to do it",
		},
		{
			Name:  "an update from a subquery reads it",
			SQL:   "UPDATE t1 SET c1 = (SELECT c1 FROM t2)",
			Needs: []Right{mainT1(core.ActionUpdate), mainT2(core.ActionSelect)},
			Op:    core.InspectOpUpdate,
			Why:   "the value written is read out of t2",
		},
		{
			Name: "a delete filtered by a subquery reads it",
			SQL:  "DELETE FROM t1 WHERE c1 IN (SELECT c1 FROM t2)",
			Needs: []Right{
				mainT1(core.ActionDelete),
				mainT1(core.ActionSelect).Only("c1"),
				mainT2(core.ActionSelect),
			},
			Op:  core.InspectOpDelete,
			Why: "which rows go depends on what t2 holds, and on the c1 of t1 the predicate compares",
		},

		// --- where a read hides. Each names a second relation somewhere the
		// FROM list does not, and a right on it is what says the inspector
		// found it.
		{
			Name:  "two tables in the FROM list",
			SQL:   "SELECT t1.c1, t2.c3 FROM t1, t2",
			Needs: []Right{mainT1(core.ActionSelect), mainT2(core.ActionSelect)},
			Op:    core.InspectOpSelect,
			Why:   "both are read, and a check that stops at the first reads t2 for free",
		},
		{
			Name:  "a join",
			SQL:   "SELECT t1.c1 FROM t1 JOIN t2 ON t1.c1 = t2.c1",
			Needs: []Right{mainT1(core.ActionSelect), mainT2(core.ActionSelect)},
			Op:    core.InspectOpSelect,
			Why:   "t2 decides which rows come back even where no column of it is returned",
		},
		{
			Name:  "a join across schemas",
			SQL:   "SELECT t1.c1 FROM t1 JOIN other.t3 ON t1.c1 = other.t3.c1",
			Needs: []Right{mainT1(core.ActionSelect), otherT3(core.ActionSelect)},
			Op:    core.InspectOpSelect,
			Why:   "a right on main.t3 is not a right on other.t3",
		},
		{
			Name:  "a CTE body",
			SQL:   "WITH x AS (SELECT c1 FROM t2) SELECT c1 FROM x",
			Needs: []Right{mainT2(core.ActionSelect)},
			Op:    core.InspectOpSelect,
			Why:   "x is not a table, and what it reads is t2",
		},
		{
			Name:  "a derived table",
			SQL:   "SELECT q.c1 FROM (SELECT c1 FROM t2) q",
			Needs: []Right{mainT2(core.ActionSelect)},
			Op:    core.InspectOpSelect,
			Why:   "the alias is not a table, and what it reads is t2",
		},
		{
			Name:  "a scalar subquery in the select list",
			SQL:   "SELECT c1, (SELECT c1 FROM t2 LIMIT 1) AS s FROM t1",
			Needs: []Right{mainT1(core.ActionSelect), mainT2(core.ActionSelect)},
			Op:    core.InspectOpSelect,
			Why:   "its value reaches the row whether or not the FROM names t2",
		},
		{
			Name:  "a subquery in WHERE",
			SQL:   "SELECT c1 FROM t1 WHERE c1 IN (SELECT c1 FROM t2)",
			Needs: []Right{mainT1(core.ActionSelect), mainT2(core.ActionSelect)},
			Op:    core.InspectOpSelect,
			Why:   "which rows come back is an answer about t2",
		},
		{
			Name:  "a subquery in HAVING",
			SQL:   "SELECT c1 FROM t1 GROUP BY c1 HAVING count(*) > (SELECT count(*) FROM t2)",
			Needs: []Right{mainT1(core.ActionSelect), mainT2(core.ActionSelect)},
			Op:    core.InspectOpSelect,
			Why:   "which groups survive is an answer about t2",
		},
		{
			Name:  "a subquery in ORDER BY",
			SQL:   "SELECT c1 FROM t1 ORDER BY (SELECT count(*) FROM t2)",
			Needs: []Right{mainT1(core.ActionSelect), mainT2(core.ActionSelect)},
			Op:    core.InspectOpSelect,
			Why:   "the order the rows come back in is an answer about t2",
		},
		{
			Name:  "each branch of a union",
			SQL:   "SELECT c1 FROM t1 UNION SELECT c1 FROM t2",
			Needs: []Right{mainT1(core.ActionSelect), mainT2(core.ActionSelect)},
			Op:    core.InspectOpSelect,
			Why:   "a branch nobody checked is a table read without a right",
		},
		{
			Name:  "a correlated EXISTS",
			SQL:   "SELECT c1 FROM t1 WHERE EXISTS (SELECT 1 FROM t2 WHERE t2.c1 = t1.c1)",
			Needs: []Right{mainT1(core.ActionSelect), mainT2(core.ActionSelect)},
			Op:    core.InspectOpSelect,
			Why:   "whether a row survives is an answer about t2",
		},
		{
			Name:  "a comma join returning no column of the second table",
			SQL:   "SELECT t1.c2 FROM t1, t2",
			Needs: []Right{mainT1(core.ActionSelect), mainT2(core.ActionSelect)},
			Op:    core.InspectOpSelect,
			Why:   "t2 is joined for its rows even though no column of it is named",
		},
		{
			Name:  "a predicate on a table nothing is returned from",
			SQL:   "SELECT t1.c2 FROM t1, t2 WHERE t2.c3 = 'secret'",
			Needs: []Right{mainT1(core.ActionSelect), mainT2(core.ActionSelect)},
			Op:    core.InspectOpSelect,
			Why:   "the predicate reports whether t2 holds that value, a row at a time",
		},
		{
			Name:  "a subquery in GROUP BY",
			SQL:   "SELECT count(*) FROM t1 GROUP BY (SELECT c1 FROM t2)",
			Needs: []Right{mainT1(core.ActionSelect), mainT2(core.ActionSelect)},
			Op:    core.InspectOpSelect,
			Why:   "how the rows are grouped is an answer about t2",
		},
		{
			Name:  "a subquery in a WINDOW clause",
			SQL:   "SELECT c1 FROM t1 WINDOW w AS (PARTITION BY (SELECT c1 FROM t2))",
			Needs: []Right{mainT1(core.ActionSelect), mainT2(core.ActionSelect)},
			Op:    core.InspectOpSelect,
			Why:   "how the rows are partitioned is an answer about t2",
		},
		{
			Name:  "a derived table joined first",
			SQL:   "SELECT * FROM (SELECT c1 FROM t1) x JOIN t2 ON x.c1 = t2.c1",
			Needs: []Right{mainT1(core.ActionSelect), mainT2(core.ActionSelect)},
			Op:    core.InspectOpSelect,
			Why:   "a derived table in a join is read as surely as one in a comma list",
		},
		{
			Name:  "a derived table joined second",
			SQL:   "SELECT * FROM t2 JOIN (SELECT c1 FROM t1) x ON x.c1 = t2.c1",
			Needs: []Right{mainT1(core.ActionSelect), mainT2(core.ActionSelect)},
			Op:    core.InspectOpSelect,
			Why:   "which side of the join it is on does not change what it reads",
		},
		{
			Name:  "a derived table outer joined",
			SQL:   "SELECT * FROM (SELECT c1 FROM t1) x LEFT JOIN t2 ON x.c1 = t2.c1",
			Needs: []Right{mainT1(core.ActionSelect), mainT2(core.ActionSelect)},
			Op:    core.InspectOpSelect,
			Why:   "an outer join reads both sides like an inner one",
		},
		{
			On:    []string{"postgresql"},
			Name:  "a parenthesized select",
			SQL:   "(SELECT c1 FROM t1)",
			Needs: []Right{mainT1(core.ActionSelect)},
			Op:    core.InspectOpSelect,
			Why:   "a select naming no table runs under any policy, so the parentheses must not hide t1",
		},
		{
			On:    []string{"postgresql"},
			Name:  "a doubly parenthesized select",
			SQL:   "((SELECT c1 FROM t1))",
			Needs: []Right{mainT1(core.ActionSelect)},
			Op:    core.InspectOpSelect,
			Why:   "however deep the parentheses, the read inside is of t1",
		},
		{
			On:    []string{"postgresql", "mysql"},
			Name:  "TABLE is a select",
			SQL:   "TABLE t1",
			Needs: []Right{mainT1(core.ActionSelect)},
			Op:    core.InspectOpSelect,
			Why:   "TABLE t1 is SELECT * FROM t1, and a select naming no table runs under any policy",
		},

		// --- a CTE on a write. Its body is read whether or not the write
		// names it, and a WHERE collected after the bodies must not replace them.
		{
			Name:  "a CTE an update does not use",
			SQL:   "WITH x AS (SELECT c1 FROM t1) UPDATE t2 SET c3 = 'x'",
			Needs: []Right{mainT1(core.ActionSelect), mainT2(core.ActionUpdate)},
			Op:    core.InspectOpUpdate,
			Why:   "the body reads t1 whatever the update does with it",
		},
		{
			Name:  "a CTE a delete does not use",
			SQL:   "WITH x AS (SELECT c1 FROM t1) DELETE FROM t2",
			Needs: []Right{mainT1(core.ActionSelect), mainT2(core.ActionDelete)},
			Op:    core.InspectOpDelete,
			Why:   "the body reads t1 whatever the delete does with it",
		},
		{
			Name:  "a CTE beside a filtered delete",
			SQL:   "WITH x AS (SELECT c1 FROM t1) DELETE FROM t2 WHERE c1 > 0",
			Needs: []Right{mainT1(core.ActionSelect), mainT2(core.ActionDelete), mainT2(core.ActionSelect)},
			Op:    core.InspectOpDelete,
			Why:   "the body reads t1 and the filter reads t2, and neither read stands in for the other",
		},
		{
			Name:  "a CTE beside a filtered update",
			SQL:   "WITH x AS (SELECT c1 FROM t1) UPDATE t2 SET c3 = 'x' WHERE c1 > 0",
			Needs: []Right{mainT1(core.ActionSelect), mainT2(core.ActionUpdate), mainT2(core.ActionSelect)},
			Op:    core.InspectOpUpdate,
			Why:   "the body reads t1 and the filter reads t2, and neither read stands in for the other",
		},

		// --- MERGE, which writes its target with whatever its WHEN clauses
		// name and reads the source it matches rows against. Only PostgreSQL
		// has the statement.
		{
			On:     []string{"postgresql"},
			Name:   "a merge that updates the matched row",
			SQL:    "MERGE INTO t1 USING t2 ON t1.c1 = t2.c1 WHEN MATCHED THEN UPDATE SET c2 = t2.c3",
			Needs:  []Right{mainT1(core.ActionUpdate), mainT1(core.ActionSelect), mainT2(core.ActionSelect)},
			Denied: []Right{Manage},
			Op:     core.InspectOpUpdate,
			Why:    "it rewrites rows of t1 chosen by reading t1 and t2, and manage is no right over rows",
		},
		{
			On:     []string{"postgresql"},
			Name:   "a merge that inserts the unmatched row",
			SQL:    "MERGE INTO t1 USING t2 ON t1.c1 = t2.c1 WHEN NOT MATCHED THEN INSERT (c1, c2) VALUES (t2.c1, t2.c3)",
			Needs:  []Right{mainT1(core.ActionInsert), mainT1(core.ActionSelect), mainT2(core.ActionSelect)},
			Denied: []Right{Manage},
			Op:     core.InspectOpInsert,
			Why:    "it adds rows to t1 and reads t1 and t2 to find which rows are missing",
		},
		{
			On:   []string{"postgresql"},
			Name: "a merge that updates and inserts",
			SQL:  "MERGE INTO t1 USING t2 ON t1.c1 = t2.c1 WHEN MATCHED THEN UPDATE SET c2 = t2.c3 WHEN NOT MATCHED THEN INSERT (c1) VALUES (t2.c1)",
			Needs: []Right{
				mainT1(core.ActionUpdate),
				mainT1(core.ActionInsert),
				mainT1(core.ActionSelect),
				mainT2(core.ActionSelect),
			},
			Op:  core.InspectOpUpdate,
			Why: "each WHEN clause is an action of its own, and neither right stands in for the other",
		},
		{
			On:   []string{"postgresql"},
			Name: "a merge that deletes the matched row",
			SQL:  "MERGE INTO t1 USING t2 ON t1.c1 = t2.c1 WHEN MATCHED THEN UPDATE SET c2 = t2.c3 WHEN MATCHED THEN DELETE",
			Needs: []Right{
				mainT1(core.ActionUpdate),
				mainT1(core.ActionDelete),
				mainT1(core.ActionSelect),
				mainT2(core.ActionSelect),
			},
			Op:  core.InspectOpUpdate,
			Why: "the DELETE clause removes rows of t1, which update on t1 is no right to do",
		},
		{
			On:    []string{"postgresql"},
			Name:  "a merge from a subquery source",
			SQL:   "MERGE INTO t1 USING (SELECT c1, c3 FROM t2) s ON t1.c1 = s.c1 WHEN MATCHED THEN UPDATE SET c2 = s.c3",
			Needs: []Right{mainT1(core.ActionUpdate), mainT1(core.ActionSelect), mainT2(core.ActionSelect)},
			Op:    core.InspectOpUpdate,
			Why:   "the source is a query over t2, and calling it s hides nothing",
		},
		{
			On:     []string{"postgresql"},
			Name:   "a merge storing a literal",
			SQL:    "MERGE INTO t1 a USING t2 b ON a.c1 = b.c1 WHEN MATCHED THEN UPDATE SET c2 = 'x'",
			Needs:  []Right{mainT1(core.ActionUpdate), mainT1(core.ActionSelect), mainT2(core.ActionSelect)},
			Denied: []Right{Manage},
			Op:     core.InspectOpUpdate,
			Why:    "it stores no value of t2, and still reads t2 to find the rows of t1 it rewrites",
		},
		{
			On:    []string{"postgresql"},
			Name:  "a merge through aliases across schemas",
			SQL:   "MERGE INTO t1 a USING other.t3 b ON a.c1 = b.c1 WHEN MATCHED THEN UPDATE SET c2 = b.c4",
			Needs: []Right{mainT1(core.ActionUpdate), mainT1(core.ActionSelect), otherT3(core.ActionSelect)},
			Op:    core.InspectOpUpdate,
			Why:   "a and b are names for t1 and other.t3, and the merge writes the first and reads the second",
		},
		{
			On:    []string{"postgresql"},
			Name:  "a merge on quoted names",
			SQL:   `MERGE INTO "t1" USING "t2" ON "t1".c1 = "t2".c1 WHEN MATCHED THEN UPDATE SET c2 = "t2".c3`,
			Needs: []Right{mainT1(core.ActionUpdate), mainT1(core.ActionSelect), mainT2(core.ActionSelect)},
			Op:    core.InspectOpUpdate,
			Why:   "quoting a name does not change which relation it is",
		},
		{
			On:    []string{"postgresql"},
			Name:  "a merge whose source is a CTE",
			SQL:   "WITH s AS (SELECT c1, c3 FROM t2) MERGE INTO t1 USING s ON t1.c1 = s.c1 WHEN MATCHED THEN UPDATE SET c2 = s.c3",
			Needs: []Right{mainT1(core.ActionUpdate), mainT1(core.ActionSelect), mainT2(core.ActionSelect)},
			Op:    core.InspectOpUpdate,
			Why:   "s is the CTE body, which reads t2, and no relation of its own",
		},
		{
			On:   []string{"postgresql"},
			Name: "the columns a merge writes and the columns it reads",
			SQL:  "MERGE INTO t1 USING t2 ON t1.c1 = t2.c1 WHEN MATCHED THEN UPDATE SET c2 = t2.c3",
			Needs: []Right{
				mainT1(core.ActionUpdate).Only("c2"),
				mainT1(core.ActionSelect).Only("c1"),
				mainT2(core.ActionSelect).Only("c1"),
				mainT2(core.ActionSelect).Only("c3"),
			},
			Denied: []Right{mainT1(core.ActionUpdate), mainT2(core.ActionSelect)},
			Op:     core.InspectOpUpdate,
			Why:    "it writes c2, matches on c1 of both tables and stores t2.c3, and update on t1 is no right to read t1.c1",
		},

		// --- column-scoped grants. A right naming a column covers that column
		// and no other, so each case here is the whole set of columns the
		// statement reaches. A case that passes holding one column short of
		// that set is a column read without a right on it.
		{
			Name:  "a column the select list names",
			SQL:   "SELECT c1 FROM t1",
			Needs: []Right{mainT1(core.ActionSelect).Only("c1")},
			Op:    core.InspectOpSelect,
			Why:   "a grant on c1 alone is enough for a statement that reads c1 alone",
		},
		{
			Name:   "manage is not a right to read rows",
			SQL:    "SELECT c1 FROM t1",
			Needs:  []Right{mainT1(core.ActionSelect).Only("c1")},
			Denied: []Right{Manage},
			Op:     core.InspectOpSelect,
			Why:    "administration is a right over the connection, not over what the tables hold",
		},
		{
			Name:  "a star reaching every column",
			SQL:   "SELECT * FROM t1",
			Needs: []Right{mainT1(core.ActionSelect).Only("c1"), mainT1(core.ActionSelect).Only("c2")},
			Op:    core.InspectOpSelect,
			Why:   "the star is expanded against the catalog, so it returns c2 as surely as it names it",
		},
		{
			Name:  "a column only the WHERE reads",
			SQL:   "SELECT c1 FROM t1 WHERE c2 = 'x'",
			Needs: []Right{mainT1(core.ActionSelect).Only("c1"), mainT1(core.ActionSelect).Only("c2")},
			Op:    core.InspectOpSelect,
			Why:   "which rows come back is an answer about c2, one predicate at a time",
		},
		{
			Name:  "a column only the GROUP BY reads",
			SQL:   "SELECT count(*) FROM t1 GROUP BY c2",
			Needs: []Right{mainT1(core.ActionSelect).Only("c2")},
			Op:    core.InspectOpSelect,
			Why:   "one group per distinct value is the list of values",
		},
		{
			Name:  "a column only the ORDER BY reads",
			SQL:   "SELECT c1 FROM t1 ORDER BY c2",
			Needs: []Right{mainT1(core.ActionSelect).Only("c1"), mainT1(core.ActionSelect).Only("c2")},
			Op:    core.InspectOpSelect,
			Why:   "the order the rows come back in is the ordering of c2",
		},
		{
			Name: "a returned column beside the column a join matches on",
			SQL:  "SELECT t1.c2 FROM t1 JOIN t2 ON t1.c1 = t2.c1",
			Needs: []Right{
				mainT1(core.ActionSelect).Only("c1"),
				mainT1(core.ActionSelect).Only("c2"),
				mainT2(core.ActionSelect).Only("c1"),
			},
			Op:  core.InspectOpSelect,
			Why: "the column returned and the columns matched on are all read",
		},
		{
			Name: "the same across schemas",
			SQL:  "SELECT t1.c2 FROM t1 JOIN other.t3 ON t1.c1 = other.t3.c1",
			Needs: []Right{
				mainT1(core.ActionSelect).Only("c1"),
				mainT1(core.ActionSelect).Only("c2"),
				otherT3(core.ActionSelect).Only("c1"),
			},
			Op:  core.InspectOpSelect,
			Why: "a column right on other.t3 is not one on a table of the same name elsewhere",
		},
		{
			Name: "a column a subquery in ORDER BY reads",
			SQL:  "SELECT c1 FROM t1 ORDER BY (SELECT c1 FROM t2)",
			Needs: []Right{
				mainT1(core.ActionSelect).Only("c1"),
				mainT2(core.ActionSelect).Only("c1"),
			},
			Op:  core.InspectOpSelect,
			Why: "the order the rows come back in is an answer about that column of t2",
		},
		{
			Name: "a column only a join condition reads",
			SQL:  "SELECT t1.c1 FROM t1 JOIN t2 ON t1.c2 = t2.c3",
			Needs: []Right{
				mainT1(core.ActionSelect).Only("c1"),
				mainT1(core.ActionSelect).Only("c2"),
				mainT2(core.ActionSelect).Only("c3"),
			},
			Op:  core.InspectOpSelect,
			Why: "which pairs of rows match is an answer about both sides of the condition",
		},
		{
			Name:  "a column an expression reads",
			SQL:   "SELECT c1 || c2 FROM t1",
			On:    []string{"postgresql", "sqlite"},
			Needs: []Right{mainT1(core.ActionSelect).Only("c1"), mainT1(core.ActionSelect).Only("c2")},
			Op:    core.InspectOpSelect,
			Why:   "a column inside an expression is read whether or not it comes back under its own name",
		},
		{
			Name:  "a column a derived table reads",
			SQL:   "SELECT q.c1 FROM (SELECT c1 FROM t2) q",
			Needs: []Right{mainT2(core.ActionSelect).Only("c1")},
			Op:    core.InspectOpSelect,
			Why:   "the right is on the column of t2 the inner query reads, not on the alias",
		},
		{
			Name:  "a column of the other schema",
			SQL:   "SELECT c4 FROM other.t3",
			Needs: []Right{otherT3(core.ActionSelect).Only("c4")},
			Op:    core.InspectOpSelect,
			Why:   "a column right carries the schema its table is in",
		},
		{
			Name:  "the column an insert names",
			SQL:   "INSERT INTO t1 (c1) VALUES (1)",
			Needs: []Right{mainT1(core.ActionInsert).Only("c1")},
			Op:    core.InspectOpInsert,
			Why:   "insert is scoped to a column like every other data action",
		},
		{
			Name: "the column an update writes and the column it filters on",
			SQL:  "UPDATE t1 SET c1 = 1 WHERE c2 = 'x'",
			Needs: []Right{
				mainT1(core.ActionUpdate).Only("c1"),
				mainT1(core.ActionSelect).Only("c2"),
			},
			Denied: []Right{mainT1(core.ActionUpdate)},
			Op:     core.InspectOpUpdate,
			Why:    "c1 is written and c2 is read to choose the rows, and update on the table is not a right to read c2",
		},
		{
			Name:   "a delete is not scoped to a column",
			SQL:    "DELETE FROM t1 WHERE c2 = 'x'",
			Needs:  []Right{mainT1(core.ActionDelete), mainT1(core.ActionSelect).Only("c2")},
			Denied: []Right{mainT1(core.ActionDelete).Only("c2")},
			Op:     core.InspectOpDelete,
			Why:    "the row goes whole, so a grant naming the column it was chosen by is not a right to remove it, and choosing by c2 reads c2",
		},
		{
			Name:  "a column an assignment reads",
			SQL:   "UPDATE t1 SET c1 = c2",
			Needs: []Right{mainT1(core.ActionUpdate).Only("c1"), mainT1(core.ActionSelect).Only("c2")},
			Op:    core.InspectOpUpdate,
			Why:   "the value stored in c1 is read out of c2",
		},
		{
			Name:  "a column an aliased update filters on",
			SQL:   "UPDATE t1 AS a SET c1 = 1 WHERE a.c2 = 'x'",
			Needs: []Right{mainT1(core.ActionUpdate).Only("c1"), mainT1(core.ActionSelect).Only("c2")},
			Op:    core.InspectOpUpdate,
			Why:   "the alias names the target table, so a.c2 is c2 of t1",
		},
		{
			On:    []string{"postgresql", "sqlite"},
			Name:  "two actions on two columns of one table",
			SQL:   "INSERT INTO t1 (c1) VALUES (1) RETURNING c2",
			Needs: []Right{mainT1(core.ActionInsert).Only("c1"), mainT1(core.ActionSelect).Only("c2")},
			Op:    core.InspectOpInsert,
			Why:   "the column written and the column handed back are scoped apart",
		},

		{
			On:   []string{"postgresql", "sqlite"},
			Name: "a column a write reads the table it joins against on",
			SQL:  "UPDATE t1 SET c1 = 2 FROM t2 WHERE t1.c1 = t2.c1",
			Needs: []Right{
				mainT1(core.ActionUpdate).Only("c1"),
				mainT1(core.ActionSelect).Only("c1"),
				mainT2(core.ActionSelect).Only("c1"),
			},
			Op:  core.InspectOpUpdate,
			Why: "t2 is matched on c1 and nothing else of it is read, and the c1 of t1 it is matched against is read too",
		},
		{
			On:   []string{"mysql"},
			Name: "a column a multi-table write reads the other table on",
			SQL:  "UPDATE t1 JOIN t2 ON t1.c1 = t2.c1 SET t1.c2 = 'x'",
			Needs: []Right{
				mainT1(core.ActionUpdate).Only("c2"),
				mainT1(core.ActionSelect).Only("c1"),
				mainT2(core.ActionSelect).Only("c1"),
			},
			Op:  core.InspectOpUpdate,
			Why: "the join reads c1 of both and the SET list writes c2 of t1",
		},
		{
			On:   []string{"mysql"},
			Name: "a column ON DUPLICATE KEY UPDATE reads",
			SQL:  "INSERT INTO t1 (c1) VALUES (1) ON DUPLICATE KEY UPDATE c1 = c2",
			Needs: []Right{
				mainT1(core.ActionInsert).Only("c1"),
				mainT1(core.ActionSelect).Only("c2"),
				mainT1(core.ActionUpdate).Only("c1"),
			},
			Op:  core.InspectOpInsert,
			Why: "the value written over the old one is read out of c2",
		},
		{
			On:   []string{"mysql"},
			Name: "the column VALUES names is the one the insert proposed",
			SQL:  "INSERT INTO t1 (c1, c2) VALUES (1, 'x') ON DUPLICATE KEY UPDATE c2 = VALUES(c2)",
			Needs: []Right{
				mainT1(core.ActionInsert).Only("c1"),
				mainT1(core.ActionInsert).Only("c2"),
				mainT1(core.ActionUpdate).Only("c2"),
			},
			Op:  core.InspectOpInsert,
			Why: "VALUES(c2) is the caller's own value, so the row's c2 is written and not read",
		},
		{
			On:   []string{"postgresql", "sqlite"},
			Name: "the column EXCLUDED names is the one the insert proposed",
			SQL:  "INSERT INTO t1 (c1, c2) VALUES (1, 'x') ON CONFLICT (c1) DO UPDATE SET c2 = EXCLUDED.c2",
			Needs: []Right{
				mainT1(core.ActionInsert).Only("c1"),
				mainT1(core.ActionInsert).Only("c2"),
				mainT1(core.ActionUpdate).Only("c2"),
			},
			Op:  core.InspectOpInsert,
			Why: "EXCLUDED.c2 is the caller's own value, so the row's c2 is written and not read",
		},
		{
			On:   []string{"postgresql", "sqlite"},
			Name: "a column an upsert reads to update from",
			SQL:  "INSERT INTO t1 (c1) VALUES (1) ON CONFLICT (c1) DO UPDATE SET c1 = t1.c2",
			Needs: []Right{
				mainT1(core.ActionInsert).Only("c1"),
				mainT1(core.ActionSelect).Only("c2"),
				mainT1(core.ActionUpdate).Only("c1"),
			},
			Op:  core.InspectOpInsert,
			Why: "the value written over the old one is read out of c2",
		},

		{
			Name:  "a table-wide grant covers the columns under it",
			SQL:   "SELECT c1 FROM t1 WHERE c2 = 'x'",
			Needs: []Right{mainT1(core.ActionSelect)},
			Op:    core.InspectOpSelect,
			Why:   "a role granted the table reads every column of it, returned or tested",
		},
		{
			Name:  "a column a CTE body reads",
			SQL:   "WITH x AS (SELECT c1 FROM t2) SELECT c1 FROM x",
			Needs: []Right{mainT2(core.ActionSelect).Only("c1")},
			Op:    core.InspectOpSelect,
			Why:   "x is not a table, and the column behind it is c1 of t2",
		},
		{
			Name:  "a column each branch of a union reads",
			SQL:   "SELECT c1 FROM t1 UNION SELECT c3 FROM t2",
			Needs: []Right{mainT1(core.ActionSelect).Only("c1"), mainT2(core.ActionSelect).Only("c3")},
			Op:    core.InspectOpSelect,
			Why:   "a branch nobody scoped is a column read without a right",
		},
		{
			Name:  "a column the source of an INSERT ... SELECT reads",
			SQL:   "INSERT INTO t1 (c1) SELECT c3 FROM t2",
			Needs: []Right{mainT1(core.ActionInsert).Only("c1"), mainT2(core.ActionSelect).Only("c3")},
			Op:    core.InspectOpInsert,
			Why:   "the column written and the column it comes from are scoped apart",
		},
		{
			Name:  "a column the source of a CREATE TABLE AS reads",
			SQL:   "CREATE TABLE t9 AS SELECT c3 FROM t2",
			Needs: []Right{Manage, mainT2(core.ActionSelect).Only("c3")},
			Why:   "the table it makes is administration, and the rows it fills it with are a read of c3",
		},
		{
			Name:  "a column a scalar subquery in the select list reads",
			SQL:   "SELECT c1, (SELECT c3 FROM t2 LIMIT 1) AS s FROM t1",
			Needs: []Right{mainT1(core.ActionSelect).Only("c1"), mainT2(core.ActionSelect).Only("c3")},
			Op:    core.InspectOpSelect,
			Why:   "its value reaches the row whether or not the FROM names t2",
		},
		{
			Name: "a column a subquery in WHERE reads",
			SQL:  "SELECT c1 FROM t1 WHERE c2 IN (SELECT c3 FROM t2)",
			Needs: []Right{
				mainT1(core.ActionSelect).Only("c1"),
				mainT1(core.ActionSelect).Only("c2"),
				mainT2(core.ActionSelect).Only("c3"),
			},
			Op:  core.InspectOpSelect,
			Why: "which rows come back is an answer about c3 of t2 and c2 of t1",
		},
		{
			Name:  "a column only a HAVING reads",
			SQL:   "SELECT c1 FROM t1 GROUP BY c1 HAVING count(c2) > 1",
			Needs: []Right{mainT1(core.ActionSelect).Only("c1"), mainT1(core.ActionSelect).Only("c2")},
			Op:    core.InspectOpSelect,
			Why:   "which groups survive is an answer about c2",
		},
		{
			Name: "a column a correlated EXISTS reads",
			SQL:  "SELECT c1 FROM t1 WHERE EXISTS (SELECT 1 FROM t2 WHERE t2.c1 = t1.c2)",
			Needs: []Right{
				mainT1(core.ActionSelect).Only("c1"),
				mainT1(core.ActionSelect).Only("c2"),
				mainT2(core.ActionSelect).Only("c1"),
			},
			Op:  core.InspectOpSelect,
			Why: "whether a row survives is an answer about c1 of t2 and about the c2 of t1 it is compared to",
		},
		{
			Name: "a column an update's correlated subquery reaches out for",
			SQL:  "UPDATE t1 SET c1 = 1 WHERE EXISTS (SELECT 1 FROM t2 WHERE t2.c1 = t1.c2)",
			Needs: []Right{
				mainT1(core.ActionUpdate).Only("c1"),
				mainT1(core.ActionSelect).Only("c2"),
				mainT2(core.ActionSelect).Only("c1"),
			},
			Op:  core.InspectOpUpdate,
			Why: "c2 belongs to no relation the subquery names, so the right on it can only be asked for out here",
		},
		{
			Name: "a column a delete's correlated subquery reaches out for",
			SQL:  "DELETE FROM t1 WHERE EXISTS (SELECT 1 FROM t2 WHERE t2.c1 = t1.c2)",
			Needs: []Right{
				mainT1(core.ActionDelete),
				mainT1(core.ActionSelect).Only("c2"),
				mainT2(core.ActionSelect).Only("c1"),
			},
			Op:  core.InspectOpDelete,
			Why: "which rows go is an answer about c2, reached from inside the subquery",
		},
		{
			On:   []string{"mysql"},
			Name: "a column a write orders itself by",
			SQL:  "UPDATE t1 SET c1 = 1 ORDER BY c2 LIMIT 1",
			Needs: []Right{
				mainT1(core.ActionUpdate).Only("c1"),
				mainT1(core.ActionSelect).Only("c2"),
			},
			Op:  core.InspectOpUpdate,
			Why: "which single row is written is an answer about c2",
		},
		{
			On:   []string{"mysql"},
			Name: "a column a delete orders itself by",
			SQL:  "DELETE FROM t1 ORDER BY c2 LIMIT 1",
			Needs: []Right{
				mainT1(core.ActionDelete),
				mainT1(core.ActionSelect).Only("c2"),
			},
			Op:  core.InspectOpDelete,
			Why: "which single row goes is an answer about c2",
		},
		{
			Name:  "a column an alias qualifies",
			SQL:   "SELECT a.c1 FROM t1 a WHERE a.c2 = 'x'",
			Needs: []Right{mainT1(core.ActionSelect).Only("c1"), mainT1(core.ActionSelect).Only("c2")},
			Op:    core.InspectOpSelect,
			Why:   "a.c1 is c1 of t1, and the right is on the table rather than the alias",
		},
		{
			Name:  "a column named in another case",
			SQL:   "SELECT C1 FROM t1",
			Needs: []Right{mainT1(core.ActionSelect).Only("c1")},
			Op:    core.InspectOpSelect,
			Why:   "C1 and c1 are one column, so one right covers both spellings",
		},
		{
			On:    []string{"postgresql", "sqlite"},
			Name:  "a quoted column name",
			SQL:   `SELECT "c1" FROM t1`,
			Needs: []Right{mainT1(core.ActionSelect).Only("c1")},
			Op:    core.InspectOpSelect,
			Why:   "quoting spells the name, it does not make another column",
		},
		{
			On:    []string{"mysql"},
			Name:  "a column quoted in backticks",
			SQL:   "SELECT `c1` FROM t1",
			Needs: []Right{mainT1(core.ActionSelect).Only("c1")},
			Op:    core.InspectOpSelect,
			Why:   "MySQL quotes with backticks, and the name inside is the column",
		},
		{
			On:    []string{"mysql"},
			Name:  "a column an expression reads, in MySQL",
			SQL:   "SELECT CONCAT(c1, c2) FROM t1",
			Needs: []Right{mainT1(core.ActionSelect).Only("c1"), mainT1(core.ActionSelect).Only("c2")},
			Op:    core.InspectOpSelect,
			Why:   "a column inside a call is read whether or not it comes back under its own name",
		},

		// --- a CTE a write reads. The name is not a relation, so a right on
		// it is a right nobody can hold: what the case asks for is the right
		// on what the body reads.
		{
			Name: "a CTE a delete filters on",
			SQL:  "WITH x AS (SELECT c1 FROM t2) DELETE FROM t1 WHERE c1 IN (SELECT c1 FROM x)",
			Needs: []Right{
				mainT1(core.ActionDelete),
				mainT1(core.ActionSelect).Only("c1"),
				mainT2(core.ActionSelect).Only("c1"),
			},
			Op:  core.InspectOpDelete,
			Why: "x is not a table, and what it reads is c1 of t2",
		},
		{
			Name: "a CTE an update filters on",
			SQL:  "WITH x AS (SELECT c1 FROM t2) UPDATE t1 SET c1 = 1 WHERE c1 IN (SELECT c1 FROM x)",
			Needs: []Right{
				mainT1(core.ActionUpdate).Only("c1"),
				mainT1(core.ActionSelect).Only("c1"),
				mainT2(core.ActionSelect).Only("c1"),
			},
			Op:  core.InspectOpUpdate,
			Why: "x is not a table, and the right is on the c1 of t2 its body reads",
		},
		{
			On:   []string{"postgresql", "sqlite"},
			Name: "a CTE an insert copies from",
			SQL:  "WITH x AS (SELECT c1 FROM t2) INSERT INTO t1 (c1) SELECT c1 FROM x",
			Needs: []Right{
				mainT1(core.ActionInsert).Only("c1"),
				mainT2(core.ActionSelect).Only("c1"),
			},
			Op:  core.InspectOpInsert,
			Why: "the rows come from t2 through a name that is not a relation",
		},
		{
			Name: "a CTE an insert declares inside itself",
			SQL:  "INSERT INTO t1 (c1) WITH x AS (SELECT c1 FROM t2) SELECT c1 FROM x",
			Needs: []Right{
				mainT1(core.ActionInsert).Only("c1"),
				mainT2(core.ActionSelect).Only("c1"),
			},
			Op:  core.InspectOpInsert,
			Why: "a WITH inside the query expression reads the same as one before the statement",
		},
		{
			Name: "a recursive CTE a delete reads",
			SQL:  "WITH RECURSIVE x(n) AS (SELECT c1 FROM t2) DELETE FROM t1 WHERE c1 IN (SELECT n FROM x)",
			Needs: []Right{
				mainT1(core.ActionDelete),
				mainT1(core.ActionSelect).Only("c1"),
				mainT2(core.ActionSelect).Only("c1"),
			},
			Op:  core.InspectOpDelete,
			Why: "the column list renames c1 to n, and the right is still on c1 of t2",
		},
		{
			Name: "a CTE an assignment reads",
			SQL:  "WITH x AS (SELECT c1 FROM t2) UPDATE t1 SET c1 = (SELECT c1 FROM x LIMIT 1)",
			Needs: []Right{
				mainT1(core.ActionUpdate).Only("c1"),
				mainT2(core.ActionSelect).Only("c1"),
			},
			Op:  core.InspectOpUpdate,
			Why: "the value stored comes out of t2 through the CTE",
		},
		{
			On:   []string{"postgresql", "sqlite"},
			Name: "a CTE a delete reads beside a RETURNING",
			SQL:  "WITH x AS (SELECT c1 FROM t2) DELETE FROM t1 WHERE c1 IN (SELECT c1 FROM x) RETURNING c2",
			Needs: []Right{
				mainT1(core.ActionDelete),
				mainT1(core.ActionSelect).Only("c1"),
				mainT1(core.ActionSelect).Only("c2"),
				mainT2(core.ActionSelect).Only("c1"),
			},
			Op:  core.InspectOpDelete,
			Why: "the CTE is read, the filter reads c1, and the clause hands c2 back",
		},

		{
			Name: "a qualified name a CTE shares its spelling with",
			SQL:  "WITH zz AS (SELECT c1 FROM t2) DELETE FROM t1 WHERE c1 IN (SELECT c1 FROM other.zz)",
			Needs: []Right{
				mainT1(core.ActionDelete),
				mainT1(core.ActionSelect).Only("c1"),
				mainT2(core.ActionSelect).Only("c1"),
				Right{Action: core.ActionSelect, Schema: "other", Table: "zz"},
			},
			Op:  core.InspectOpDelete,
			Why: "only a bare name can be the CTE, so other.zz is a relation of its own and is read",
		},
		{
			On:   []string{"postgresql", "sqlite"},
			Name: "a CTE body naming what a later CTE declares",
			SQL:  "WITH a AS (SELECT c1 FROM t2), t2 AS (SELECT c1 FROM other.t3) DELETE FROM t1 WHERE c1 IN (SELECT c1 FROM a)",
			Needs: []Right{
				mainT1(core.ActionDelete),
				mainT1(core.ActionSelect).Only("c1"),
				mainT2(core.ActionSelect).Only("c1"),
				otherT3(core.ActionSelect).Only("c1"),
			},
			Op:  core.InspectOpDelete,
			Why: "a plain WITH exposes only the names declared before a body, so a body reads relations rather than its siblings",
		},

		{
			Name: "a CTE shadowing a table a nested read names",
			SQL:  "WITH t2 AS (SELECT c1 FROM other.t3) SELECT c1 FROM t1 WHERE c1 IN (SELECT c1 FROM t2)",
			Needs: []Right{
				mainT1(core.ActionSelect).Only("c1"),
				otherT3(core.ActionSelect),
			},
			Denied: []Right{mainT1(core.ActionSelect).Only("c1"), mainT2(core.ActionSelect)},
			Op:     core.InspectOpSelect,
			Why:    "the bare t2 is the CTE, so main.t2 is never read and a right on it is no help",
		},

		{
			Name: "a CTE named like the table the write targets",
			SQL:  "WITH t2 AS (SELECT c1 FROM other.t3) UPDATE main.t2 SET c3 = 'x' WHERE c1 IN (SELECT c1 FROM t2)",
			Needs: []Right{
				mainT2(core.ActionUpdate).Only("c3"),
				mainT2(core.ActionSelect).Only("c1"),
				otherT3(core.ActionSelect).Only("c1"),
			},
			Op:  core.InspectOpUpdate,
			Why: "the target is written with its schema, so the CTE spelled the same way does not take it",
		},
		{
			On:   []string{"postgresql"},
			Name: "a CTE named like the table a data-modifying CTE writes",
			SQL:  "WITH t2 AS (SELECT c1 FROM other.t3), x AS (DELETE FROM main.t2 RETURNING c1) SELECT c1 FROM x",
			Needs: []Right{
				mainT2(core.ActionDelete),
				mainT2(core.ActionSelect),
				otherT3(core.ActionSelect),
			},
			Op:  core.InspectOpDelete,
			Why: "the delete is a nested statement, and a CTE spelled like its target does not take it",
		},
		{
			Name: "a schema-qualified name a CTE cannot shadow",
			SQL:  "WITH t2 AS (SELECT c1 FROM other.t3) SELECT c1 FROM t1 WHERE c1 IN (SELECT c1 FROM main.t2)",
			Needs: []Right{
				mainT1(core.ActionSelect).Only("c1"),
				mainT2(core.ActionSelect).Only("c1"),
				otherT3(core.ActionSelect),
			},
			Op:  core.InspectOpSelect,
			Why: "writing the schema names the table whatever the WITH declared, so both relations are read",
		},

		// --- a view. The statement names it as it names a table and carries
		// nothing of what it reads, so the right is the one held on the view.
		{
			Name:   "a read through a view",
			SQL:    "SELECT c5 FROM v1",
			Needs:  []Right{mainV1(core.ActionSelect).Only("c5")},
			Denied: []Right{mainT1(core.ActionSelect), mainT2(core.ActionSelect)},
			Op:     core.InspectOpSelect,
			Why:    "a right on the tables a view may be over is not a right on the view",
		},
		{
			Name:  "a column of a view",
			SQL:   "SELECT c5 FROM v1 WHERE c1 = 1",
			Needs: []Right{mainV1(core.ActionSelect).Only("c5"), mainV1(core.ActionSelect).Only("c1")},
			Op:    core.InspectOpSelect,
			Why:   "the columns of a view are scoped like a table's",
		},
		{
			Name:  "a write through a view",
			SQL:   "UPDATE v1 SET c5 = 'x'",
			Needs: []Right{mainV1(core.ActionUpdate).Only("c5")},
			Op:    core.InspectOpUpdate,
			Why:   "an updatable view is written through, and the write is on the view",
		},
		{
			On:   []string{"postgresql"},
			Name: "a merge whose target is a view",
			SQL:  "MERGE INTO main.v1 AS v USING main.t2 AS s ON v.c1 = s.c1 WHEN MATCHED THEN UPDATE SET c5 = 'x'",
			Needs: []Right{
				mainV1(core.ActionUpdate).Only("c5"),
				mainV1(core.ActionSelect).Only("c1"),
				mainT2(core.ActionSelect).Only("c1"),
			},
			Denied: []Right{Manage},
			Op:     core.InspectOpUpdate,
			Why:    "the same edit spelled as an UPDATE takes the same rights on the view, so the spelling cannot change them",
		},

		// --- how a relation is named. The rule is one relation, however it is
		// spelled, and a name that resolves to nothing is refused rather than
		// guessed at.
		{
			Name:  "a schema-qualified name",
			SQL:   "SELECT c1 FROM main.t1",
			Needs: []Right{mainT1(core.ActionSelect)},
			Op:    core.InspectOpSelect,
			Why:   "main.t1 and t1 are the same table",
		},
		{
			Name:  "a name in another schema",
			SQL:   "SELECT c1 FROM other.t3",
			Needs: []Right{otherT3(core.ActionSelect)},
			Op:    core.InspectOpSelect,
			Why:   "a right on main is not a right on other",
		},
		{
			Name:  "an alias",
			SQL:   "SELECT x.c1 FROM t1 AS x",
			Needs: []Right{mainT1(core.ActionSelect)},
			Op:    core.InspectOpSelect,
			Why:   "the alias is a name for t1, not a relation of its own",
		},
		{
			Name:  "an alias named after another table",
			SQL:   "SELECT x.c1 FROM t1 AS x, t2 AS t1",
			Needs: []Right{mainT1(core.ActionSelect), mainT2(core.ActionSelect)},
			Op:    core.InspectOpSelect,
			Why:   "calling t2 by the name t1 must not hide either of them",
		},
		{
			Name:  "a CTE named after a table",
			SQL:   "WITH t1 AS (SELECT c1 FROM t2) SELECT c1 FROM t1",
			Needs: []Right{mainT2(core.ActionSelect)},
			Op:    core.InspectOpSelect,
			Why:   "the statement reads the CTE, so the table it shadows is never touched",
		},
		{
			Name:  "a qualified name a CTE shadows",
			SQL:   "WITH t1 AS (SELECT c1 FROM t2) SELECT c1 FROM main.t1",
			Needs: []Right{mainT1(core.ActionSelect), mainT2(core.ActionSelect)},
			Op:    core.InspectOpSelect,
			Why:   "qualifying reaches past the CTE to the real table, and the body still reads t2",
		},
		{
			Name:  "a name in another case",
			SQL:   "SELECT C1 FROM T1",
			Needs: []Right{mainT1(core.ActionSelect)},
			Op:    core.InspectOpSelect,
			Why:   "every dialect here folds an unquoted name, so T1 is t1",
		},

		// --- statements that name no table and change nothing
		{
			// A connection check is the commonest statement there is, and it
			// reports nothing about any table, so it asks for nothing. That
			// also makes it the one case that must run under a policy
			// granting nothing at all.
			Name:  "a select of a constant names no table",
			SQL:   "SELECT 1",
			Needs: nil,
			Why:   "it reads no table, so there is nothing to hold a right on",
		},

		// --- schema changes, which are the administration right
		{
			Name:  "creating a table is administration",
			SQL:   "CREATE TABLE t9 (c1 INTEGER)",
			Needs: []Right{Manage},
			Op:    core.InspectOpCreate,
			Why:   "the schema is not data",
		},
		{
			Name:  "creating a table from a query reads the query",
			SQL:   "CREATE TABLE t9 AS SELECT c1 FROM t1",
			Needs: []Right{Manage, mainT1(core.ActionSelect)},
			Op:    core.InspectOpCreate,
			Why:   "manage covers making the table, not reading t1 into it",
		},
		{
			Name:  "creating a view reads what it selects",
			SQL:   "CREATE VIEW v1 AS SELECT c1 FROM t1",
			Needs: []Right{Manage, mainT1(core.ActionSelect)},
			Op:    core.InspectOpCreate,
			Why:   "the view body is a read that anyone selecting the view inherits",
		},
		{
			Name:   "creating a table from a compound query reads every branch",
			SQL:    "CREATE TABLE t9 AS SELECT c1 FROM t2 UNION SELECT c1 FROM other.t3",
			Needs:  []Right{Manage, mainT2(core.ActionSelect), otherT3(core.ActionSelect)},
			Denied: rowRights,
			Op:     core.InspectOpCreate,
			Why:    "select on one branch does not make a table, and manage does not read the other",
		},
		{
			Name:   "creating a view from a compound query reads every branch",
			SQL:    "CREATE VIEW v9 AS SELECT c1 FROM t2 UNION SELECT c1 FROM other.t3",
			Needs:  []Right{Manage, mainT2(core.ActionSelect), otherT3(core.ActionSelect)},
			Denied: rowRights,
			Op:     core.InspectOpCreate,
			Why:    "the view body reads both branches, and anyone selecting the view inherits that read",
		},
		{
			Name:  "altering a table is administration",
			SQL:   "ALTER TABLE t1 ADD COLUMN c9 INTEGER",
			Needs: []Right{Manage},
			Op:    core.InspectOpAlter,
			Why:   "it changes the schema",
		},
		{
			Name:   "dropping a table is administration",
			SQL:    "DROP TABLE t1",
			Needs:  []Right{Manage},
			Denied: rowRights,
			Op:     core.InspectOpDrop,
			Why:    "delete removes rows, drop removes the table",
		},
		{
			Name:  "the four row rights together are not manage",
			SQL:   "DROP TABLE t1",
			Needs: []Right{Manage},
			Denied: []Right{
				mainT1(core.ActionSelect),
				mainT1(core.ActionInsert),
				mainT1(core.ActionUpdate),
				mainT1(core.ActionDelete),
			},
			Op:  core.InspectOpDrop,
			Why: "every right over the rows of a table is still not the right to remove the table",
		},

		// --- asking the planner about a statement. It reports what the server
		// knows about the rows, so it takes what the statement itself takes.
		{
			Name:  "EXPLAIN of a select",
			SQL:   "EXPLAIN SELECT c1 FROM t1",
			Needs: []Right{mainT1(core.ActionSelect)},
			Why:   "the plan reports what the server knows about the rows of t1",
		},
		{
			Name:  "EXPLAIN of an update",
			SQL:   "EXPLAIN UPDATE t1 SET c1 = 1",
			Needs: []Right{mainT1(core.ActionUpdate)},
			Why:   "asking how a write would run is asking about the write",
		},

		{
			On:    []string{"postgresql", "mysql"},
			Name:  "truncating a table is administration",
			SQL:   "TRUNCATE TABLE t1",
			Needs: []Right{Manage},
			Op:    core.InspectOpTruncate,
			Why:   "it empties the table outside the transaction a delete runs in",
		},
		{
			On:    []string{"sqlite"},
			Name:  "SQLite has no TRUNCATE",
			SQL:   "TRUNCATE TABLE t1",
			Needs: []Right{Manage},
			Why:   "a statement the grammar does not carry takes the administration right",
		},

		// --- rights and session statements
		{
			// SQLite has no GRANT, so its parser salvages a bare select, and
			// the floor is what refuses it.
			Name:   "granting a right is administration",
			SQL:    "GRANT SELECT ON t1 TO bob",
			Needs:  []Right{Manage},
			Denied: rowRights,
			Why:    "it hands a right to somebody else",
		},
		{
			Name:  "revoking a right is administration",
			SQL:   "REVOKE SELECT ON t1 FROM bob",
			Needs: []Right{Manage},
			Why:   "it takes a right away from somebody else",
		},
		{
			On:    []string{"postgresql", "sqlite"},
			Name:  "an upsert that updates on conflict also updates",
			SQL:   "INSERT INTO t1 (c1) VALUES (1) ON CONFLICT (c1) DO UPDATE SET c2 = 'x'",
			Needs: []Right{mainT1(core.ActionInsert), mainT1(core.ActionUpdate)},
			Op:    core.InspectOpInsert,
			Why:   "a role holding insert alone would rewrite a row it may not update",
		},
		{
			On:    []string{"postgresql", "sqlite"},
			Name:  "an upsert that does nothing on conflict only inserts",
			SQL:   "INSERT INTO t1 (c1) VALUES (1) ON CONFLICT (c1) DO NOTHING",
			Needs: []Right{mainT1(core.ActionInsert)},
			Op:    core.InspectOpInsert,
			Why:   "the conflicting row is left exactly as it was",
		},
		{
			On:    []string{"postgresql", "sqlite"},
			Name:  "RETURNING hands rows back, which is a read",
			SQL:   "UPDATE t1 SET c1 = 1 RETURNING c2",
			Needs: []Right{mainT1(core.ActionUpdate), mainT1(core.ActionSelect)},
			Op:    core.InspectOpUpdate,
			Why:   "a role holding update alone would read t1 by writing to it",
		},
		{
			On:    []string{"postgresql", "sqlite"},
			Name:  "a delete returning what it removed",
			SQL:   "DELETE FROM t1 RETURNING c2",
			Needs: []Right{mainT1(core.ActionDelete), mainT1(core.ActionSelect)},
			Op:    core.InspectOpDelete,
			Why:   "the rows come back to the caller on their way out",
		},
		{
			On:    []string{"postgresql", "sqlite"},
			Name:  "an insert returning what it wrote",
			SQL:   "INSERT INTO t1 (c1) VALUES (1) RETURNING c2",
			Needs: []Right{mainT1(core.ActionInsert), mainT1(core.ActionSelect)},
			Op:    core.InspectOpInsert,
			Why:   "c2 is whatever the table put there, which the caller did not supply",
		},
		{
			On:   []string{"postgresql", "sqlite"},
			Name: "UPDATE ... FROM reads the table it joins against",
			SQL:  "UPDATE t1 SET c1 = 2 FROM t2 WHERE t1.c1 = t2.c1",
			Needs: []Right{
				mainT1(core.ActionUpdate),
				mainT1(core.ActionSelect).Only("c1"),
				mainT2(core.ActionSelect),
			},
			Op:  core.InspectOpUpdate,
			Why: "t2 is read to decide which rows of t1 change, it is not written, and the c1 of t1 it matches on is read too",
		},
		{
			On:   []string{"postgresql", "sqlite"},
			Name: "an upsert whose conflict predicate reads another table",
			SQL:  "INSERT INTO t1 (c1) VALUES (1) ON CONFLICT (c1) WHERE c1 IN (SELECT c1 FROM t2) DO NOTHING",
			Needs: []Right{
				mainT1(core.ActionInsert),
				mainT1(core.ActionSelect).Only("c1"),
				mainT2(core.ActionSelect),
			},
			Op:  core.InspectOpInsert,
			Why: "whether the row is inserted is an answer about t2, reached through the c1 of t1 the predicate reads",
		},
		{
			On:    []string{"postgresql", "sqlite"},
			Name:  "an upsert reading another table to update from it",
			SQL:   "INSERT INTO t1 (c1) SELECT c1 FROM t2 ON CONFLICT (c1) DO UPDATE SET c2 = 'x'",
			Needs: []Right{mainT1(core.ActionInsert), mainT1(core.ActionUpdate), mainT2(core.ActionSelect)},
			Op:    core.InspectOpInsert,
			Why:   "it inserts, it rewrites what was there, and it reads t2 to do it",
		},
		{
			On:    []string{"postgresql"},
			Name:  "EXPLAIN of a create from a query",
			SQL:   "EXPLAIN CREATE TABLE t9 AS SELECT c1 FROM t2",
			Needs: []Right{Manage, mainT2(core.ActionSelect)},
			Op:    core.InspectOpCreate,
			Why:   "wrapping a statement in EXPLAIN must not ask for less than the statement does",
		},
		{
			On: []string{"postgresql", "mysql"},
			// EXPLAIN ANALYZE runs the statement rather than describing it,
			// so nothing less than what the statement takes will do.
			Name:  "EXPLAIN ANALYZE of a delete",
			SQL:   "EXPLAIN ANALYZE DELETE FROM t1",
			Needs: []Right{mainT1(core.ActionDelete)},
			Why:   "the rows really go, so it is the delete it explains",
		},
		{
			On:    []string{"mysql", "sqlite"},
			Name:  "REPLACE deletes the row it conflicts with",
			SQL:   "REPLACE INTO t1 (c1) VALUES (1)",
			Needs: []Right{mainT1(core.ActionInsert), mainT1(core.ActionDelete)},
			Op:    core.InspectOpInsert,
			Why:   "the row that was there is gone, so insert alone destroys data",
		},
		{
			On:    []string{"mysql", "sqlite"},
			Name:  "REPLACE from a select reads what it copies",
			SQL:   "REPLACE INTO t1 (c1) SELECT c1 FROM t2",
			Needs: []Right{mainT1(core.ActionInsert), mainT1(core.ActionDelete), mainT2(core.ActionSelect)},
			Op:    core.InspectOpInsert,
			Why:   "it destroys rows of t1 and reads t2 to do it",
		},
		{
			On:    []string{"postgresql", "sqlite"},
			Name:  "a name in double quotes",
			SQL:   `SELECT c1 FROM "t1"`,
			Needs: []Right{mainT1(core.ActionSelect)},
			Op:    core.InspectOpSelect,
			Why:   "quoting is how a name is written, not which table it is",
		},
		{
			On:    []string{"postgresql"},
			Name:  "a quoted schema and table",
			SQL:   `SELECT c1 FROM "main"."t1"`,
			Needs: []Right{mainT1(core.ActionSelect)},
			Op:    core.InspectOpSelect,
			Why:   "both halves quoted is still main.t1",
		},
		{
			On:     []string{"postgresql"},
			Name:   "copying a file into a table",
			SQL:    "COPY t1 FROM '/tmp/x.csv'",
			Needs:  []Right{Manage},
			Denied: rowRights,
			Why:    "it reads a file the server can see and the caller may not",
		},
		{
			On:     []string{"postgresql"},
			Name:   "copying a table out to a file",
			SQL:    "COPY t1 TO '/tmp/x.csv'",
			Needs:  []Right{Manage},
			Denied: rowRights,
			Why:    "it writes rows somewhere the rules do not reach",
		},
		{
			On:    []string{"mysql", "sqlite"},
			Name:  "a name in backticks",
			SQL:   "SELECT c1 FROM `t1`",
			Needs: []Right{mainT1(core.ActionSelect)},
			Op:    core.InspectOpSelect,
			Why:   "backticks quote a name in MySQL, and SQLite takes them too",
		},
		{
			On:    []string{"mysql"},
			Name:  "a backticked schema and table",
			SQL:   "SELECT c1 FROM `main`.`t1`",
			Needs: []Right{mainT1(core.ActionSelect)},
			Op:    core.InspectOpSelect,
			Why:   "both halves quoted is still main.t1",
		},
		{
			On:     []string{"postgresql", "mysql"},
			Name:   "calling a procedure",
			SQL:    "CALL some_proc()",
			Needs:  []Right{Manage},
			Denied: rowRights,
			Why:    "what the procedure does is not in the statement",
		},
		{
			On:     []string{"mysql"},
			Name:   "loading a file into a table",
			SQL:    "LOAD DATA INFILE '/tmp/x.csv' INTO TABLE t1",
			Needs:  []Right{Manage},
			Denied: rowRights,
			Why:    "it reads a file the server can see and the caller may not",
		},
		{
			On:    []string{"mysql"},
			Name:  "locking a table",
			SQL:   "LOCK TABLES t1 WRITE",
			Needs: []Right{Manage},
			Why:   "holding a lock is a thing done to the server, not to rows",
		},
		{
			On:    []string{"mysql"},
			Name:  "ON DUPLICATE KEY UPDATE also updates",
			SQL:   "INSERT INTO t1 (c1) VALUES (1) ON DUPLICATE KEY UPDATE c2 = 'x'",
			Needs: []Right{mainT1(core.ActionInsert), mainT1(core.ActionUpdate)},
			Op:    core.InspectOpInsert,
			Why:   "a role holding insert alone would rewrite a row it may not update",
		},
		{
			On:   []string{"mysql"},
			Name: "a multi-table UPDATE writes what it sets and reads the rest",
			SQL:  "UPDATE t1 JOIN t2 ON t1.c1 = t2.c1 SET t1.c1 = 2",
			Needs: []Right{
				mainT1(core.ActionUpdate),
				mainT1(core.ActionSelect).Only("c1"),
				mainT2(core.ActionSelect),
			},
			Op:  core.InspectOpUpdate,
			Why: "t2 is joined against, so update on it is a right the statement does not need",
		},
		{
			On:   []string{"mysql"},
			Name: "a multi-table UPDATE writing both tables",
			SQL:  "UPDATE t1 JOIN t2 ON t1.c1 = t2.c1 SET t1.c1 = 2, t2.c3 = 'x'",
			Needs: []Right{
				mainT1(core.ActionUpdate).Only("c1"),
				mainT2(core.ActionUpdate).Only("c3"),
				mainT1(core.ActionSelect).Only("c1"),
				mainT2(core.ActionSelect).Only("c1"),
			},
			Op:  core.InspectOpUpdate,
			Why: "both are named by the SET list, so both are written, and the join reads the c1 of each",
		},
		{
			On:   []string{"mysql"},
			Name: "a multi-table DELETE reads what it joins against",
			SQL:  "DELETE t1 FROM t1 JOIN t2 ON t1.c1 = t2.c1",
			Needs: []Right{
				mainT1(core.ActionDelete),
				mainT1(core.ActionSelect).Only("c1"),
				mainT2(core.ActionSelect),
			},
			Op:  core.InspectOpDelete,
			Why: "which rows of t1 go is an answer about t2, and only t1 is deleted from",
		},
		{
			On:    []string{"mysql"},
			Name:  "ON DUPLICATE KEY UPDATE reading another table",
			SQL:   "INSERT INTO t1 (c1) VALUES (1) ON DUPLICATE KEY UPDATE c2 = (SELECT c3 FROM t2)",
			Needs: []Right{mainT1(core.ActionInsert), mainT1(core.ActionUpdate), mainT2(core.ActionSelect)},
			Op:    core.InspectOpInsert,
			Why:   "the value it writes over the old one is read out of t2",
		},
		{
			On:    []string{"sqlite"},
			Name:  "a name in square brackets",
			SQL:   "SELECT c1 FROM [t1]",
			Needs: []Right{mainT1(core.ActionSelect)},
			Op:    core.InspectOpSelect,
			Why:   "SQLite takes SQL Server quoting too",
		},
		{
			On:    []string{"sqlite"},
			Name:  "a quoted name in another case",
			SQL:   `SELECT c1 FROM "T1"`,
			Needs: []Right{mainT1(core.ActionSelect)},
			Op:    core.InspectOpSelect,
			Why:   "SQLite matches a table name without regard to case, quoted or not",
		},
		{
			On:     []string{"sqlite"},
			Name:   "attaching another database file",
			SQL:    "ATTACH DATABASE '/tmp/other.db' AS x",
			Needs:  []Right{Manage},
			Denied: rowRights,
			Why:    "it brings a whole database the rules say nothing about into reach",
		},
		{
			On:    []string{"sqlite"},
			Name:  "detaching one",
			SQL:   "DETACH DATABASE x",
			Needs: []Right{Manage},
			Why:   "what the connection can reach is not data",
		},
		{
			On:    []string{"sqlite"},
			Name:  "reading the schema through a pragma",
			SQL:   "PRAGMA table_info(t1)",
			Needs: []Right{Manage},
			Why:   "a pragma reads and writes settings rather than rows",
		},
		{
			On:    []string{"sqlite"},
			Name:  "vacuuming",
			SQL:   "VACUUM",
			Needs: []Right{Manage},
			Why:   "it rewrites the file the database lives in",
		},

		// --- a name the statement declares. A CTE or an alias is not a table,
		// so it asks for no right of its own; a qualified name is never one,
		// so it always asks for the table's.
		{
			Name:  "a select of an expression names no table",
			SQL:   "SELECT 1 + 1",
			Needs: nil,
			Why:   "it reads no table, so there is nothing to hold a right on",
		},
		{
			Name:  "a CTE an ORDER BY subquery reads",
			SQL:   "WITH x AS (SELECT c1 FROM t1) SELECT c1 FROM x ORDER BY (SELECT c1 FROM x)",
			Needs: []Right{mainT1(core.ActionSelect)},
			Op:    core.InspectOpSelect,
			Why:   "a subquery sees the CTEs of the query around it, so x is not a table there either",
		},
		{
			Name:  "a CTE a WHERE subquery reads",
			SQL:   "WITH x AS (SELECT c1 FROM t1) SELECT c1 FROM t2 WHERE c1 IN (SELECT c1 FROM x)",
			Needs: []Right{mainT1(core.ActionSelect), mainT2(core.ActionSelect)},
			Op:    core.InspectOpSelect,
			Why:   "x inside the subquery is the CTE, and what it reads is t1",
		},
		{
			Name:  "a CTE a scalar subquery reads",
			SQL:   "WITH x AS (SELECT c1 FROM t1) SELECT (SELECT count(*) FROM x) FROM t2",
			Needs: []Right{mainT1(core.ActionSelect), mainT2(core.ActionSelect)},
			Op:    core.InspectOpSelect,
			Why:   "x inside the subquery is the CTE, and the rows of t2 decide how many come back",
		},
		{
			Name:  "a CTE a HAVING subquery reads",
			SQL:   "WITH x AS (SELECT c1 FROM t1) SELECT c1 FROM t2 GROUP BY c1 HAVING count(*) > (SELECT count(*) FROM x)",
			Needs: []Right{mainT1(core.ActionSelect), mainT2(core.ActionSelect)},
			Op:    core.InspectOpSelect,
			Why:   "x inside the subquery is the CTE, and what it reads is t1",
		},
		{
			Name:  "a qualified name in ORDER BY past a derived table of that name",
			SQL:   "SELECT c1 FROM (SELECT c1 FROM t1) t2 ORDER BY (SELECT c1 FROM main.t2)",
			Needs: []Right{mainT1(core.ActionSelect), mainT2(core.ActionSelect)},
			Op:    core.InspectOpSelect,
			Why:   "an alias shadows the bare name, never the qualified one, so main.t2 is the table",
		},
		{
			Name:  "a qualified name in WHERE past a derived table of that name",
			SQL:   "SELECT c1 FROM (SELECT c1 FROM t1) t2 WHERE c1 IN (SELECT c1 FROM main.t2)",
			Needs: []Right{mainT1(core.ActionSelect), mainT2(core.ActionSelect)},
			Op:    core.InspectOpSelect,
			Why:   "an alias shadows the bare name, never the qualified one, so main.t2 is the table",
		},
		{
			Name:  "a qualified name in the select list past a derived table of that name",
			SQL:   "SELECT (SELECT c1 FROM main.t2) FROM (SELECT c1 FROM t1) t2",
			Needs: []Right{mainT1(core.ActionSelect), mainT2(core.ActionSelect)},
			Op:    core.InspectOpSelect,
			Why:   "an alias shadows the bare name, never the qualified one, so main.t2 is the table",
		},
		{
			Name:  "a qualified name in WHERE past a CTE of that name",
			SQL:   "WITH t2 AS (SELECT c1 FROM t1) SELECT c1 FROM t2 WHERE c1 IN (SELECT c1 FROM main.t2)",
			Needs: []Right{mainT1(core.ActionSelect), mainT2(core.ActionSelect)},
			Op:    core.InspectOpSelect,
			Why:   "a CTE shadows the bare name, never the qualified one, so main.t2 is the table",
		},
		{
			Name:  "a qualified name joined beside a CTE of that name",
			SQL:   "WITH t3 AS (SELECT c1 FROM t1) SELECT * FROM t3 JOIN other.t3 ON 1=1",
			Needs: []Right{mainT1(core.ActionSelect), otherT3(core.ActionSelect)},
			Op:    core.InspectOpSelect,
			Why:   "naming a CTE after a table must not hide the table when it is written with its schema",
		},
		{
			Name:  "a qualified name in the default schema joined beside a CTE of that name",
			SQL:   "WITH t2 AS (SELECT c1 FROM t1) SELECT * FROM t2 JOIN main.t2 ON 1=1",
			Needs: []Right{mainT1(core.ActionSelect), mainT2(core.ActionSelect)},
			Op:    core.InspectOpSelect,
			Why:   "the CTE is t2 and the table is main.t2, and the statement reads both",
		},
		{
			Name:  "a qualified name comma-listed beside a CTE of that name",
			SQL:   "WITH t3 AS (SELECT c1 FROM t1) SELECT other.t3.c4 FROM t3, other.t3",
			Needs: []Right{mainT1(core.ActionSelect), otherT3(core.ActionSelect)},
			Op:    core.InspectOpSelect,
			Why:   "naming a CTE after a table must not hide the table when it is written with its schema",
		},
		{
			Name:  "a CTE named after a table it does not read",
			SQL:   "WITH t2 AS (SELECT c1 FROM t1) SELECT c1 FROM t2",
			Needs: []Right{mainT1(core.ActionSelect)},
			Op:    core.InspectOpSelect,
			Why:   "an unqualified name matching a CTE is the CTE, so main.t2 is never read",
		},
		{
			Name:  "a star over a derived table",
			SQL:   "SELECT * FROM (SELECT c1 FROM t1) s",
			Needs: []Right{mainT1(core.ActionSelect)},
			Op:    core.InspectOpSelect,
			Why:   "s is an alias, and the star reaches only what it returns",
		},
		{
			Name:  "a derived table nested in another",
			SQL:   "SELECT * FROM (SELECT c1 FROM (SELECT c1 FROM t1) y) x",
			Needs: []Right{mainT1(core.ActionSelect)},
			Op:    core.InspectOpSelect,
			Why:   "y is in scope only inside x, so carrying it outward leaves a table nobody can hold a right on",
		},
		{
			Name:  "a nested derived table beside a table",
			SQL:   "SELECT * FROM (SELECT c1 FROM (SELECT c1 FROM t1) y, t2) x",
			Needs: []Right{mainT1(core.ActionSelect), mainT2(core.ActionSelect)},
			Op:    core.InspectOpSelect,
			Why:   "y is in scope only inside x, and t2 beside it is a table",
		},
		{
			Name:  "a nested derived table joined to a table",
			SQL:   "SELECT * FROM (SELECT c1 FROM (SELECT c1 FROM t1) y JOIN t2 ON 1=1) x",
			Needs: []Right{mainT1(core.ActionSelect), mainT2(core.ActionSelect)},
			Op:    core.InspectOpSelect,
			Why:   "y is in scope only inside x, and t2 joined to it is a table",
		},
		{
			Name:  "a recursive CTE reading itself",
			SQL:   "WITH RECURSIVE x AS (SELECT c1 FROM t1 UNION ALL SELECT c1 FROM x) SELECT * FROM x",
			Needs: []Right{mainT1(core.ActionSelect)},
			Op:    core.InspectOpSelect,
			Why:   "the body sees its own name, so x is the CTE and t1 is all it reads",
		},
		{
			Name:  "a recursive CTE with a column list reading itself",
			SQL:   "WITH RECURSIVE x(c1) AS (SELECT c1 FROM t1 UNION ALL SELECT c1 FROM x WHERE c1 < 5) SELECT * FROM x",
			Needs: []Right{mainT1(core.ActionSelect)},
			Op:    core.InspectOpSelect,
			Why:   "the body sees its own name, so x is the CTE and t1 is all it reads",
		},
		{
			Name:  "a CTE built from an earlier one",
			SQL:   "WITH a AS (SELECT c1 FROM t1), b AS (SELECT c1 FROM a) SELECT * FROM b",
			Needs: []Right{mainT1(core.ActionSelect)},
			Op:    core.InspectOpSelect,
			Why:   "a body sees the CTEs declared before it, so a is not a table",
		},
		{
			Name:  "a CTE reading an earlier one from a subquery",
			SQL:   "WITH a AS (SELECT c1 FROM t1), b AS (SELECT c1 FROM a WHERE c1 IN (SELECT c1 FROM a)) SELECT * FROM b",
			Needs: []Right{mainT1(core.ActionSelect)},
			Op:    core.InspectOpSelect,
			Why:   "a subquery inside a body sees what the body sees",
		},
		{
			Name:  "a CTE uniting two earlier ones",
			SQL:   "WITH a AS (SELECT c1 FROM t1), b AS (SELECT c1 FROM t2), c AS (SELECT c1 FROM a UNION SELECT c1 FROM b) SELECT * FROM c",
			Needs: []Right{mainT1(core.ActionSelect), mainT2(core.ActionSelect)},
			Op:    core.InspectOpSelect,
			Why:   "neither branch names a table, and the tables behind them are still read",
		},
		{
			Name:  "a CTE body naming a table a later CTE is named after",
			SQL:   "WITH a AS (SELECT c1 FROM t2), t2 AS (SELECT c1 FROM t1) SELECT * FROM a",
			Needs: []Right{mainT1(core.ActionSelect), mainT2(core.ActionSelect)},
			Op:    core.InspectOpSelect,
			Why:   "a plain WITH exposes only the CTEs declared before a body, so t2 in a is the table",
		},
		{
			On:    []string{"postgresql", "sqlite"},
			Name:  "a CTE an UPDATE ... FROM reads",
			SQL:   "WITH x AS (SELECT c1 FROM t1) UPDATE t2 SET c1 = x.c1 FROM x",
			Needs: []Right{mainT2(core.ActionUpdate), mainT1(core.ActionSelect)},
			Op:    core.InspectOpUpdate,
			Why:   "x is not a table, and what it reads is t1",
		},
		{
			On:    []string{"postgresql"},
			Name:  "a CTE a DELETE ... USING reads",
			SQL:   "WITH x AS (SELECT c1 FROM t1) DELETE FROM t2 USING x WHERE t2.c1 = x.c1",
			Needs: []Right{mainT2(core.ActionDelete), mainT2(core.ActionSelect), mainT1(core.ActionSelect)},
			Op:    core.InspectOpDelete,
			Why:   "x is not a table, what it reads is t1, and the match reads c1 of t2",
		},
		{
			On:    []string{"postgresql", "sqlite"},
			Name:  "a derived table an UPDATE ... FROM reads",
			SQL:   "UPDATE t2 SET c1 = s.c1 FROM (SELECT c1 FROM t1) s",
			Needs: []Right{mainT2(core.ActionUpdate), mainT1(core.ActionSelect)},
			Op:    core.InspectOpUpdate,
			Why:   "s is not a table, and what it reads is t1",
		},
		{
			On:    []string{"postgresql", "sqlite"},
			Name:  "an aliased table an UPDATE ... FROM reads",
			SQL:   "UPDATE t2 SET c1 = a.c1 FROM t1 a WHERE t2.c1 = a.c1",
			Needs: []Right{mainT2(core.ActionUpdate), mainT2(core.ActionSelect), mainT1(core.ActionSelect)},
			Op:    core.InspectOpUpdate,
			Why:   "a is t1, and the match reads c1 of t2",
		},

		// --- a statement inside a statement. The inner one is checked on its
		// own table, so a grant on the outer one's does not reach it.
		{
			On:     []string{"postgresql"},
			Name:   "a CTE that deletes",
			SQL:    "WITH x AS (DELETE FROM t1 RETURNING c1) SELECT c1 FROM x",
			Needs:  []Right{mainT1(core.ActionDelete), mainT1(core.ActionSelect)},
			Denied: []Right{mainT2(core.ActionSelect), mainT2(core.ActionDelete)},
			Op:     core.InspectOpDelete,
			Why:    "the CTE deletes from t1 and hands its rows back, and rights on another table do not reach it",
		},
		{
			On:    []string{"postgresql"},
			Name:  "a CTE that updates",
			SQL:   "WITH x AS (UPDATE t1 SET c2 = 'x' RETURNING c1) SELECT c1 FROM x",
			Needs: []Right{mainT1(core.ActionUpdate), mainT1(core.ActionSelect)},
			Op:    core.InspectOpUpdate,
			Why:   "the CTE updates t1 and hands its rows back",
		},
		{
			On:    []string{"postgresql"},
			Name:  "a CTE that inserts",
			SQL:   "WITH x AS (INSERT INTO t1 (c1) VALUES (1) RETURNING c1) SELECT c1 FROM x",
			Needs: []Right{mainT1(core.ActionInsert), mainT1(core.ActionSelect)},
			Op:    core.InspectOpInsert,
			Why:   "the CTE inserts into t1 and hands its rows back",
		},
		{
			On:   []string{"postgresql"},
			Name: "a CTE that deletes beside a delete of another table",
			SQL:  "WITH x AS (DELETE FROM t1 RETURNING c1) DELETE FROM t2 WHERE c1 = 1",
			Needs: []Right{
				mainT1(core.ActionDelete),
				mainT1(core.ActionSelect),
				mainT2(core.ActionDelete),
				mainT2(core.ActionSelect),
			},
			Denied: []Right{mainT2(core.ActionSelect), mainT2(core.ActionDelete)},
			Op:     core.InspectOpDelete,
			Why:    "the outer delete is on t2 and the CTE's is on t1, and a grant on the one is not a grant on the other",
		},
		{
			On:    []string{"postgresql", "sqlite"},
			Name:  "UPDATE ... FROM reads the table it fills from",
			SQL:   "UPDATE t2 SET c1 = t1.c1 FROM t1",
			Needs: []Right{mainT2(core.ActionUpdate), mainT1(core.ActionSelect)},
			Op:    core.InspectOpUpdate,
			Why:   "t1 is read to fill t2, and update does not cover reading it",
		},
		{
			On:     []string{"postgresql"},
			Name:   "DELETE ... USING reads the table it matches against",
			SQL:    "DELETE FROM t2 USING t1 WHERE t2.c1 = t1.c1",
			Needs:  []Right{mainT2(core.ActionDelete), mainT2(core.ActionSelect), mainT1(core.ActionSelect)},
			Denied: []Right{mainT2(core.ActionSelect), mainT2(core.ActionDelete)},
			Op:     core.InspectOpDelete,
			Why:    "USING reads t1 to choose the rows of t2, and rights on t2 do not reach it",
		},
		{
			On:    []string{"postgresql"},
			Name:  "copying a query out to a file",
			SQL:   "COPY (SELECT c1 FROM t1) TO '/tmp/x.csv'",
			Needs: []Right{Manage, mainT1(core.ActionSelect)},
			Why:   "writing the server's filesystem takes manage, reading t1 takes select",
		},
		{
			On:    []string{"postgresql"},
			Name:  "creating a materialized view reads what it selects",
			SQL:   "CREATE MATERIALIZED VIEW mv AS SELECT c1 FROM t1",
			Needs: []Right{Manage, mainT1(core.ActionSelect)},
			Why:   "a materialized view holds the rows it read",
		},
		{
			On:    []string{"postgresql"},
			Name:  "creating a table from a parenthesized query",
			SQL:   "CREATE TABLE t9 AS (SELECT c1 FROM t1)",
			Needs: []Right{Manage, mainT1(core.ActionSelect)},
			Why:   "a parenthesized source is the same read as an unparenthesized one",
		},
		{
			On:    []string{"postgresql"},
			Name:  "creating a table from TABLE",
			SQL:   "CREATE TABLE t9 AS TABLE t1",
			Needs: []Right{Manage, mainT1(core.ActionSelect)},
			Why:   "TABLE t1 is SELECT * FROM t1",
		},
		{
			On:     []string{"postgresql"},
			Name:   "creating a table from a star",
			SQL:    "CREATE TABLE t9 AS SELECT * FROM t1",
			Needs:  []Right{Manage, mainT1(core.ActionSelect)},
			Denied: rowRights,
			Why:    "the four row rights read t1 but cannot make the table",
		},
		{
			On:     []string{"postgresql"},
			Name:   "creating a view over a star",
			SQL:    "CREATE VIEW v AS SELECT * FROM t1",
			Needs:  []Right{Manage, mainT1(core.ActionSelect)},
			Denied: rowRights,
			Why:    "the four row rights read t1 but cannot make the view",
		},

		// --- a statement nobody classified, carrying a read. The floor covers
		// what the statement does; the read nested in it still takes the select
		// its table needs, since manage does not stand in for a row right.
		{
			On:     []string{"mysql"},
			Name:   "a session variable set from a query",
			SQL:    "SET @v = (SELECT c3 FROM t2)",
			Needs:  []Right{Manage, mainT2(core.ActionSelect).Only("c3")},
			Denied: rowRights,
			Why:    "c3 lands in a variable the next statement reads back without naming t2",
		},
		{
			On:     []string{"postgresql", "mysql"},
			Name:   "a procedure argument holding a query",
			SQL:    "CALL p((SELECT c1 FROM t1 WHERE c1 IN (SELECT c3 FROM t2)))",
			Needs:  []Right{Manage, mainT1(core.ActionSelect).Only("c1"), mainT2(core.ActionSelect).Only("c3")},
			Denied: rowRights,
			Why:    "the procedure is handed rows of t1 chosen by reading the c3 of t2",
		},
		{
			On:     []string{"sqlite"},
			Name:   "a trigger body reading a table",
			SQL:    "CREATE TRIGGER tr AFTER INSERT ON t1 BEGIN INSERT INTO t2 (c3) SELECT c1 FROM t1; END",
			Needs:  []Right{Manage, mainT1(core.ActionSelect).Only("c1")},
			Denied: rowRights,
			Why:    "making the trigger is administration, and the c1 it copies on every insert is a read",
		},

		// --- statements the four row rights do not reach. Each asks for manage
		// alone, and denying the row rights on every table says no mix of them
		// stands in for it.
		{
			On:     []string{"postgresql"},
			Name:   "an anonymous code block",
			SQL:    "DO $$ BEGIN DELETE FROM t1; END $$",
			Needs:  []Right{Manage},
			Denied: rowRights,
			Why:    "what the block does is not in the statement anyone can read",
		},
		{
			// The grammar's merge_delete_clause only follows an insert or an
			// update clause, so this one is a fragment error recovery invents.
			On:     []string{"postgresql"},
			Name:   "a merge whose only action is a delete",
			SQL:    "MERGE INTO t1 USING t2 ON t1.c1 = t2.c1 WHEN MATCHED THEN DELETE",
			Needs:  []Right{Manage, mainT2(core.ActionSelect).Only("c1")},
			Denied: rowRights,
			Why:    "the parser reads no action here, and an action it did not read is no right to claim",
		},
		{
			// DO NOTHING is not in merge_insert_clause either, and reading the
			// fragment as an insert would take a right the statement does not
			// need.
			On:     []string{"postgresql"},
			Name:   "a merge that does nothing to the unmatched row",
			SQL:    "MERGE INTO t1 USING t2 ON t1.c1 = t2.c1 WHEN NOT MATCHED THEN DO NOTHING",
			Needs:  []Right{Manage, mainT2(core.ActionSelect).Only("c1")},
			Denied: rowRights,
			Why:    "the parser reads no action here, and an action it did not read is no right to claim",
		},
		{
			Name:   "revoking every right is administration",
			SQL:    "REVOKE ALL ON t1 FROM bob",
			Needs:  []Right{Manage},
			Denied: rowRights,
			Why:    "it takes rights away from somebody else, and SQLite, which has no REVOKE, floors it",
		},
		{
			On:     []string{"postgresql"},
			Name:   "creating a role",
			SQL:    "CREATE ROLE evil SUPERUSER",
			Needs:  []Right{Manage},
			Denied: rowRights,
			Why:    "it makes somebody who holds every right",
		},
		{
			On:     []string{"postgresql", "sqlite"},
			Name:   "renaming a table",
			SQL:    "ALTER TABLE t1 RENAME TO t9",
			Needs:  []Right{Manage},
			Denied: rowRights,
			Why:    "it changes the schema, and every grant naming t1 stops reaching it",
		},
		{
			On:     []string{"mysql"},
			Name:   "RENAME TABLE",
			SQL:    "RENAME TABLE t1 TO t9",
			Needs:  []Right{Manage},
			Denied: rowRights,
			Why:    "it changes the schema, and every grant naming t1 stops reaching it",
		},
		{
			On:     []string{"postgresql"},
			Name:   "refreshing a materialized view",
			SQL:    "REFRESH MATERIALIZED VIEW mv",
			Needs:  []Right{Manage},
			Denied: rowRights,
			Why:    "it reruns a query the statement does not carry",
		},
		{
			On:     []string{"postgresql"},
			Name:   "locking a table in PostgreSQL",
			SQL:    "LOCK TABLE t1",
			Needs:  []Right{Manage},
			Denied: rowRights,
			Why:    "holding a lock is a thing done to the server, not to rows",
		},
		{
			On:     []string{"postgresql", "mysql"},
			Name:   "truncating without the TABLE keyword",
			SQL:    "TRUNCATE t1",
			Needs:  []Right{Manage},
			Denied: rowRights,
			Op:     core.InspectOpTruncate,
			Why:    "it empties the table outside the transaction a delete runs in",
		},
		{
			On:     []string{"postgresql"},
			Name:   "text that is not SQL",
			SQL:    "!!! not sql at all !!!",
			Needs:  []Right{Manage},
			Denied: rowRights,
			Why:    "a statement nobody read is floored rather than read as nothing to check",
		},

		// --- reaching the host: its filesystem, its shell, another server. The
		// database gates most of these on a superuser or the FILE privilege,
		// which is a second gate and not this one.
		{
			On:     []string{"postgresql"},
			Name:   "copying a table to a program",
			SQL:    "COPY t1 TO PROGRAM 'curl evil'",
			Needs:  []Right{Manage},
			Denied: rowRights,
			Why:    "it runs a shell command on the server",
		},
		{
			On:     []string{"postgresql"},
			Name:   "creating a tablespace",
			SQL:    "CREATE TABLESPACE ts LOCATION '/tmp/ts'",
			Needs:  []Right{Manage},
			Denied: rowRights,
			Why:    "it writes to a directory of the server's",
		},
		{
			On:     []string{"postgresql"},
			Name:   "ALTER SYSTEM",
			SQL:    "ALTER SYSTEM SET log_directory = '/tmp'",
			Needs:  []Right{Manage},
			Denied: rowRights,
			Why:    "it rewrites the server's configuration",
		},
		{
			On:     []string{"mysql"},
			Name:   "loading an XML file into a table",
			SQL:    "LOAD XML INFILE '/tmp/x' INTO TABLE t1",
			Needs:  []Right{Manage},
			Denied: rowRights,
			Why:    "it reads a file the server can see and the caller may not",
		},
		{
			On:     []string{"mysql"},
			Name:   "installing a plugin",
			SQL:    "INSTALL PLUGIN x SONAME 'evil.so'",
			Needs:  []Right{Manage},
			Denied: rowRights,
			Why:    "it loads a library into the server",
		},
		{
			On:     []string{"sqlite"},
			Name:   "vacuuming into a file",
			SQL:    "VACUUM INTO '/tmp/x.db'",
			Needs:  []Right{Manage},
			Denied: rowRights,
			Why:    "it writes a copy of the whole database somewhere the rules do not reach",
		},
		{
			On:     []string{"postgresql"},
			Name:   "reading a server file",
			SQL:    "SELECT pg_read_file('/etc/passwd')",
			Needs:  []Right{Manage},
			Denied: rowRights,
			Why:    "it looks like a read and returns a file of the host's",
		},
		{
			On:     []string{"postgresql"},
			Name:   "listing a server directory",
			SQL:    "SELECT pg_ls_dir('/etc')",
			Needs:  []Right{Manage},
			Denied: rowRights,
			Why:    "it looks like a read and returns the host's filesystem",
		},
		{
			On:     []string{"postgresql"},
			Name:   "exporting a large object",
			SQL:    "SELECT lo_export(1, '/tmp/x')",
			Needs:  []Right{Manage},
			Denied: rowRights,
			Why:    "it writes a file on the host",
		},
		{
			On:     []string{"postgresql"},
			Name:   "connecting to another server",
			SQL:    "SELECT dblink_connect('host=evil')",
			Needs:  []Right{Manage},
			Denied: rowRights,
			Why:    "it opens a connection the rules say nothing about",
		},
		{
			On:     []string{"postgresql"},
			Name:   "reading a server file from a scalar subquery",
			SQL:    "SELECT (SELECT pg_read_file('/etc/passwd'))",
			Needs:  []Right{Manage},
			Denied: rowRights,
			Why:    "nesting the call does not make it a read of rows",
		},
		{
			On:     []string{"mysql"},
			Name:   "LOAD_FILE",
			SQL:    "SELECT LOAD_FILE('/etc/passwd')",
			Needs:  []Right{Manage},
			Denied: rowRights,
			Why:    "it looks like a read and returns a file of the host's",
		},
		{
			On:     []string{"sqlite"},
			Name:   "writefile",
			SQL:    "SELECT writefile('/tmp/x', 'data')",
			Needs:  []Right{Manage},
			Denied: rowRights,
			Why:    "it looks like a read and writes a file on the host",
		},

		{
			On:     []string{"postgresql"},
			Name:   "a host routine in a predicate",
			SQL:    "SELECT * FROM t1 WHERE c2 = pg_read_file('/etc/passwd')",
			Needs:  []Right{Manage, mainT1(core.ActionSelect)},
			Denied: rowRights,
			Why:    "the call reaches the host and the query reads t1, and neither right covers the other",
		},
		{
			On:     []string{"postgresql"},
			Name:   "a host routine an update stores",
			SQL:    "UPDATE t1 SET c2 = pg_read_file('/etc/passwd')",
			Needs:  []Right{Manage, mainT1(core.ActionUpdate)},
			Denied: rowRights,
			Why:    "the call reaches the host and the statement writes t1, and neither right covers the other",
		},
		{
			On:     []string{"mysql"},
			Name:   "a host routine an insert stores",
			SQL:    "INSERT INTO t1 (c2) VALUES (LOAD_FILE('/etc/passwd'))",
			Needs:  []Right{Manage, mainT1(core.ActionInsert)},
			Denied: rowRights,
			Why:    "the call reaches the host and the statement writes t1, and neither right covers the other",
		},
		{
			On:     []string{"sqlite"},
			Name:   "a host routine in a SQLite predicate",
			SQL:    "SELECT * FROM t1 WHERE c2 = readfile('/etc/passwd')",
			Needs:  []Right{Manage, mainT1(core.ActionSelect)},
			Denied: rowRights,
			Why:    "the call reaches the host and the query reads t1, and neither right covers the other",
		},
		{
			On:     []string{"sqlite"},
			Name:   "a host routine a SQLite update stores",
			SQL:    "UPDATE t1 SET c2 = writefile('/tmp/x','y')",
			Needs:  []Right{Manage, mainT1(core.ActionUpdate)},
			Denied: rowRights,
			Why:    "the call reaches the host and the statement writes t1, and neither right covers the other",
		},
		{
			On:     []string{"sqlite"},
			Name:   "a host routine in one branch of a union",
			SQL:    "SELECT c1 FROM t1 UNION SELECT readfile('/etc/passwd')",
			Needs:  []Right{Manage, mainT1(core.ActionSelect)},
			Denied: rowRights,
			Why:    "the branches are one statement, so the call classifies all of it, and t1 is still read",
		},

		// --- a statement the parser stumbled over. Where what error recovery
		// salvaged names no table, a per-table check has nothing to ask about.
		{
			On:     []string{"postgresql", "mysql", "sqlite"},
			Name:   "a select cut off after FROM",
			SQL:    "SELECT c1 FROM",
			Needs:  []Right{Manage},
			Denied: rowRights,
			Why:    "the fragment names no table, so only the floor refuses it",
		},
		{
			On:     []string{"postgresql"},
			Name:   "a select with no list before FROM",
			SQL:    "SELECT FROM",
			Needs:  []Right{Manage},
			Denied: rowRights,
			Why:    "the fragment names no table, so only the floor refuses it",
		},
		{
			On:     []string{"mysql", "sqlite"},
			Name:   "a bare SELECT",
			SQL:    "SELECT",
			Needs:  []Right{Manage},
			Denied: rowRights,
			Why:    "the fragment names no table, so only the floor refuses it",
		},

		// --- a name spelled like a host routine is not a call, so it stays
		// ordinary work.
		{
			On:    []string{"postgresql"},
			Name:  "an alias spelled like pg_read_file",
			SQL:   "SELECT c1 AS pg_read_file FROM t1",
			Needs: []Right{mainT1(core.ActionSelect)},
			Op:    core.InspectOpSelect,
			Why:   "the name is not followed by a call",
		},
		{
			On:    []string{"postgresql"},
			Name:  "ordering by a name spelled like pg_read_file",
			SQL:   "SELECT c1 FROM t1 ORDER BY pg_read_file",
			Needs: []Right{mainT1(core.ActionSelect)},
			Op:    core.InspectOpSelect,
			Why:   "the name is not followed by a call",
		},
		{
			On:    []string{"mysql"},
			Name:  "an alias spelled like LOAD_FILE",
			SQL:   "SELECT c1 AS load_file FROM t1",
			Needs: []Right{mainT1(core.ActionSelect)},
			Op:    core.InspectOpSelect,
			Why:   "the name is not followed by a call",
		},
		{
			On:    []string{"mysql"},
			Name:  "a string spelled like a LOAD_FILE call",
			SQL:   "SELECT c1 FROM t1 WHERE c2 = 'load_file('",
			Needs: []Right{mainT1(core.ActionSelect)},
			Op:    core.InspectOpSelect,
			Why:   "text inside a string literal is not a call",
		},
		{
			On:    []string{"mysql"},
			Name:  "a column spelled like DUMPFILE",
			SQL:   "SELECT dumpfile FROM t1",
			Needs: []Right{mainT1(core.ActionSelect)},
			Op:    core.InspectOpSelect,
			Why:   "a column name is not an INTO DUMPFILE clause",
		},
		{
			On:    []string{"mysql"},
			Name:  "ordering by a name spelled like DUMPFILE",
			SQL:   "SELECT c1 FROM t1 ORDER BY dumpfile",
			Needs: []Right{mainT1(core.ActionSelect)},
			Op:    core.InspectOpSelect,
			Why:   "a column name is not an INTO DUMPFILE clause",
		},
		{
			On:    []string{"sqlite"},
			Name:  "an alias spelled like readfile",
			SQL:   "SELECT c1 AS readfile FROM t1",
			Needs: []Right{mainT1(core.ActionSelect)},
			Op:    core.InspectOpSelect,
			Why:   "the name is not followed by a call",
		},
		{
			On:    []string{"sqlite"},
			Name:  "a string spelled like writefile",
			SQL:   "SELECT c1 FROM t1 WHERE c2 = 'writefile'",
			Needs: []Right{mainT1(core.ActionSelect)},
			Op:    core.InspectOpSelect,
			Why:   "text inside a string literal is not a call",
		},
		{
			On:    []string{"postgresql"},
			Name:  "inserting into a table named pg_read_file",
			SQL:   "INSERT INTO pg_read_file (c1) VALUES (1)",
			Needs: []Right{{Action: core.ActionInsert, Schema: "main", Table: "pg_read_file"}},
			Op:    core.InspectOpInsert,
			Why:   "the parenthesis after a table name is a column list, not a call",
		},
		{
			On:    []string{"postgresql"},
			Name:  "updating a table named pg_read_file",
			SQL:   "UPDATE pg_read_file SET c1 = 1",
			Needs: []Right{{Action: core.ActionUpdate, Schema: "main", Table: "pg_read_file"}},
			Op:    core.InspectOpUpdate,
			Why:   "a table may be named after a routine and still be a table",
		},
		{
			On:    []string{"postgresql"},
			Name:  "a derived table aliased pg_read_file with a column list",
			SQL:   "SELECT * FROM (SELECT c1 FROM t1) AS pg_read_file (x)",
			Needs: []Right{mainT1(core.ActionSelect)},
			Op:    core.InspectOpSelect,
			Why:   "the parenthesis after an alias is a column list, not a call",
		},
		{
			On:    []string{"mysql"},
			Name:  "inserting into a table named load_file",
			SQL:   "INSERT INTO load_file (c1) VALUES (1)",
			Needs: []Right{{Action: core.ActionInsert, Schema: "main", Table: "load_file"}},
			Op:    core.InspectOpInsert,
			Why:   "the parenthesis after a table name is a column list, not a call",
		},
		{
			On:    []string{"sqlite"},
			Name:  "inserting into a table named readfile",
			SQL:   "INSERT INTO readfile (c1) VALUES (1)",
			Needs: []Right{{Action: core.ActionInsert, Schema: "main", Table: "readfile"}},
			Op:    core.InspectOpInsert,
			Why:   "the parenthesis after a table name is a column list, not a call",
		},

		// --- SELECT ... INTO. A spelling that builds something while looking
		// like a read takes manage for what it builds and select for what it
		// reads.
		{
			On:    []string{"postgresql"},
			Name:  "SELECT INTO a new table",
			SQL:   "SELECT c1 INTO t9 FROM t1",
			Needs: []Right{Manage, mainT1(core.ActionSelect)},
			Op:    core.InspectOpSelect,
			Why:   "it creates t9 and fills it from t1",
		},
		{
			On:    []string{"postgresql"},
			Name:  "SELECT INTO TEMP",
			SQL:   "SELECT c1 INTO TEMP t9 FROM t1",
			Needs: []Right{Manage, mainT1(core.ActionSelect)},
			Op:    core.InspectOpSelect,
			Why:   "a temporary table is still a table it creates",
		},
		{
			On:    []string{"postgresql"},
			Name:  "SELECT INTO TEMPORARY",
			SQL:   "SELECT c1 INTO TEMPORARY t9 FROM t1",
			Needs: []Right{Manage, mainT1(core.ActionSelect)},
			Op:    core.InspectOpSelect,
			Why:   "a temporary table is still a table it creates",
		},
		{
			On:    []string{"mysql"},
			Name:  "INTO OUTFILE before FROM",
			SQL:   "SELECT c1 INTO OUTFILE '/tmp/x' FROM t1",
			Needs: []Right{Manage, mainT1(core.ActionSelect)},
			Op:    core.InspectOpSelect,
			Why:   "it writes rows to a file on the host",
		},
		{
			On:    []string{"mysql"},
			Name:  "INTO DUMPFILE before FROM",
			SQL:   "SELECT c1 INTO DUMPFILE '/tmp/x' FROM t1",
			Needs: []Right{Manage, mainT1(core.ActionSelect)},
			Op:    core.InspectOpSelect,
			Why:   "it writes a row to a file on the host",
		},
		{
			// The trailing INTO is the documented spelling and reaches a
			// different grammar node than the one before FROM.
			On:    []string{"mysql"},
			Name:  "INTO OUTFILE after the query",
			SQL:   "SELECT c1 FROM t1 INTO OUTFILE '/tmp/x'",
			Needs: []Right{Manage, mainT1(core.ActionSelect)},
			Op:    core.InspectOpSelect,
			Why:   "it writes rows to a file on the host",
		},
		{
			On:    []string{"mysql"},
			Name:  "INTO DUMPFILE after the query",
			SQL:   "SELECT c1 FROM t1 INTO DUMPFILE '/tmp/x'",
			Needs: []Right{Manage, mainT1(core.ActionSelect)},
			Op:    core.InspectOpSelect,
			Why:   "it writes a row to a file on the host",
		},
		{
			On:    []string{"mysql"},
			Name:  "INTO OUTFILE after a parenthesized query",
			SQL:   "(SELECT c1 FROM t1) INTO OUTFILE '/tmp/x'",
			Needs: []Right{Manage, mainT1(core.ActionSelect)},
			Op:    core.InspectOpSelect,
			Why:   "it writes rows to a file on the host",
		},
		{
			On:    []string{"mysql"},
			Name:  "INTO OUTFILE in one parenthesized branch of a union",
			SQL:   "(SELECT c1 FROM t1) UNION (SELECT c1 INTO OUTFILE '/tmp/x' FROM t1)",
			Needs: []Right{Manage, mainT1(core.ActionSelect)},
			Op:    core.InspectOpSelect,
			Why:   "one branch carrying it is enough to write the file",
		},
		{
			// MySQL documents INTO after a locking clause since 8.0.20. This
			// grammar raises a syntax error there and recovery drops the tail.
			On:    []string{"mysql"},
			Name:  "INTO OUTFILE after FOR UPDATE",
			SQL:   "SELECT c1 FROM t1 FOR UPDATE INTO OUTFILE '/tmp/x'",
			Needs: []Right{Manage, mainT1(core.ActionSelect)},
			Op:    core.InspectOpSelect,
			Why:   "it writes rows to a file on the host",
		},
		{
			On:    []string{"mysql"},
			Name:  "INTO OUTFILE after LOCK IN SHARE MODE",
			SQL:   "SELECT c1 FROM t1 LOCK IN SHARE MODE INTO OUTFILE '/tmp/x'",
			Needs: []Right{Manage, mainT1(core.ActionSelect)},
			Op:    core.InspectOpSelect,
			Why:   "it writes rows to a file on the host",
		},
		{
			On:    []string{"mysql"},
			Name:  "INTO DUMPFILE after FOR UPDATE",
			SQL:   "SELECT c1 FROM t1 FOR UPDATE INTO DUMPFILE '/tmp/x'",
			Needs: []Right{Manage, mainT1(core.ActionSelect)},
			Op:    core.InspectOpSelect,
			Why:   "it writes a row to a file on the host",
		},
		{
			On:    []string{"mysql"},
			Name:  "a locking read",
			SQL:   "SELECT c1 FROM t1 FOR UPDATE",
			Needs: []Right{mainT1(core.ActionSelect)},
			Op:    core.InspectOpSelect,
			Why:   "a locking clause on its own writes nothing, so it stays a plain read",
		},
		{
			On:    []string{"mysql"},
			Name:  "SELECT INTO a variable",
			SQL:   "SELECT c1 INTO @v FROM t1",
			Needs: []Right{mainT1(core.ActionSelect)},
			Op:    core.InspectOpSelect,
			Why:   "a session variable is not a file or a table, so it stays a plain read",
		},

		// --- SQLite's own spellings
		{
			On:    []string{"sqlite"},
			Name:  "a compound branch on a statement that reads nothing",
			SQL:   "DROP TABLE t1 UNION SELECT c1 FROM other.t3",
			Needs: []Right{Manage, otherT3(core.ActionSelect)},
			Why:   "no DROP reads a query, so what the branch names is read by a statement nobody can name",
		},
		{
			On:    []string{"sqlite"},
			Name:  "a compound branch that is not a query",
			SQL:   "SELECT c1 FROM t2 UNION DELETE FROM t1",
			Needs: []Right{Manage, mainT2(core.ActionSelect)},
			Why:   "a branch nobody can read leaves a statement nobody can name, and reporting what is left of it would report a write as a read",
		},
		{
			On:    []string{"sqlite"},
			Name:  "INSERT OR REPLACE deletes the row it conflicts with",
			SQL:   "INSERT OR REPLACE INTO t1 VALUES (1, 'a')",
			Needs: []Right{mainT1(core.ActionInsert), mainT1(core.ActionDelete)},
			Op:    core.InspectOpInsert,
			Why:   "the row that was there is gone, so insert alone destroys data",
		},
		{
			On:    []string{"sqlite"},
			Name:  "INSERT OR IGNORE only inserts",
			SQL:   "INSERT OR IGNORE INTO t1 VALUES (1, 'a')",
			Needs: []Right{mainT1(core.ActionInsert)},
			Op:    core.InspectOpInsert,
			Why:   "the conflicting row is left exactly as it was",
		},
		{
			// This grammar does not model every spelling SQLite accepts, and a
			// statement it stumbles over while still naming its tables is
			// checked against those tables rather than floored.
			On:    []string{"sqlite"},
			Name:  "a named window the grammar misses",
			SQL:   "SELECT c1 FROM t1 WINDOW w AS (PARTITION BY c1)",
			Needs: []Right{mainT1(core.ActionSelect)},
			Op:    core.InspectOpSelect,
			Why:   "refusing it would hold ordinary work",
		},
		{
			On:    []string{"sqlite"},
			Name:  "an aggregate FILTER the grammar misses",
			SQL:   "SELECT count(*) FILTER (WHERE c1 > 0) FROM t1",
			Needs: []Right{mainT1(core.ActionSelect)},
			Op:    core.InspectOpSelect,
			Why:   "refusing it would hold ordinary work",
		},
		{
			On:    []string{"sqlite"},
			Name:  "NULLS LAST the grammar misses",
			SQL:   "SELECT c1 FROM t1 ORDER BY c1 NULLS LAST",
			Needs: []Right{mainT1(core.ActionSelect)},
			Op:    core.InspectOpSelect,
			Why:   "refusing it would hold ordinary work",
		},
		{
			On:    []string{"sqlite"},
			Name:  "REGEXP the grammar misses",
			SQL:   "SELECT c1 FROM t1 WHERE c2 REGEXP 'a'",
			Needs: []Right{mainT1(core.ActionSelect)},
			Op:    core.InspectOpSelect,
			Why:   "refusing it would hold ordinary work",
		},
	}
}
