// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CancelAccessTokenPolling(): $CancellablePromise<void> {
    return $Call.ByID(3744132403);
}

export function GetAccessToken(deviceCode: string): $CancellablePromise<void> {
    return $Call.ByID(2002237112, deviceCode);
}

export function GetDeviceCode(): $CancellablePromise<$models.DeviceCodeResponse | null> {
    return $Call.ByID(2636258938).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.DeviceCodeResponse.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
