// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class DeviceCodeResponse {
    "device_code": string;
    "user_code": string;
    "verification_uri": string;
    "expires_in": number;
    "interval": number;

    /** Creates a new DeviceCodeResponse instance. */
    constructor($$source: Partial<DeviceCodeResponse> = {}) {
        if (!("device_code" in $$source)) {
            this["device_code"] = "";
        }
        if (!("user_code" in $$source)) {
            this["user_code"] = "";
        }
        if (!("verification_uri" in $$source)) {
            this["verification_uri"] = "";
        }
        if (!("expires_in" in $$source)) {
            this["expires_in"] = 0;
        }
        if (!("interval" in $$source)) {
            this["interval"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeviceCodeResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): DeviceCodeResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DeviceCodeResponse($$parsedSource as Partial<DeviceCodeResponse>);
    }
}
