// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * *
 * *	String
 */
export type JSONNullString = any;

/**
 * JSONPayload is the generated type for `JSON` columns (e.g. mutation_commit.payload).
 * It is an alias for any so the mutation flow can hold either the raw payload or a
 * decoded DTO in the same field. Pinned via a sqlc column override because newer sqlc
 * defaults `JSON` columns to json.RawMessage, which is not assignment-compatible.
 */
export type JSONPayload = any;
