// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Updater exposes update operations as Wails bindings.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * Apply downloads, verifies, installs, and relaunches the latest version.
 * Called from the frontend when the user accepts the update.
 */
export function Apply(): $CancellablePromise<void> {
    return $Call.ByID(2248233362);
}

/**
 * CheckVersion fetches /version and emits an "available" event if a newer
 * version exists. Does not download or install anything.
 */
export function CheckVersion(): $CancellablePromise<void> {
    return $Call.ByID(1582590550);
}

export function SetContext(): $CancellablePromise<void> {
    return $Call.ByID(2413332709);
}
