// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelQuery(arg1) {
  return window['go']['db_client']['DbClient']['CancelQuery'](arg1);
}

export function Explain(arg1) {
  return window['go']['db_client']['DbClient']['Explain'](arg1);
}

export function Export(arg1) {
  return window['go']['db_client']['DbClient']['Export'](arg1);
}

export function GenerateUpdateSQL(arg1) {
  return window['go']['db_client']['DbClient']['GenerateUpdateSQL'](arg1);
}

export function GetMeta(arg1, arg2) {
  return window['go']['db_client']['DbClient']['GetMeta'](arg1, arg2);
}

export function GetOrOpenConn(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['db_client']['DbClient']['GetOrOpenConn'](arg1, arg2, arg3, arg4, arg5);
}

export function GetResultPage(arg1) {
  return window['go']['db_client']['DbClient']['GetResultPage'](arg1);
}

export function InspectStatement(arg1, arg2) {
  return window['go']['db_client']['DbClient']['InspectStatement'](arg1, arg2);
}

export function LookupForeignKey(arg1) {
  return window['go']['db_client']['DbClient']['LookupForeignKey'](arg1);
}

export function Ping(arg1) {
  return window['go']['db_client']['DbClient']['Ping'](arg1);
}

export function Plan(arg1) {
  return window['go']['db_client']['DbClient']['Plan'](arg1);
}

export function Query(arg1) {
  return window['go']['db_client']['DbClient']['Query'](arg1);
}

export function QuerySchema(arg1) {
  return window['go']['db_client']['DbClient']['QuerySchema'](arg1);
}

export function SetContext(arg1) {
  return window['go']['db_client']['DbClient']['SetContext'](arg1);
}

export function StartQuery(arg1) {
  return window['go']['db_client']['DbClient']['StartQuery'](arg1);
}
