// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db_client} from '../models';
import {graph} from '../models';
import {core} from '../models';
import {sql} from '../models';
import {context} from '../models';

export function CancelQuery(arg1:db_client.CancelQueryParams):Promise<void>;

export function ChooseSSHKeyFile():Promise<string>;

export function Explain(arg1:db_client.ExplainParams):Promise<graph.ExplainResult>;

export function Export(arg1:db_client.ExportParams):Promise<void>;

export function GenerateSelectSQL(arg1:db_client.GenerateSelectSQLParams):Promise<db_client.GenerateSelectSQLResult>;

export function GenerateUpdateSQL(arg1:db_client.GenerateUpdateSQLParams):Promise<db_client.GenerateUpdateSQLResult>;

export function GetMeta(arg1:graph.DBInstanceNode,arg2:boolean):Promise<core.Metadata>;

export function GetOrOpenConn(arg1:string,arg2:string,arg3:string,arg4:string,arg5:graph.DBInstanceSSHConfig):Promise<sql.DB>;

export function GetResultPage(arg1:db_client.GetResultPageParams):Promise<graph.QueryResult>;

export function InspectStatement(arg1:string,arg2:graph.DBInstanceNode):Promise<Array<core.InspectStatement>>;

export function LookupForeignKey(arg1:db_client.LookupForeignKeyParams):Promise<graph.QueryResult>;

export function Ping(arg1:db_client.PingParams):Promise<string>;

export function Plan(arg1:db_client.PlanParams):Promise<graph.ExplainResult>;

export function Query(arg1:db_client.QueryParams):Promise<graph.QueryResult>;

export function QuerySchema(arg1:db_client.QuerySchemaParams):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function SetSSHKeyPassphrase(arg1:string,arg2:string):Promise<void>;

export function StartQuery(arg1:db_client.StartQueryParams):Promise<db_client.StartQueryResult>;
