// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Group is the Wails-bound service for managing IAM groups (identity), their
 * members, and the roles they grant. It mirrors internal/role.Role: each write
 * goes through a tracked query so the SQL interceptor enqueues a sync commit.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as generated$0 from "../db/generated/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AddUserToGroup(userID: string, groupID: string): $CancellablePromise<void> {
    return $Call.ByID(3674039894, userID, groupID);
}

export function AttachRoleToGroup(roleID: string, groupID: string): $CancellablePromise<void> {
    return $Call.ByID(540264881, roleID, groupID);
}

export function CreateGroup(name: string): $CancellablePromise<generated$0.Group> {
    return $Call.ByID(3165302349, name).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * DeleteGroup deletes a group by ID. The delete syncs to the backend, which
 * stops honoring the group's role grants; the membership and role-attachment
 * rows are not explicitly removed (SQLite FKs are not enforced locally, and
 * backend effective-role resolution ignores deleted groups).
 */
export function DeleteGroup(groupID: string): $CancellablePromise<void> {
    return $Call.ByID(2305546912, groupID);
}

export function DetachRoleFromGroup(groupToRoleID: string): $CancellablePromise<void> {
    return $Call.ByID(3201162092, groupToRoleID);
}

export function ListGroupMembers(groupID: string): $CancellablePromise<$models.GroupUserEntry[]> {
    return $Call.ByID(3114827928, groupID).then(($result: any) => {
        return $$createType2($result);
    });
}

export function ListGroupRoles(groupID: string): $CancellablePromise<$models.GroupRoleEntry[]> {
    return $Call.ByID(2475314022, groupID).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * ListGroups returns all groups for the current workspace, with member and role counts.
 */
export function ListGroups(): $CancellablePromise<generated$0.ListGroupsByWorkspaceRow[]> {
    return $Call.ByID(4040312458).then(($result: any) => {
        return $$createType6($result);
    });
}

export function RemoveUserFromGroup(userToGroupID: string): $CancellablePromise<void> {
    return $Call.ByID(3508339828, userToGroupID);
}

export function RenameGroup(id: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(1747808635, id, name);
}

// Private type creation functions
const $$createType0 = generated$0.Group.createFrom;
const $$createType1 = $models.GroupUserEntry.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $models.GroupRoleEntry.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = generated$0.ListGroupsByWorkspaceRow.createFrom;
const $$createType6 = $Create.Array($$createType5);
