// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class GroupRoleEntry {
    "id": string;
    "name": string | null;
    "group_to_role_id": string;

    /** Creates a new GroupRoleEntry instance. */
    constructor($$source: Partial<GroupRoleEntry> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = null;
        }
        if (!("group_to_role_id" in $$source)) {
            this["group_to_role_id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GroupRoleEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): GroupRoleEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GroupRoleEntry($$parsedSource as Partial<GroupRoleEntry>);
    }
}

export class GroupUserEntry {
    "id": string;
    "name": string | null;
    "user_to_group_id": string;

    /** Creates a new GroupUserEntry instance. */
    constructor($$source: Partial<GroupUserEntry> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = null;
        }
        if (!("user_to_group_id" in $$source)) {
            this["user_to_group_id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GroupUserEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): GroupUserEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GroupUserEntry($$parsedSource as Partial<GroupUserEntry>);
    }
}
