// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {terminal} from '../models';
import {context} from '../models';

export function Create(arg1:string,arg2:string):Promise<void>;

export function Destroy(arg1:string):Promise<void>;

export function DestroyAll():Promise<void>;

export function GetAvailableShells():Promise<Array<terminal.ShellOption>>;

export function Resize(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function Write(arg1:string,arg2:string):Promise<void>;
