// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1, arg2) {
  return window['go']['terminal']['Terminal']['Create'](arg1, arg2);
}

export function Destroy(arg1) {
  return window['go']['terminal']['Terminal']['Destroy'](arg1);
}

export function DestroyAll() {
  return window['go']['terminal']['Terminal']['DestroyAll']();
}

export function GetAvailableShells() {
  return window['go']['terminal']['Terminal']['GetAvailableShells']();
}

export function Resize(arg1, arg2, arg3) {
  return window['go']['terminal']['Terminal']['Resize'](arg1, arg2, arg3);
}

export function SetContext(arg1) {
  return window['go']['terminal']['Terminal']['SetContext'](arg1);
}

export function Write(arg1, arg2) {
  return window['go']['terminal']['Terminal']['Write'](arg1, arg2);
}
