// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {sqllang} from '../models';

export function Close():Promise<void>;

export function Complete(arg1:sqllang.PositionParams):Promise<sqllang.CompleteResult>;

export function Hover(arg1:sqllang.PositionParams):Promise<sqllang.HoverResult>;

export function Lint(arg1:sqllang.PositionParams):Promise<sqllang.LintResult>;

export function Resolve(arg1:sqllang.PositionParams):Promise<sqllang.ResolveResult>;
