// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['sqllang']['SqlLang']['Close']();
}

export function Complete(arg1) {
  return window['go']['sqllang']['SqlLang']['Complete'](arg1);
}

export function Hover(arg1) {
  return window['go']['sqllang']['SqlLang']['Hover'](arg1);
}

export function Lint(arg1) {
  return window['go']['sqllang']['SqlLang']['Lint'](arg1);
}

export function Resolve(arg1) {
  return window['go']['sqllang']['SqlLang']['Resolve'](arg1);
}
