// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ExecutionLimitsResponse is the workspace-level query safety policy returned to
 * the frontend after an update.
 */
export class ExecutionLimitsResponse {
    "statement_timeout_ms": number;
    "max_result_size_mb": number;

    /** Creates a new ExecutionLimitsResponse instance. */
    constructor($$source: Partial<ExecutionLimitsResponse> = {}) {
        if (!("statement_timeout_ms" in $$source)) {
            this["statement_timeout_ms"] = 0;
        }
        if (!("max_result_size_mb" in $$source)) {
            this["max_result_size_mb"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExecutionLimitsResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): ExecutionLimitsResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExecutionLimitsResponse($$parsedSource as Partial<ExecutionLimitsResponse>);
    }
}
