// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as tokenanalyzer$0 from "../../../github.com/selectDb/dialect/core/tokenanalyzer/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as graph$0 from "../graph/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CheckForLogin(): $CancellablePromise<void> {
    return $Call.ByID(1425142152);
}

export function CheckForLogout(): $CancellablePromise<void> {
    return $Call.ByID(2480583021);
}

/**
 * EnsureUserConfigDefaults makes sure the per-user .theme and .config files
 * exist on disk, seeding the built-in defaults when missing (existing files are
 * preserved). Called before opening the personal Settings editors so they can
 * always read the files, even if seeding at startup failed or a file was
 * deleted.
 */
export function EnsureUserConfigDefaults(): $CancellablePromise<void> {
    return $Call.ByID(1280326457);
}

/**
 * GetAppEnv returns the build-time application environment ("production",
 * "staging", "dev", ...). Set in main via -X main.appEnv and exported to the
 * process env at startup. The frontend uses it to gate prod-only UI.
 */
export function GetAppEnv(): $CancellablePromise<string> {
    return $Call.ByID(244427814);
}

/**
 * GetConfig loads and returns the merged personal config (defaults + per-user
 * .config keybindings/snippets).
 */
export function GetConfig(): $CancellablePromise<graph$0.ConfigResponse | null> {
    return $Call.ByID(1643872934).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetDefaultLintContent returns the default .lint file content.
 */
export function GetDefaultLintContent(): $CancellablePromise<string> {
    return $Call.ByID(1680405265);
}

/**
 * GetDefaultThemeContent returns the default theme file content.
 * Used when creating a new .theme file or showing users the template.
 */
export function GetDefaultThemeContent(): $CancellablePromise<string> {
    return $Call.ByID(359728619);
}

/**
 * GetDefaultUserConfigContent returns the default per-user .config content
 * (keybindings/snippets). Used by the personal config editor.
 */
export function GetDefaultUserConfigContent(): $CancellablePromise<string> {
    return $Call.ByID(3268810793);
}

/**
 * GetLint loads and returns the workspace .lint config entries.
 */
export function GetLint(): $CancellablePromise<tokenanalyzer$0.LintFile> {
    return $Call.ByID(4178419349).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetThemeVariables loads and returns the current workspace theme variables.
 * Called by the frontend on startup to initialize the theme.
 * When there is no workspace (e.g. login page), returns the default theme so the app is still styled.
 */
export function GetThemeVariables(): $CancellablePromise<graph$0.ThemeVariables | null> {
    return $Call.ByID(1975046762).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GetZoom returns the window's current page zoom factor.
 */
export function GetZoom(): $CancellablePromise<number> {
    return $Call.ByID(2072827331);
}

/**
 * LoadAllDatabaseSchemas runs QuerySchema for each workspace DB instance (same as after other graph rebuilds).
 */
export function LoadAllDatabaseSchemas(wsGraph: graph$0.WorkspaceNode | null): $CancellablePromise<void> {
    return $Call.ByID(463064022, wsGraph);
}

export function Logout(): $CancellablePromise<void> {
    return $Call.ByID(2566300002);
}

export function OpenURL(url: string): $CancellablePromise<void> {
    return $Call.ByID(672115093, url);
}

/**
 * ResetLint writes the default .lint content to the workspace file.
 */
export function ResetLint(): $CancellablePromise<void> {
    return $Call.ByID(1848134014);
}

/**
 * ResetTheme resets the workspace theme to default values by writing
 * the default theme content to the .theme file.
 */
export function ResetTheme(): $CancellablePromise<void> {
    return $Call.ByID(494125172);
}

/**
 * ResetUserConfig resets the per-user .config (keybindings/snippets) to defaults.
 */
export function ResetUserConfig(): $CancellablePromise<void> {
    return $Call.ByID(2230625766);
}

/**
 * RevealInExplorer opens the system file explorer and highlights the file at
 * the given selectdb:// URI.
 */
export function RevealInExplorer(uri: string): $CancellablePromise<void> {
    return $Call.ByID(1869494157, uri);
}

export function SetContext(): $CancellablePromise<void> {
    return $Call.ByID(1199758839);
}

/**
 * SetZoom applies a page zoom factor to the window and returns the factor that
 * was actually applied, which the frontend uses to keep its zoom level in step
 * with the webview (Windows cannot go below 100%).
 */
export function SetZoom(factor: number): $CancellablePromise<number> {
    return $Call.ByID(2984968295, factor);
}

/**
 * Stops any running DB availability watcher and starts a new one.
 */
export function StartDatabaseWatcher(): $CancellablePromise<void> {
    return $Call.ByID(2903622711);
}

/**
 * Stops any running watcher and starts a new one for workspaceID.
 */
export function StartFileWatcher(workspaceID: string): $CancellablePromise<void> {
    return $Call.ByID(2481068214, workspaceID);
}

/**
 * UpdateWorkspaceExecutionLimits persists the workspace execution limits (a
 * tracked write that syncs to the team) and returns the normalized values that
 * were stored. Emits workspaceGraphUpdated so the UI reflects the change.
 */
export function UpdateWorkspaceExecutionLimits(statementTimeoutMs: number, maxResultSizeMB: number): $CancellablePromise<$models.ExecutionLimitsResponse | null> {
    return $Call.ByID(720962844, statementTimeoutMs, maxResultSizeMB).then(($result: any) => {
        return $$createType7($result);
    });
}

export function WatchNetworkQuality(): $CancellablePromise<void> {
    return $Call.ByID(2213596812);
}

export function WindowClose(): $CancellablePromise<void> {
    return $Call.ByID(3550822116);
}

export function WindowMinimise(): $CancellablePromise<void> {
    return $Call.ByID(1531228797);
}

export function WindowToggleFullscreen(): $CancellablePromise<void> {
    return $Call.ByID(748747909);
}

// Private type creation functions
const $$createType0 = graph$0.ConfigResponse.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = tokenanalyzer$0.LintConfigEntry.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = graph$0.ThemeVariables.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $models.ExecutionLimitsResponse.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
