// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Create(sessionId: string, shell: string): $CancellablePromise<void> {
    return $Call.ByID(1831831142, sessionId, shell);
}

export function Destroy(sessionId: string): $CancellablePromise<void> {
    return $Call.ByID(1495358012, sessionId);
}

export function DestroyAll(): $CancellablePromise<void> {
    return $Call.ByID(85183335);
}

export function GetAvailableShells(): $CancellablePromise<$models.ShellOption[]> {
    return $Call.ByID(2546641350).then(($result: any) => {
        return $$createType1($result);
    });
}

export function Resize(sessionId: string, cols: number, rows: number): $CancellablePromise<void> {
    return $Call.ByID(97050774, sessionId, cols, rows);
}

export function Write(sessionId: string, data: string): $CancellablePromise<void> {
    return $Call.ByID(375507229, sessionId, data);
}

// Private type creation functions
const $$createType0 = $models.ShellOption.createFrom;
const $$createType1 = $Create.Array($$createType0);
