// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as generated$0 from "../db/generated/models.js";

export function GetCurrentUser(): $CancellablePromise<generated$0.User> {
    return $Call.ByID(3834794602).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetCurrentUserAvatar(userID: string): $CancellablePromise<string> {
    return $Call.ByID(4246964411, userID);
}

// Private type creation functions
const $$createType0 = generated$0.User.createFrom;
