// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CreateAPIKey(params: $models.CreateParams): $CancellablePromise<$models.CreateResult | null> {
    return $Call.ByID(2760662307, params).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ListAPIKeys(): $CancellablePromise<$models.APIKeyEntry[]> {
    return $Call.ByID(1413405060).then(($result: any) => {
        return $$createType3($result);
    });
}

export function RevokeAPIKey(id: string): $CancellablePromise<void> {
    return $Call.ByID(2195540641, id);
}

export function RotateAPIKey(id: string): $CancellablePromise<$models.CreateResult | null> {
    return $Call.ByID(3462398788, id).then(($result: any) => {
        return $$createType1($result);
    });
}

export function SetAPIKeyRoles(id: string, roleIDs: string[]): $CancellablePromise<void> {
    return $Call.ByID(1388130560, id, roleIDs);
}

// Private type creation functions
const $$createType0 = $models.CreateResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.APIKeyEntry.createFrom;
const $$createType3 = $Create.Array($$createType2);
