// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class APIKeyEntry {
    "id": string;
    "name": string | null;
    "prefix": string | null;
    "roles": APIKeyRole[];
    "created_by": string | null;
    "created_at": string | null;
    "last_used_at": string | null;
    "expires_at": string | null;

    /** Creates a new APIKeyEntry instance. */
    constructor($$source: Partial<APIKeyEntry> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = null;
        }
        if (!("prefix" in $$source)) {
            this["prefix"] = null;
        }
        if (!("roles" in $$source)) {
            this["roles"] = [];
        }
        if (!("created_by" in $$source)) {
            this["created_by"] = null;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = null;
        }
        if (!("last_used_at" in $$source)) {
            this["last_used_at"] = null;
        }
        if (!("expires_at" in $$source)) {
            this["expires_at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new APIKeyEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): APIKeyEntry {
        const $$createField3_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("roles" in $$parsedSource) {
            $$parsedSource["roles"] = $$createField3_0($$parsedSource["roles"]);
        }
        return new APIKeyEntry($$parsedSource as Partial<APIKeyEntry>);
    }
}

export class APIKeyRole {
    "id": string;
    "name": string;

    /** Creates a new APIKeyRole instance. */
    constructor($$source: Partial<APIKeyRole> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new APIKeyRole instance from a string or object.
     */
    static createFrom($$source: any = {}): APIKeyRole {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new APIKeyRole($$parsedSource as Partial<APIKeyRole>);
    }
}

export class CreateParams {
    "name": string;
    "role_ids": string[];

    /**
     * RFC3339, nil = never expires
     */
    "expires_at": string | null;

    /** Creates a new CreateParams instance. */
    constructor($$source: Partial<CreateParams> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("role_ids" in $$source)) {
            this["role_ids"] = [];
        }
        if (!("expires_at" in $$source)) {
            this["expires_at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateParams instance from a string or object.
     */
    static createFrom($$source: any = {}): CreateParams {
        const $$createField1_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("role_ids" in $$parsedSource) {
            $$parsedSource["role_ids"] = $$createField1_0($$parsedSource["role_ids"]);
        }
        return new CreateParams($$parsedSource as Partial<CreateParams>);
    }
}

/**
 * CreateResult carries the plaintext key. It is returned once and is never
 * retrievable again.
 */
export class CreateResult {
    "id": string;
    "prefix": string;
    "key": string;

    /** Creates a new CreateResult instance. */
    constructor($$source: Partial<CreateResult> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("prefix" in $$source)) {
            this["prefix"] = "";
        }
        if (!("key" in $$source)) {
            this["key"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateResult instance from a string or object.
     */
    static createFrom($$source: any = {}): CreateResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CreateResult($$parsedSource as Partial<CreateResult>);
    }
}

// Private type creation functions
const $$createType0 = APIKeyRole.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
