// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as Role from "./role.js";
export {
    Role
};

export {
    AddPermissionParams,
    PermissionEntry,
    RoleUserEntry
} from "./models.js";
