// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AddPermissionParams {
    "role_id": string;
    "db_instance_id": string | null;
    "schema_name": string | null;
    "table_name": string | null;
    "column_name": string | null;
    "action": string;
    "effect": string;

    /** Creates a new AddPermissionParams instance. */
    constructor($$source: Partial<AddPermissionParams> = {}) {
        if (!("role_id" in $$source)) {
            this["role_id"] = "";
        }
        if (!("db_instance_id" in $$source)) {
            this["db_instance_id"] = null;
        }
        if (!("schema_name" in $$source)) {
            this["schema_name"] = null;
        }
        if (!("table_name" in $$source)) {
            this["table_name"] = null;
        }
        if (!("column_name" in $$source)) {
            this["column_name"] = null;
        }
        if (!("action" in $$source)) {
            this["action"] = "";
        }
        if (!("effect" in $$source)) {
            this["effect"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AddPermissionParams instance from a string or object.
     */
    static createFrom($$source: any = {}): AddPermissionParams {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AddPermissionParams($$parsedSource as Partial<AddPermissionParams>);
    }
}

export class PermissionEntry {
    "id": string;
    "role_id": string;
    "workspace_id": string;
    "db_instance_id": string | null;
    "schema_name": string | null;
    "table_name": string | null;
    "column_name": string | null;
    "action": string;
    "effect": string;

    /** Creates a new PermissionEntry instance. */
    constructor($$source: Partial<PermissionEntry> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("role_id" in $$source)) {
            this["role_id"] = "";
        }
        if (!("workspace_id" in $$source)) {
            this["workspace_id"] = "";
        }
        if (!("db_instance_id" in $$source)) {
            this["db_instance_id"] = null;
        }
        if (!("schema_name" in $$source)) {
            this["schema_name"] = null;
        }
        if (!("table_name" in $$source)) {
            this["table_name"] = null;
        }
        if (!("column_name" in $$source)) {
            this["column_name"] = null;
        }
        if (!("action" in $$source)) {
            this["action"] = "";
        }
        if (!("effect" in $$source)) {
            this["effect"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PermissionEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): PermissionEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PermissionEntry($$parsedSource as Partial<PermissionEntry>);
    }
}

export class RoleUserEntry {
    "id": string;
    "name": string | null;
    "user_to_role_id": string;

    /** Creates a new RoleUserEntry instance. */
    constructor($$source: Partial<RoleUserEntry> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = null;
        }
        if (!("user_to_role_id" in $$source)) {
            this["user_to_role_id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RoleUserEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): RoleUserEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RoleUserEntry($$parsedSource as Partial<RoleUserEntry>);
    }
}
