// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as core$0 from "../../../github.com/selectDb/dialect/core/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as generated$0 from "../db/generated/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AddPermission(params: $models.AddPermissionParams): $CancellablePromise<$models.PermissionEntry> {
    return $Call.ByID(4169427318, params).then(($result: any) => {
        return $$createType0($result);
    });
}

export function AssignUserToRole(userID: string, roleID: string): $CancellablePromise<void> {
    return $Call.ByID(1433581965, userID, roleID);
}

export function CreateRole(name: string): $CancellablePromise<generated$0.Role> {
    return $Call.ByID(2559929438, name).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * DeleteRole deletes a role by ID. Cascades to user_role and permission.
 */
export function DeleteRole(roleID: string): $CancellablePromise<void> {
    return $Call.ByID(793581361, roleID);
}

export function DuplicateRole(id: string): $CancellablePromise<generated$0.Role> {
    return $Call.ByID(1619153943, id).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetMyPermissions(): $CancellablePromise<core$0.PermissionEntry[]> {
    return $Call.ByID(918545276).then(($result: any) => {
        return $$createType3($result);
    });
}

export function ListPermissions(roleID: string): $CancellablePromise<$models.PermissionEntry[]> {
    return $Call.ByID(847392422, roleID).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * ListRoles returns all roles for the current workspace.
 */
export function ListRoles(): $CancellablePromise<generated$0.ListRolesByWorkspaceRow[]> {
    return $Call.ByID(755124239).then(($result: any) => {
        return $$createType6($result);
    });
}

export function ListUsersInRole(roleID: string): $CancellablePromise<$models.RoleUserEntry[]> {
    return $Call.ByID(2038792949, roleID).then(($result: any) => {
        return $$createType8($result);
    });
}

export function RemovePermission(id: string): $CancellablePromise<void> {
    return $Call.ByID(3805386377, id);
}

export function RemoveUserFromRole(userToRoleID: string): $CancellablePromise<void> {
    return $Call.ByID(3475112989, userToRoleID);
}

export function RenameRole(id: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(2351553236, id, name);
}

// Private type creation functions
const $$createType0 = $models.PermissionEntry.createFrom;
const $$createType1 = generated$0.Role.createFrom;
const $$createType2 = core$0.PermissionEntry.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Array($$createType0);
const $$createType5 = generated$0.ListRolesByWorkspaceRow.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = $models.RoleUserEntry.createFrom;
const $$createType8 = $Create.Array($$createType7);
