// Package httpapi projects the apigen entity model into the generated REST route
// table (internal/api/gen/routes.go). Like the OpenAPI projection it derives
// everything from the schema IR; the emitted code is only thin rest.Entity
// descriptors (table + exposed fields + per-op required actions + the syncer
// Apply/ApplyDelete for synced entities) handed to the hand-written rest runtime,
// which owns all request handling. The field specs come from the same IR that
// produces the OpenAPI filterable-fields table, so the API and its docs advertise
// and accept exactly the same fields and operators.
package httpapi

import (
	"fmt"
	"go/format"
	"sort"
	"strings"

	"backend/internal/apigen/codegen"
	"backend/internal/apigen/schema"
	"backend/internal/apigen/syncer"
)

// EmitRoutes renders internal/api/gen/routes.go: a RegisterRoutes(mux, wrap) that
// builds a rest.Entity per @app.api entity and calls rest.Register.
func EmitRoutes(entities []schema.Entity) (codegen.GenFile, error) {
	var apis []schema.Entity
	for _, e := range entities {
		if len(e.API) > 0 {
			apis = append(apis, e)
		}
	}

	// Synced entities with write ops need their syncer gen package (Apply/ApplyDelete).
	writePkgs := map[string]bool{}
	needCore := false
	for _, e := range apis {
		if e.Sync && hasWriteOp(e) {
			writePkgs[e.Table] = true
		}
		for _, op := range e.API {
			if len(op.Requires) > 0 {
				needCore = true
			}
		}
	}

	var b strings.Builder
	b.WriteString("// Code generated by apigen. DO NOT EDIT.\n\n")
	b.WriteString("package gen\n\n")
	b.WriteString("import (\n")
	b.WriteString("\t\"net/http\"\n\n")
	b.WriteString("\t\"backend/internal/api/query\"\n")
	b.WriteString("\t\"backend/internal/api/rest\"\n")
	if needCore {
		b.WriteString("\n\tcore \"github.com/selectDb/dialect/core\"\n")
	}
	if len(writePkgs) > 0 {
		b.WriteString("\n")
		for _, t := range sortedKeys(writePkgs) {
			b.WriteString(fmt.Sprintf("\t%s %q\n", t, "backend/internal/syncer/gen/"+t))
		}
	}
	b.WriteString(")\n\n")

	b.WriteString("// RegisterRoutes wires the generated REST resources onto mux. wrap is the\n")
	b.WriteString("// shared middleware chain (authenticated, WorkspaceFromHeader, limited) the\n")
	b.WriteString("// api package supplies, parameterized by per-op request rate.\n")
	b.WriteString("func RegisterRoutes(mux *http.ServeMux, wrap func(perMinute int, h http.Handler) http.Handler) {\n")
	b.WriteString("\trest.Register(mux, wrap, entities())\n")
	b.WriteString("}\n\n")

	b.WriteString("func entities() []rest.Entity {\n\treturn []rest.Entity{\n")
	for _, e := range apis {
		if err := writeEntity(&b, e); err != nil {
			return codegen.GenFile{}, err
		}
	}
	b.WriteString("\t}\n}\n")

	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		return codegen.GenFile{}, fmt.Errorf("routes.go: %w\n---\n%s", err, b.String())
	}
	return codegen.GenFile{Name: "routes.go", Content: string(formatted)}, nil
}

func writeEntity(b *strings.Builder, e schema.Entity) error {
	pk, err := pkFieldName(e)
	if err != nil {
		return err
	}
	b.WriteString("\t\t{\n")
	b.WriteString(fmt.Sprintf("\t\t\tSingular: %q, Plural: %q, Table: %q,\n", e.Name, codegen.Plural(e.Name), e.Table))
	b.WriteString(fmt.Sprintf("\t\t\tResource: query.Resource{\n\t\t\t\tTable: %q, PK: %q, DefaultSort: %q,\n", e.Schema+"."+e.Table, pk, e.DefaultSort))
	b.WriteString("\t\t\t\tFields: []query.Field{\n")
	for _, f := range e.Fields {
		if !f.Exposed {
			continue
		}
		b.WriteString(fmt.Sprintf("\t\t\t\t\t{Name: %q, Column: %q, Kind: %s, Ops: %s%s},\n",
			f.Name, f.Column, kindExpr(f.Kind), opsExpr(f), enumExpr(f)))
	}
	b.WriteString("\t\t\t\t},\n\t\t\t},\n")

	b.WriteString("\t\t\tRequires: map[string][]string{\n")
	for _, op := range e.API {
		acts, err := actionExprs(op.Requires)
		if err != nil {
			return fmt.Errorf("entity %s op %s: %w", e.Table, op.Op, err)
		}
		b.WriteString(fmt.Sprintf("\t\t\t\t%q: {%s},\n", op.Op, acts))
	}
	b.WriteString("\t\t\t},\n")

	if e.Sync && hasWriteOp(e) {
		b.WriteString(fmt.Sprintf("\t\t\tApply: %s.Apply, ApplyDelete: %s.ApplyDelete,\n", e.Table, e.Table))
	}
	b.WriteString("\t\t},\n")
	return nil
}

func hasWriteOp(e schema.Entity) bool {
	for _, op := range e.API {
		switch op.Op {
		case "create", "update", "delete":
			return true
		}
	}
	return false
}

func pkFieldName(e schema.Entity) (string, error) {
	if len(e.PrimaryKey) == 0 {
		return "", fmt.Errorf("entity %s has no primary key", e.Table)
	}
	for _, f := range e.Fields {
		if f.Column == e.PrimaryKey[0] {
			return f.Name, nil
		}
	}
	return "", fmt.Errorf("entity %s: no field for primary-key column %q", e.Table, e.PrimaryKey[0])
}

func kindExpr(k schema.Kind) string {
	switch k {
	case schema.KindUUID:
		return "query.KindUUID"
	case schema.KindInt:
		return "query.KindInt"
	case schema.KindTime:
		return "query.KindTime"
	case schema.KindBool:
		return "query.KindBool"
	case schema.KindJSON:
		return "query.KindJSON"
	case schema.KindInet:
		return "query.KindInet"
	default: // text
		return "query.KindText"
	}
}

func opsExpr(f schema.Field) string {
	toks := schema.ODataOperators(f)
	parts := make([]string, 0, len(toks))
	for _, t := range toks {
		parts = append(parts, opConst(t))
	}
	return "[]query.Op{" + strings.Join(parts, ", ") + "}"
}

func opConst(tok string) string {
	switch tok {
	case "eq":
		return "query.OpEq"
	case "ne":
		return "query.OpNe"
	case "lt":
		return "query.OpLt"
	case "le":
		return "query.OpLe"
	case "gt":
		return "query.OpGt"
	case "ge":
		return "query.OpGe"
	case "in":
		return "query.OpIn"
	case "not in":
		return "query.OpNotIn"
	case "contains":
		return "query.OpContains"
	case "startswith":
		return "query.OpStartsWith"
	case "endswith":
		return "query.OpEndsWith"
	}
	return ""
}

func enumExpr(f schema.Field) string {
	if len(f.Values) == 0 {
		return ""
	}
	qs := make([]string, len(f.Values))
	for i, v := range f.Values {
		qs[i] = fmt.Sprintf("%q", v)
	}
	return ", Enum: []string{" + strings.Join(qs, ", ") + "}"
}

func actionExprs(requires []string) (string, error) {
	parts := make([]string, len(requires))
	for i, r := range requires {
		c, ok := syncer.ActionConst(r)
		if !ok {
			return "", fmt.Errorf("unknown requires action %q", r)
		}
		parts[i] = c
	}
	return strings.Join(parts, ", "), nil
}

func sortedKeys(m map[string]bool) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}
