// Package httpapi projects the apigen entity model into the generated REST route
// table under internal/api/gen. Mirroring the syncer's layout, each @app.api
// entity gets its own package folder: resource.go (the queryable field spec) and
// one file per endpoint (list.go, get.go, create.go, …), plus a routes.go, with
// a top-level routes.go aggregating them.
//
// Each endpoint file holds the FULL handler inlined — the gate check, the query
// runtime call, the syncer Apply, the status codes — not a delegation to a
// generic helper. This is code generation: the boilerplate is the point. A
// reader opens internal/api/gen/role/create.go and sees exactly what a role
// create does, top to bottom, without following an abstraction into the rest
// package. The rest package holds only primitives (response writers, the authz
// gate, body decode) the handlers call. Field specs come from the same IR that
// produces the OpenAPI filterable-fields table, so the API and its docs
// advertise and accept the same fields/operators.
//
// Following the syncer emitter, the file skeletons are text/templates and every
// per-field/per-op decision is resolved into a view struct in Go first; the
// templates own only layout.
package httpapi

import (
	"fmt"
	"go/format"
	"strings"
	"text/template"

	"backend/internal/apigen/codegen"
	"backend/internal/apigen/schema"
	"backend/internal/apigen/syncer"
)

const genHeader = "// Code generated by apigen. DO NOT EDIT.\n\n"

// EmitRoutes renders the generated REST route table as a set of files rooted at
// internal/api/gen: one folder per @app.api entity plus the top-level routes.go.
// Templates render unformatted; every file is run through format.Source here.
func EmitRoutes(entities []schema.Entity) ([]codegen.GenFile, error) {
	var apis []schema.Entity
	for _, e := range entities {
		if len(e.API) > 0 {
			apis = append(apis, e)
		}
	}

	var files []codegen.GenFile
	for _, e := range apis {
		fs, err := emitEntity(e)
		if err != nil {
			return nil, err
		}
		files = append(files, fs...)
	}
	files = append(files, codegen.GenFile{Name: "routes.go", Content: codegen.Render(topRoutesTmpl, topData{Tables: tableNames(apis)})})

	for i, f := range files {
		formatted, err := format.Source([]byte(f.Content))
		if err != nil {
			return nil, fmt.Errorf("%s: %w", f.Name, err)
		}
		files[i].Content = string(formatted)
	}
	return files, nil
}

// emitEntity produces one entity's package folder: resource.go, a file per op,
// and routes.go. The folder/package is named for the table (as the syncer's is).
func emitEntity(e schema.Entity) ([]codegen.GenFile, error) {
	dir := e.Table + "/"

	rd, err := newResourceData(e)
	if err != nil {
		return nil, err
	}
	files := []codegen.GenFile{{Name: dir + "resource.go", Content: codegen.Render(resourceTmpl, rd)}}

	for _, op := range e.API {
		od, err := newOpData(e, op)
		if err != nil {
			return nil, fmt.Errorf("entity %s op %s: %w", e.Table, op.Op, err)
		}
		tmpl, err := opTemplate(op.Op)
		if err != nil {
			return nil, fmt.Errorf("entity %s: %w", e.Table, err)
		}
		files = append(files, codegen.GenFile{Name: dir + op.Op + ".go", Content: codegen.Render(tmpl, od)})
	}

	files = append(files, codegen.GenFile{Name: dir + "routes.go", Content: codegen.Render(routesTmpl, newRouteData(e))})
	return files, nil
}

// --- views -----------------------------------------------------------------

// fieldData is one exposed column projected onto a query.Field literal. Kind,
// Ops, and Enum are pre-rendered Go expressions so the template only places them.
type fieldData struct{ Name, Column, Kind, Ops, Enum string }

// resourceData is the view for resource.go: the table's shared query.Resource
// and the naming constants the handlers reference.
type resourceData struct {
	Pkg, QualTable, PK, DefaultSort, Name string
	Fields                                []fieldData
	HasWrite                              bool
}

func newResourceData(e schema.Entity) (resourceData, error) {
	pk, err := pkFieldName(e)
	if err != nil {
		return resourceData{}, err
	}
	d := resourceData{
		Pkg: e.Table, QualTable: e.Schema + "." + e.Table,
		PK: pk, DefaultSort: e.DefaultSort, Name: e.Name,
		HasWrite: hasWriteOp(e),
	}
	for _, f := range e.Fields {
		if !f.Exposed {
			continue
		}
		d.Fields = append(d.Fields, fieldData{
			Name: f.Name, Column: f.Column,
			Kind: kindExpr(f.Kind), Ops: opsExpr(f), Enum: enumExpr(f),
		})
	}
	return d, nil
}

// writeFields builds the per-field validate.Field literals a write handler
// validates its body against: every client-settable column with its
// type/nullable/enum, the same writable set as the OpenAPI request schema.
//
// The create flag captures the two contracts' real differences. On create the
// client MAY supply the id in the body — validated as a uuid when present, but
// optional; the handler generates one when it's omitted (REST-conventional
// server-assigned id, with a client-supplied id supported for idempotent
// creates). So id leads the list but is not Required, while NOT NULL no-default
// columns are. On update the id is the URL path, not a body field, so id is
// absent, and the body is a partial patch, so nothing is Required.
func writeFields(e schema.Entity, create bool) ([]string, error) {
	var out []string
	if create {
		pk, err := pkFieldName(e)
		if err != nil {
			return nil, err
		}
		out = append(out, writeFieldLit(pk, "query.KindUUID", false, false, nil))
	}
	for _, f := range e.Fields {
		if !schema.IsWritable(f) {
			continue
		}
		required := create && schema.RequiredOnCreate(f)
		out = append(out, writeFieldLit(f.Name, kindExpr(f.Kind), required, f.Nullable, f.Values))
	}
	return out, nil
}

// writeFieldLit renders one validate.Field literal, emitting only the non-zero
// options so the generated spec stays terse.
func writeFieldLit(name, kindExpr string, required, nullable bool, enum []string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "{Name: %q, Kind: %s", name, kindExpr)
	if required {
		b.WriteString(", Required: true")
	}
	if nullable {
		b.WriteString(", Nullable: true")
	}
	if len(enum) > 0 {
		qs := make([]string, len(enum))
		for i, v := range enum {
			qs[i] = fmt.Sprintf("%q", v)
		}
		b.WriteString(", Enum: []string{" + strings.Join(qs, ", ") + "}")
	}
	b.WriteString("}")
	return b.String()
}

// opData is the view every endpoint template renders: the package, the URL
// plural, the inline gate argument, whether the core action package is imported,
// and (for writes) the syncer-glue import path.
type opData struct {
	Pkg, Plural, Gate, SyncImport string
	UsesCore                      bool
	WriteFields                   []string // validate.Field literals; set for create/update
}

func newOpData(e schema.Entity, op schema.APIOp) (opData, error) {
	gate, usesCore, err := gateArg(op.Requires)
	if err != nil {
		return opData{}, err
	}
	d := opData{
		Pkg: e.Table, Plural: codegen.Plural(e.Name),
		Gate: gate, UsesCore: usesCore,
		SyncImport: "backend/internal/syncer/gen/" + e.Table,
	}
	if op.Op == "create" || op.Op == "update" {
		if d.WriteFields, err = writeFields(e, op.Op == "create"); err != nil {
			return opData{}, err
		}
	}
	return d, nil
}

// routeLine is one mux.Handle mounting: the "METHOD /path" pattern, the rate
// constant, and the handler constructor to call.
type routeLine struct{ Pattern, Rate, Handler string }

// routeData is the view for an entity's routes.go.
type routeData struct {
	Pkg, Name string
	Routes    []routeLine
}

func newRouteData(e schema.Entity) routeData {
	plural := codegen.Plural(e.Name)
	d := routeData{Pkg: e.Table, Name: e.Name}
	for _, op := range e.API {
		d.Routes = append(d.Routes, routeLine{
			Pattern: schema.RESTMethod(op.Op) + " " + path(op.Op, plural),
			Rate:    rateConst(op.Op),
			Handler: codegen.Pascal(op.Op),
		})
	}
	return d
}

// topData is the view for the top-level routes.go.
type topData struct{ Tables []string }

func tableNames(apis []schema.Entity) []string {
	out := make([]string, len(apis))
	for i, e := range apis {
		out[i] = e.Table
	}
	return out
}

// --- per-op decisions (resolved in Go, placed by the templates) -------------

// gateArg renders an op's required-actions argument to rest.Gate: nil when the
// op is open to any member, else an inline []string{...} of core action
// constants. The bool reports whether the core package is referenced.
func gateArg(requires []string) (string, bool, error) {
	if len(requires) == 0 {
		return "nil", false, nil
	}
	acts, err := actionExprs(requires)
	if err != nil {
		return "", false, err
	}
	return "[]string{" + acts + "}", true, nil
}

func opTemplate(op string) (*template.Template, error) {
	switch op {
	case "list":
		return listTmpl, nil
	case "get":
		return getTmpl, nil
	case "create":
		return createTmpl, nil
	case "update":
		return updateTmpl, nil
	case "delete":
		return deleteTmpl, nil
	}
	return nil, fmt.Errorf("unknown api op %q", op)
}

// path is the REST path an op mounts on: the collection /plural (list, create)
// or the item /plural/{id} (get, update, delete). The collection/item split is
// single-sourced in schema (shared with the OpenAPI emitter).
func path(op, plural string) string {
	if schema.OnCollection(op) {
		return "/" + plural
	}
	return "/" + plural + "/{id}"
}

// rateConst is the per-op rate constant: stricter for writes, cheap for reads.
func rateConst(op string) string {
	if schema.IsWriteOp(op) {
		return "WriteRate"
	}
	return "ReadRate"
}

func hasWriteOp(e schema.Entity) bool {
	for _, op := range e.API {
		if schema.IsWriteOp(op.Op) {
			return true
		}
	}
	return false
}

func pkFieldName(e schema.Entity) (string, error) {
	if len(e.PrimaryKey) == 0 {
		return "", fmt.Errorf("entity %s has no primary key", e.Table)
	}
	for _, f := range e.Fields {
		if f.Column == e.PrimaryKey[0] {
			return f.Name, nil
		}
	}
	return "", fmt.Errorf("entity %s: no field for primary-key column %q", e.Table, e.PrimaryKey[0])
}

func kindExpr(k schema.Kind) string {
	switch k {
	case schema.KindUUID:
		return "query.KindUUID"
	case schema.KindInt:
		return "query.KindInt"
	case schema.KindTime:
		return "query.KindTime"
	case schema.KindBool:
		return "query.KindBool"
	case schema.KindJSON:
		return "query.KindJSON"
	case schema.KindInet:
		return "query.KindInet"
	default: // text
		return "query.KindText"
	}
}

// opsExpr renders a field's operator set as a []query.Op literal. query.Op is a
// string type whose values are exactly the OData tokens ODataOperators yields
// (query.OpEq == "eq"), so the token value is emitted directly rather than
// re-deriving query's constant identifiers here — the token spelling is the
// contract, owned by the query package.
func opsExpr(f schema.Field) string {
	toks := schema.ODataOperators(f)
	parts := make([]string, 0, len(toks))
	for _, t := range toks {
		parts = append(parts, fmt.Sprintf("%q", t))
	}
	return "[]query.Op{" + strings.Join(parts, ", ") + "}"
}

func enumExpr(f schema.Field) string {
	if len(f.Values) == 0 {
		return ""
	}
	qs := make([]string, len(f.Values))
	for i, v := range f.Values {
		qs[i] = fmt.Sprintf("%q", v)
	}
	return ", Enum: []string{" + strings.Join(qs, ", ") + "}"
}

func actionExprs(requires []string) (string, error) {
	parts := make([]string, len(requires))
	for i, r := range requires {
		c, ok := syncer.ActionConst(r)
		if !ok {
			return "", fmt.Errorf("unknown requires action %q", r)
		}
		parts[i] = c
	}
	return strings.Join(parts, ", "), nil
}

// --- templates (skeletons only) --------------------------------------------

var resourceTmpl = mustParse("resource.go.tmpl")

var listTmpl = mustParse("list.go.tmpl")

var getTmpl = mustParse("get.go.tmpl")

var createTmpl = mustParse("create.go.tmpl")

var updateTmpl = mustParse("update.go.tmpl")

var deleteTmpl = mustParse("delete.go.tmpl")

var routesTmpl = mustParse("routes.go.tmpl")

var topRoutesTmpl = mustParse("toproutes.go.tmpl")
