// Package httpapi projects the apigen entity model into the generated REST route
// table under internal/api/gen. Mirroring the syncer's layout, each @app.api
// entity gets its own package folder — a resource descriptor plus one file per
// endpoint (list.go, get.go, …) and a routes.go — with a top-level routes.go
// aggregating them. The emitted code is thin: a rest.Entity descriptor (table +
// exposed fields + per-op required actions + the syncer Apply/ApplyDelete for
// synced entities) and handlers that delegate to the hand-written rest runtime.
// Field specs come from the same IR that produces the OpenAPI filterable-fields
// table, so the API and its docs advertise and accept the same fields/operators.
package httpapi

import (
	"fmt"
	"go/format"
	"strings"

	"backend/internal/apigen/codegen"
	"backend/internal/apigen/schema"
	"backend/internal/apigen/syncer"
)

const genHeader = "// Code generated by apigen. DO NOT EDIT.\n\n"

// EmitRoutes renders the generated REST route table as a set of files rooted at
// internal/api/gen: one folder per @app.api entity plus the top-level routes.go.
func EmitRoutes(entities []schema.Entity) ([]codegen.GenFile, error) {
	var apis []schema.Entity
	for _, e := range entities {
		if len(e.API) > 0 {
			apis = append(apis, e)
		}
	}

	var files []codegen.GenFile
	for _, e := range apis {
		fs, err := emitEntity(e)
		if err != nil {
			return nil, err
		}
		files = append(files, fs...)
	}
	top, err := emitTopRoutes(apis)
	if err != nil {
		return nil, err
	}
	return append(files, top), nil
}

// emitEntity produces one entity's package folder: resource.go, a file per op,
// and routes.go. The folder/package is named for the table (as the syncer's is).
func emitEntity(e schema.Entity) ([]codegen.GenFile, error) {
	dir := e.Table + "/"
	var files []codegen.GenFile

	res, err := emitResource(e)
	if err != nil {
		return nil, err
	}
	files = append(files, codegen.GenFile{Name: dir + "resource.go", Content: res})

	for _, op := range e.API {
		f, err := emitOp(e, op.Op)
		if err != nil {
			return nil, err
		}
		files = append(files, codegen.GenFile{Name: dir + op.Op + ".go", Content: f})
	}

	routes, err := emitEntityRoutes(e)
	if err != nil {
		return nil, err
	}
	return append(files, codegen.GenFile{Name: dir + "routes.go", Content: routes}), nil
}

// emitResource writes the rest.Entity descriptor: the queryable field specs, the
// per-op required actions, and (for synced entities) the syncer Apply refs.
func emitResource(e schema.Entity) (string, error) {
	pk, err := pkFieldName(e)
	if err != nil {
		return "", err
	}
	needCore := false
	for _, op := range e.API {
		if len(op.Requires) > 0 {
			needCore = true
		}
	}
	write := e.Sync && hasWriteOp(e)

	b := &strings.Builder{}
	b.WriteString(genHeader)
	fmt.Fprintf(b, "package %s\n\n", e.Table)
	b.WriteString("import (\n")
	b.WriteString("\t\"backend/internal/api/query\"\n")
	b.WriteString("\t\"backend/internal/api/rest\"\n")
	if needCore {
		b.WriteString("\n\tcore \"github.com/selectDb/dialect/core\"\n")
	}
	if write {
		fmt.Fprintf(b, "\n\tsyncgen %q\n", "backend/internal/syncer/gen/"+e.Table)
	}
	b.WriteString(")\n\n")

	fmt.Fprintf(b, "// entity describes the %s resource: its queryable fields and the\n", e.Name)
	if write {
		b.WriteString("// per-op required workspace actions, plus the syncer Apply/ApplyDelete\n")
		b.WriteString("// the write handlers delegate to.\n")
	} else {
		b.WriteString("// per-op required workspace actions (read-only: no writes).\n")
	}
	b.WriteString("var entity = rest.Entity{\n")
	fmt.Fprintf(b, "\tSingular: %q, Plural: %q, Table: %q,\n", e.Name, codegen.Plural(e.Name), e.Table)
	fmt.Fprintf(b, "\tResource: query.Resource{\n\t\tTable: %q, PK: %q, DefaultSort: %q,\n", e.Schema+"."+e.Table, pk, e.DefaultSort)
	b.WriteString("\t\tFields: []query.Field{\n")
	for _, f := range e.Fields {
		if !f.Exposed {
			continue
		}
		fmt.Fprintf(b, "\t\t\t{Name: %q, Column: %q, Kind: %s, Ops: %s%s},\n",
			f.Name, f.Column, kindExpr(f.Kind), opsExpr(f), enumExpr(f))
	}
	b.WriteString("\t\t},\n\t},\n")

	b.WriteString("\tRequires: map[string][]string{\n")
	for _, op := range e.API {
		acts, err := actionExprs(op.Requires)
		if err != nil {
			return "", fmt.Errorf("entity %s op %s: %w", e.Table, op.Op, err)
		}
		fmt.Fprintf(b, "\t\t%q: {%s},\n", op.Op, acts)
	}
	b.WriteString("\t},\n")
	if write {
		b.WriteString("\tApply: syncgen.Apply, ApplyDelete: syncgen.ApplyDelete,\n")
	}
	b.WriteString("}\n")

	return formatGo(b.String())
}

// emitOp writes one endpoint file: a handler that delegates to the rest runtime.
func emitOp(e schema.Entity, op string) (string, error) {
	b := &strings.Builder{}
	b.WriteString(genHeader)
	fmt.Fprintf(b, "package %s\n\n", e.Table)
	b.WriteString("import (\n\t\"net/http\"\n\n\t\"backend/internal/api/rest\"\n)\n\n")
	fmt.Fprintf(b, "// %s handles %s %s.\n", opFn(op), method(op), path(op, codegen.Plural(e.Name)))
	fmt.Fprintf(b, "func %s() http.HandlerFunc { return rest.%sHandler(entity) }\n", opFn(op), opFn(op))
	return formatGo(b.String())
}

// emitEntityRoutes writes the entity's Register: it mounts each declared op on
// its REST path with the shared middleware chain at the per-op rate.
func emitEntityRoutes(e schema.Entity) (string, error) {
	plural := codegen.Plural(e.Name)
	b := &strings.Builder{}
	b.WriteString(genHeader)
	fmt.Fprintf(b, "package %s\n\n", e.Table)
	b.WriteString("import (\n\t\"net/http\"\n\n\t\"backend/internal/api/rest\"\n)\n\n")
	fmt.Fprintf(b, "// Register mounts the %s endpoints on mux.\n", e.Name)
	b.WriteString("func Register(mux *http.ServeMux, wrap rest.Wrap) {\n")
	for _, op := range e.API {
		fmt.Fprintf(b, "\tmux.Handle(%q, wrap(rest.%s, %s()))\n",
			method(op.Op)+" "+path(op.Op, plural), rateConst(op.Op), opFn(op.Op))
	}
	b.WriteString("}\n")
	return formatGo(b.String())
}

// emitTopRoutes writes internal/api/gen/routes.go, which calls each entity
// package's Register.
func emitTopRoutes(apis []schema.Entity) (codegen.GenFile, error) {
	b := &strings.Builder{}
	b.WriteString(genHeader)
	b.WriteString("package gen\n\n")
	b.WriteString("import (\n\t\"net/http\"\n\n\t\"backend/internal/api/rest\"\n\n")
	for _, e := range apis {
		fmt.Fprintf(b, "\t%s %q\n", e.Table, "backend/internal/api/gen/"+e.Table)
	}
	b.WriteString(")\n\n")
	b.WriteString("// RegisterRoutes wires every generated REST resource onto mux with the shared\n")
	b.WriteString("// middleware chain (authenticated, WorkspaceFromHeader, limited) the api\n")
	b.WriteString("// package supplies.\n")
	b.WriteString("func RegisterRoutes(mux *http.ServeMux, wrap rest.Wrap) {\n")
	for _, e := range apis {
		fmt.Fprintf(b, "\t%s.Register(mux, wrap)\n", e.Table)
	}
	b.WriteString("}\n")
	c, err := formatGo(b.String())
	if err != nil {
		return codegen.GenFile{}, err
	}
	return codegen.GenFile{Name: "routes.go", Content: c}, nil
}

func formatGo(src string) (string, error) {
	out, err := format.Source([]byte(src))
	if err != nil {
		return "", fmt.Errorf("format: %w\n---\n%s", err, src)
	}
	return string(out), nil
}

// opFn is the exported handler/registration name for an op (list -> List).
func opFn(op string) string { return strings.ToUpper(op[:1]) + op[1:] }

func method(op string) string {
	switch op {
	case "create":
		return "POST"
	case "update":
		return "PATCH"
	case "delete":
		return "DELETE"
	default: // list, get
		return "GET"
	}
}

func path(op, plural string) string {
	switch op {
	case "list", "create":
		return "/" + plural
	default: // get, update, delete
		return "/" + plural + "/{id}"
	}
}

func rateConst(op string) string {
	switch op {
	case "create", "update", "delete":
		return "WriteRate"
	default:
		return "ReadRate"
	}
}

func hasWriteOp(e schema.Entity) bool {
	for _, op := range e.API {
		switch op.Op {
		case "create", "update", "delete":
			return true
		}
	}
	return false
}

func pkFieldName(e schema.Entity) (string, error) {
	if len(e.PrimaryKey) == 0 {
		return "", fmt.Errorf("entity %s has no primary key", e.Table)
	}
	for _, f := range e.Fields {
		if f.Column == e.PrimaryKey[0] {
			return f.Name, nil
		}
	}
	return "", fmt.Errorf("entity %s: no field for primary-key column %q", e.Table, e.PrimaryKey[0])
}

func kindExpr(k schema.Kind) string {
	switch k {
	case schema.KindUUID:
		return "query.KindUUID"
	case schema.KindInt:
		return "query.KindInt"
	case schema.KindTime:
		return "query.KindTime"
	case schema.KindBool:
		return "query.KindBool"
	case schema.KindJSON:
		return "query.KindJSON"
	case schema.KindInet:
		return "query.KindInet"
	default: // text
		return "query.KindText"
	}
}

func opsExpr(f schema.Field) string {
	toks := schema.ODataOperators(f)
	parts := make([]string, 0, len(toks))
	for _, t := range toks {
		parts = append(parts, opConst(t))
	}
	return "[]query.Op{" + strings.Join(parts, ", ") + "}"
}

func opConst(tok string) string {
	switch tok {
	case "eq":
		return "query.OpEq"
	case "ne":
		return "query.OpNe"
	case "lt":
		return "query.OpLt"
	case "le":
		return "query.OpLe"
	case "gt":
		return "query.OpGt"
	case "ge":
		return "query.OpGe"
	case "in":
		return "query.OpIn"
	case "not in":
		return "query.OpNotIn"
	case "contains":
		return "query.OpContains"
	case "startswith":
		return "query.OpStartsWith"
	case "endswith":
		return "query.OpEndsWith"
	}
	return ""
}

func enumExpr(f schema.Field) string {
	if len(f.Values) == 0 {
		return ""
	}
	qs := make([]string, len(f.Values))
	for i, v := range f.Values {
		qs[i] = fmt.Sprintf("%q", v)
	}
	return ", Enum: []string{" + strings.Join(qs, ", ") + "}"
}

func actionExprs(requires []string) (string, error) {
	parts := make([]string, len(requires))
	for i, r := range requires {
		c, ok := syncer.ActionConst(r)
		if !ok {
			return "", fmt.Errorf("unknown requires action %q", r)
		}
		parts[i] = c
	}
	return strings.Join(parts, ", "), nil
}
