// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteDatasource(arg1) {
  return window['go']['datasource']['Datasource']['DeleteDatasource'](arg1);
}

export function GetDatasource(arg1) {
  return window['go']['datasource']['Datasource']['GetDatasource'](arg1);
}

export function UpsertDatasource(arg1) {
  return window['go']['datasource']['Datasource']['UpsertDatasource'](arg1);
}
