// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {datasource} from '../models';

export function DeleteDatasource(arg1:string):Promise<void>;

export function GetDatasource(arg1:string):Promise<datasource.GetResult>;

export function UpsertDatasource(arg1:datasource.UpsertParams):Promise<void>;
