// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Delete(arg1) {
  return window['go']['fs_provider']['FSProvider']['Delete'](arg1);
}

export function ExecuteCommand(arg1) {
  return window['go']['fs_provider']['FSProvider']['ExecuteCommand'](arg1);
}

export function GetOSPathFromURI(arg1) {
  return window['go']['fs_provider']['FSProvider']['GetOSPathFromURI'](arg1);
}

export function Mkdir(arg1) {
  return window['go']['fs_provider']['FSProvider']['Mkdir'](arg1);
}

export function ReadDirectory(arg1) {
  return window['go']['fs_provider']['FSProvider']['ReadDirectory'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['fs_provider']['FSProvider']['ReadFile'](arg1);
}

export function Rename(arg1) {
  return window['go']['fs_provider']['FSProvider']['Rename'](arg1);
}

export function SetRoot(arg1) {
  return window['go']['fs_provider']['FSProvider']['SetRoot'](arg1);
}

export function Stat(arg1) {
  return window['go']['fs_provider']['FSProvider']['Stat'](arg1);
}

export function Write(arg1) {
  return window['go']['fs_provider']['FSProvider']['Write'](arg1);
}
