// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {fs_provider} from '../models';

export function Delete(arg1:fs_provider.DeleteParams):Promise<void>;

export function ExecuteCommand(arg1:fs_provider.ExecuteCommandParams):Promise<fs_provider.CommandResult>;

export function GetOSPathFromURI(arg1:string):Promise<string>;

export function Mkdir(arg1:fs_provider.MkdirParams):Promise<void>;

export function ReadDirectory(arg1:fs_provider.ReadDirectoryParams):Promise<Array<fs_provider.DirEntry>>;

export function ReadFile(arg1:fs_provider.ReadFileParams):Promise<string>;

export function Rename(arg1:fs_provider.RenameParams):Promise<void>;

export function SetRoot(arg1:string):Promise<void>;

export function Stat(arg1:string):Promise<fs_provider.FileStat>;

export function Write(arg1:fs_provider.WriteParams):Promise<void>;
