// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Git encapsulates all Git-related operations for the desktop app.
 * It orchestrates local git commands for version control functionality.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CommitChanges creates a commit with the given message from all staged changes.
 */
export function CommitChanges(params: $models.CommitParams): $CancellablePromise<void> {
    return $Call.ByID(17261112, params);
}

/**
 * GetBranches returns a list of all branches (local and remote).
 */
export function GetBranches(): $CancellablePromise<$models.BranchInfo[]> {
    return $Call.ByID(3107412534).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetFileDiffContent returns the content of a file at HEAD (left) and in the working tree (right).
 * Left is empty for untracked/new files; right is empty for deleted files.
 * Files larger than 1 MiB return a placeholder string instead of their content.
 */
export function GetFileDiffContent(params: $models.GetFileDiffContentParams): $CancellablePromise<$models.GetFileDiffContentResult | null> {
    return $Call.ByID(3235413672, params).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetGitFileStatus returns file-level git status for the workspace, including
 * staged, unstaged, and untracked files.
 */
export function GetGitFileStatus(): $CancellablePromise<$models.GitFileStatus | null> {
    return $Call.ByID(3862879922).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GetGitWorkspaceStatus is intentionally conservative: a failing git command
 * reads as "not a repo" rather than an error, so the panel always renders.
 */
export function GetGitWorkspaceStatus(): $CancellablePromise<$models.GitWorkspaceStatus | null> {
    return $Call.ByID(2936111873).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * PullWithRebase pulls from origin and rebases local commits on top of the remote branch.
 */
export function PullWithRebase(): $CancellablePromise<void> {
    return $Call.ByID(3220108701);
}

/**
 * PullWorkspaceRepo pulls the current branch of the workspace repository from
 * its "origin" remote.
 */
export function PullWorkspaceRepo(): $CancellablePromise<void> {
    return $Call.ByID(839737822);
}

/**
 * PushForceWithLease pushes the current branch to origin using --force-with-lease,
 * overwriting the remote only if it has not been updated since the last fetch.
 */
export function PushForceWithLease(): $CancellablePromise<void> {
    return $Call.ByID(552458801);
}

/**
 * PushWorkspaceRepo pushes the current branch of the workspace repository to
 * its "origin" remote, creating the upstream tracking branch if needed.
 */
export function PushWorkspaceRepo(): $CancellablePromise<void> {
    return $Call.ByID(3836615083);
}

/**
 * ResetBranchToRemote fetches from origin and resets the current branch to match the remote,
 * discarding local commits and uncommitted changes.
 */
export function ResetBranchToRemote(): $CancellablePromise<void> {
    return $Call.ByID(467262130);
}

/**
 * RevertAll discards all changes to all files, including deleting untracked files.
 */
export function RevertAll(): $CancellablePromise<void> {
    return $Call.ByID(3870011391);
}

/**
 * RevertFile discards all changes to a file (both staged and unstaged).
 * For staged files, it unstages them first, then discards working tree changes.
 * For unstaged files, it just discards working tree changes.
 * After reverting, it cleans up any empty directories that were left behind
 * (e.g., when a renamed file is reverted to its original location).
 */
export function RevertFile(params: $models.RevertFileParams): $CancellablePromise<void> {
    return $Call.ByID(2643667058, params);
}

export function SetContext(): $CancellablePromise<void> {
    return $Call.ByID(1897303165);
}

/**
 * StageAll stages all changes (modified, deleted, and untracked files).
 */
export function StageAll(): $CancellablePromise<void> {
    return $Call.ByID(3539593559);
}

/**
 * StageFile stages a single file for commit.
 */
export function StageFile(params: $models.StageFileParams): $CancellablePromise<void> {
    return $Call.ByID(304979930, params);
}

/**
 * SwitchBranch switches to the specified branch, creating it from remote if needed.
 */
export function SwitchBranch(params: $models.SwitchBranchParams): $CancellablePromise<void> {
    return $Call.ByID(1018717906, params);
}

/**
 * UnstageAll unstages all changes.
 */
export function UnstageAll(): $CancellablePromise<void> {
    return $Call.ByID(3595579392);
}

/**
 * UnstageFile unstages a single file.
 */
export function UnstageFile(params: $models.UnstageFileParams): $CancellablePromise<void> {
    return $Call.ByID(3153094655, params);
}

// Private type creation functions
const $$createType0 = $models.BranchInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.GetFileDiffContentResult.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $models.GitFileStatus.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $models.GitWorkspaceStatus.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
