// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Git encapsulates all Git-related operations for the desktop app.
 * It orchestrates local git commands for version control functionality.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CommitChanges creates a commit with the given message from all staged changes.
 */
export function CommitChanges(params: $models.CommitParams): $CancellablePromise<void> {
    return $Call.ByID(17261112, params);
}

/**
 * CompleteLinkExistingRepo finalises a pending link started by LinkExistingRepo.
 * choice "checkout" replaces local files with the remote branch.
 * choice "keep" leaves local files untouched; the remote is already configured.
 */
export function CompleteLinkExistingRepo(choice: string): $CancellablePromise<void> {
    return $Call.ByID(2686222576, choice);
}

/**
 * GetBranches returns a list of all branches (local and remote).
 */
export function GetBranches(): $CancellablePromise<$models.BranchInfo[]> {
    return $Call.ByID(3107412534).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetFileDiffContent returns the content of a file at HEAD (left) and in the working tree (right).
 * Left is empty for untracked/new files; right is empty for deleted files.
 * Files larger than 1 MiB return a placeholder string instead of their content.
 */
export function GetFileDiffContent(params: $models.GetFileDiffContentParams): $CancellablePromise<$models.GetFileDiffContentResult | null> {
    return $Call.ByID(3235413672, params).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetGitFileStatus returns file-level git status for the workspace, including
 * staged, unstaged, and untracked files.
 */
export function GetGitFileStatus(): $CancellablePromise<$models.GitFileStatus | null> {
    return $Call.ByID(3862879922).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GetGitWorkspaceStatus inspects the local filesystem and returns high-level Git status information.
 * 
 * It is intentionally conservative: failure to run git commands is treated as
 * "not a git repo" / "no remote" rather than an error, so that the UI can
 * still render and offer init/publish flows.
 */
export function GetGitWorkspaceStatus(): $CancellablePromise<$models.GitWorkspaceStatus | null> {
    return $Call.ByID(2936111873).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * InitAndPublishRepo performs local git initialization and creates an initial
 * commit for the given workspace. A later iteration will extend this to call
 * the remote backend to actually create the GitHub repo and push.
 */
export function InitAndPublishRepo(params: $models.InitAndPublishParams): $CancellablePromise<void> {
    return $Call.ByID(2303337240, params);
}

/**
 * LinkExistingRepo is the user-facing Wails method. It performs all
 * non-destructive setup (init, remote, persist, fetch) and returns a
 * LinkStatus. When Scenario is "checkout", the frontend shows a choice modal
 * and then calls CompleteLinkExistingRepo with the user's decision.
 */
export function LinkExistingRepo(params: $models.LinkExistingParams): $CancellablePromise<$models.LinkStatus> {
    return $Call.ByID(3976444531, params).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * LinkExistingRepoForWorkspace configures the local git repository for the
 * given workspace ID to point at an existing remote. It delegates to
 * ReconcileWorkspaceRemote so there is a single, idempotent, self-healing code
 * path for materializing a workspace's repository.
 */
export function LinkExistingRepoForWorkspace(workspaceID: string, params: $models.LinkExistingParams): $CancellablePromise<void> {
    return $Call.ByID(1239714551, workspaceID, params);
}

/**
 * PullWithRebase pulls from origin and rebases local commits on top of the remote branch.
 */
export function PullWithRebase(): $CancellablePromise<void> {
    return $Call.ByID(3220108701);
}

/**
 * PullWorkspaceRepo pulls the current branch of the workspace repository from
 * its "origin" remote.
 */
export function PullWorkspaceRepo(): $CancellablePromise<void> {
    return $Call.ByID(839737822);
}

/**
 * PushForceWithLease pushes the current branch to origin using --force-with-lease,
 * overwriting the remote only if it has not been updated since the last fetch.
 */
export function PushForceWithLease(): $CancellablePromise<void> {
    return $Call.ByID(552458801);
}

/**
 * PushWorkspaceRepo pushes the current branch of the workspace repository to
 * its "origin" remote, creating the upstream tracking branch if needed.
 */
export function PushWorkspaceRepo(): $CancellablePromise<void> {
    return $Call.ByID(3836615083);
}

/**
 * ReconcileWorkspaceRemote makes the local workspace repository converge to
 * desiredURL (or to "no remote" when desiredURL is nil). It is idempotent and
 * self-healing, and it never destroys unpushed work: before any switch it
 * snapshots the whole workspace (including .git) to a backup directory.
 * 
 * It does not write the workspace.git_remote_url DB column. That column is
 * owned by the sync layer (UpsertWorkspaceForSync, @no-track) and by the
 * interactive admin actions; writing it here would echo a redundant workspace
 * commit back to the server.
 */
export function ReconcileWorkspaceRemote(workspaceID: string, desiredURL: string | null): $CancellablePromise<$models.ReconcileResult> {
    return $Call.ByID(2249883805, workspaceID, desiredURL).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * ResetBranchToRemote fetches from origin and resets the current branch to match the remote,
 * discarding local commits and uncommitted changes.
 */
export function ResetBranchToRemote(): $CancellablePromise<void> {
    return $Call.ByID(467262130);
}

/**
 * RevertAll discards all changes to all files, including deleting untracked files.
 */
export function RevertAll(): $CancellablePromise<void> {
    return $Call.ByID(3870011391);
}

/**
 * RevertFile discards all changes to a file (both staged and unstaged).
 * For staged files, it unstages them first, then discards working tree changes.
 * For unstaged files, it just discards working tree changes.
 * After reverting, it cleans up any empty directories that were left behind
 * (e.g., when a renamed file is reverted to its original location).
 */
export function RevertFile(params: $models.RevertFileParams): $CancellablePromise<void> {
    return $Call.ByID(2643667058, params);
}

export function SetContext(): $CancellablePromise<void> {
    return $Call.ByID(1897303165);
}

/**
 * StageAll stages all changes (modified, deleted, and untracked files).
 */
export function StageAll(): $CancellablePromise<void> {
    return $Call.ByID(3539593559);
}

/**
 * StageFile stages a single file for commit.
 */
export function StageFile(params: $models.StageFileParams): $CancellablePromise<void> {
    return $Call.ByID(304979930, params);
}

/**
 * SwitchBranch switches to the specified branch, creating it from remote if needed.
 */
export function SwitchBranch(params: $models.SwitchBranchParams): $CancellablePromise<void> {
    return $Call.ByID(1018717906, params);
}

/**
 * UnlinkRemote removes the "origin" remote from the workspace's git repository
 * and clears the workspace's stored git_remote_url so the workspace is considered unsynced.
 * The local .git directory and commits are left intact.
 */
export function UnlinkRemote(): $CancellablePromise<void> {
    return $Call.ByID(2704809219);
}

/**
 * UnstageAll unstages all changes.
 */
export function UnstageAll(): $CancellablePromise<void> {
    return $Call.ByID(3595579392);
}

/**
 * UnstageFile unstages a single file.
 */
export function UnstageFile(params: $models.UnstageFileParams): $CancellablePromise<void> {
    return $Call.ByID(3153094655, params);
}

// Private type creation functions
const $$createType0 = $models.BranchInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.GetFileDiffContentResult.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $models.GitFileStatus.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $models.GitWorkspaceStatus.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $models.LinkStatus.createFrom;
const $$createType9 = $models.ReconcileResult.createFrom;
