// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * BranchInfo represents information about a git branch
 */
export class BranchInfo {
    "name": string;
    "isCurrent": boolean;
    "isRemote": boolean;

    /** Creates a new BranchInfo instance. */
    constructor($$source: Partial<BranchInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("isCurrent" in $$source)) {
            this["isCurrent"] = false;
        }
        if (!("isRemote" in $$source)) {
            this["isRemote"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BranchInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): BranchInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BranchInfo($$parsedSource as Partial<BranchInfo>);
    }
}

/**
 * CommitParams defines the input for creating a commit.
 */
export class CommitParams {
    "message": string;

    /** Creates a new CommitParams instance. */
    constructor($$source: Partial<CommitParams> = {}) {
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CommitParams instance from a string or object.
     */
    static createFrom($$source: any = {}): CommitParams {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CommitParams($$parsedSource as Partial<CommitParams>);
    }
}

/**
 * GetFileDiffContentParams defines the input for fetching diff content for a file.
 */
export class GetFileDiffContentParams {
    /**
     * Relative path from workspace root
     */
    "path": string;

    /** Creates a new GetFileDiffContentParams instance. */
    constructor($$source: Partial<GetFileDiffContentParams> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GetFileDiffContentParams instance from a string or object.
     */
    static createFrom($$source: any = {}): GetFileDiffContentParams {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GetFileDiffContentParams($$parsedSource as Partial<GetFileDiffContentParams>);
    }
}

/**
 * GetFileDiffContentResult holds the left (HEAD) and right (working tree) content.
 */
export class GetFileDiffContentResult {
    "leftContent": string;
    "rightContent": string;

    /** Creates a new GetFileDiffContentResult instance. */
    constructor($$source: Partial<GetFileDiffContentResult> = {}) {
        if (!("leftContent" in $$source)) {
            this["leftContent"] = "";
        }
        if (!("rightContent" in $$source)) {
            this["rightContent"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GetFileDiffContentResult instance from a string or object.
     */
    static createFrom($$source: any = {}): GetFileDiffContentResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GetFileDiffContentResult($$parsedSource as Partial<GetFileDiffContentResult>);
    }
}

/**
 * GitFileStatus provides file-level git status information for the workspace.
 */
export class GitFileStatus {
    "branch": string;
    "staged": GitFileStatusItem[];
    "unstaged": GitFileStatusItem[];
    "untracked": GitFileStatusItem[];
    "hasChanges": boolean;
    "commitsAhead": number;
    "commitsBehind": number;

    /** Creates a new GitFileStatus instance. */
    constructor($$source: Partial<GitFileStatus> = {}) {
        if (!("branch" in $$source)) {
            this["branch"] = "";
        }
        if (!("staged" in $$source)) {
            this["staged"] = [];
        }
        if (!("unstaged" in $$source)) {
            this["unstaged"] = [];
        }
        if (!("untracked" in $$source)) {
            this["untracked"] = [];
        }
        if (!("hasChanges" in $$source)) {
            this["hasChanges"] = false;
        }
        if (!("commitsAhead" in $$source)) {
            this["commitsAhead"] = 0;
        }
        if (!("commitsBehind" in $$source)) {
            this["commitsBehind"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GitFileStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): GitFileStatus {
        const $$createField1_0 = $$createType1;
        const $$createField2_0 = $$createType1;
        const $$createField3_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("staged" in $$parsedSource) {
            $$parsedSource["staged"] = $$createField1_0($$parsedSource["staged"]);
        }
        if ("unstaged" in $$parsedSource) {
            $$parsedSource["unstaged"] = $$createField2_0($$parsedSource["unstaged"]);
        }
        if ("untracked" in $$parsedSource) {
            $$parsedSource["untracked"] = $$createField3_0($$parsedSource["untracked"]);
        }
        return new GitFileStatus($$parsedSource as Partial<GitFileStatus>);
    }
}

/**
 * GitFileStatusItem represents the status of a single file in the git working tree.
 */
export class GitFileStatusItem {
    /**
     * Relative path from workspace root
     */
    "path": string;

    /**
     * "staged", "unstaged", "untracked"
     */
    "status": string;

    /**
     * Git porcelain format code (e.g., "M ", " M", "??", "A ")
     */
    "porcelainCode": string;

    /** Creates a new GitFileStatusItem instance. */
    constructor($$source: Partial<GitFileStatusItem> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("porcelainCode" in $$source)) {
            this["porcelainCode"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GitFileStatusItem instance from a string or object.
     */
    static createFrom($$source: any = {}): GitFileStatusItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GitFileStatusItem($$parsedSource as Partial<GitFileStatusItem>);
    }
}

/**
 * GitWorkspaceStatus describes the Git-level state of a workspace on disk. This is the
 * primary shape that the frontend will consume to decide which CTAs to show
 * (init, publish, link, etc).
 */
export class GitWorkspaceStatus {
    "gitAvailable": boolean;
    "isGitRepo": boolean;
    "hasRemote": boolean;
    "remoteUrl"?: string;

    /**
     * ConfiguredRemoteUrl is the workspace's server-authoritative git remote,
     * read from the DB independently of git availability. When git is missing
     * this is the only way the UI can tell the user the workspace is supposed
     * to be linked (and therefore its files cannot sync until git is installed).
     */
    "configuredRemoteUrl"?: string;

    /** Creates a new GitWorkspaceStatus instance. */
    constructor($$source: Partial<GitWorkspaceStatus> = {}) {
        if (!("gitAvailable" in $$source)) {
            this["gitAvailable"] = false;
        }
        if (!("isGitRepo" in $$source)) {
            this["isGitRepo"] = false;
        }
        if (!("hasRemote" in $$source)) {
            this["hasRemote"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GitWorkspaceStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): GitWorkspaceStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GitWorkspaceStatus($$parsedSource as Partial<GitWorkspaceStatus>);
    }
}

/**
 * InitAndPublishParams defines the input for initializing a local git repo for
 * a workspace and preparing it for publication to GitHub. The actual GitHub
 * repository creation will be delegated to the remote backend in a later step.
 */
export class InitAndPublishParams {
    "repoName": string;

    /**
     * "public" or "private"
     */
    "visibility": string;
    "remoteUrl"?: string;

    /** Creates a new InitAndPublishParams instance. */
    constructor($$source: Partial<InitAndPublishParams> = {}) {
        if (!("repoName" in $$source)) {
            this["repoName"] = "";
        }
        if (!("visibility" in $$source)) {
            this["visibility"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InitAndPublishParams instance from a string or object.
     */
    static createFrom($$source: any = {}): InitAndPublishParams {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new InitAndPublishParams($$parsedSource as Partial<InitAndPublishParams>);
    }
}

export class LinkExistingParams {
    "remoteUrl": string;

    /** Creates a new LinkExistingParams instance. */
    constructor($$source: Partial<LinkExistingParams> = {}) {
        if (!("remoteUrl" in $$source)) {
            this["remoteUrl"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LinkExistingParams instance from a string or object.
     */
    static createFrom($$source: any = {}): LinkExistingParams {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LinkExistingParams($$parsedSource as Partial<LinkExistingParams>);
    }
}

export class LinkStatus {
    "scenario": string;
    "branch": string;

    /** Creates a new LinkStatus instance. */
    constructor($$source: Partial<LinkStatus> = {}) {
        if (!("scenario" in $$source)) {
            this["scenario"] = "";
        }
        if (!("branch" in $$source)) {
            this["branch"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LinkStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): LinkStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LinkStatus($$parsedSource as Partial<LinkStatus>);
    }
}

export enum ReconcileAction {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ReconcileNoop = "noop",
    ReconcileLinked = "linked",
    ReconcileSwitched = "switched",
    ReconcileUnlinked = "unlinked",
};

/**
 * ReconcileResult describes what reconcile did so the caller can rebuild the
 * graph and surface a transparent notification to the user.
 */
export class ReconcileResult {
    "action": ReconcileAction;
    "changed": boolean;
    "remoteUrl": string;
    "backupPath": string;
    "backupRef": string;

    /** Creates a new ReconcileResult instance. */
    constructor($$source: Partial<ReconcileResult> = {}) {
        if (!("action" in $$source)) {
            this["action"] = ReconcileAction.$zero;
        }
        if (!("changed" in $$source)) {
            this["changed"] = false;
        }
        if (!("remoteUrl" in $$source)) {
            this["remoteUrl"] = "";
        }
        if (!("backupPath" in $$source)) {
            this["backupPath"] = "";
        }
        if (!("backupRef" in $$source)) {
            this["backupRef"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReconcileResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ReconcileResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReconcileResult($$parsedSource as Partial<ReconcileResult>);
    }
}

/**
 * RevertFileParams defines the input for reverting changes to a file.
 */
export class RevertFileParams {
    /**
     * Relative path from workspace root
     */
    "path": string;

    /** Creates a new RevertFileParams instance. */
    constructor($$source: Partial<RevertFileParams> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RevertFileParams instance from a string or object.
     */
    static createFrom($$source: any = {}): RevertFileParams {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RevertFileParams($$parsedSource as Partial<RevertFileParams>);
    }
}

/**
 * StageFileParams defines the input for staging a file.
 */
export class StageFileParams {
    /**
     * Relative path from workspace root
     */
    "path": string;

    /** Creates a new StageFileParams instance. */
    constructor($$source: Partial<StageFileParams> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StageFileParams instance from a string or object.
     */
    static createFrom($$source: any = {}): StageFileParams {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StageFileParams($$parsedSource as Partial<StageFileParams>);
    }
}

/**
 * SwitchBranchParams defines the input for switching branches.
 */
export class SwitchBranchParams {
    "branchName": string;

    /** Creates a new SwitchBranchParams instance. */
    constructor($$source: Partial<SwitchBranchParams> = {}) {
        if (!("branchName" in $$source)) {
            this["branchName"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SwitchBranchParams instance from a string or object.
     */
    static createFrom($$source: any = {}): SwitchBranchParams {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SwitchBranchParams($$parsedSource as Partial<SwitchBranchParams>);
    }
}

/**
 * UnstageFileParams defines the input for unstaging a file.
 */
export class UnstageFileParams {
    /**
     * Relative path from workspace root
     */
    "path": string;

    /** Creates a new UnstageFileParams instance. */
    constructor($$source: Partial<UnstageFileParams> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UnstageFileParams instance from a string or object.
     */
    static createFrom($$source: any = {}): UnstageFileParams {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UnstageFileParams($$parsedSource as Partial<UnstageFileParams>);
    }
}

// Private type creation functions
const $$createType0 = GitFileStatusItem.createFrom;
const $$createType1 = $Create.Array($$createType0);
