// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export {
    CustomRule,
    LintConfigEntry,
    LintRuleConfig
} from "./models.js";

export type {
    LintFile
} from "./models.js";
