// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * CustomRule is a user-defined regexp-based lint rule.
 */
export class CustomRule {
    "id": string;

    /**
     * "off", "hint", "warning", "error"
     */
    "severity": string;
    "message": string;
    "pattern": string;

    /** Creates a new CustomRule instance. */
    constructor($$source: Partial<CustomRule> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("severity" in $$source)) {
            this["severity"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("pattern" in $$source)) {
            this["pattern"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CustomRule instance from a string or object.
     */
    static createFrom($$source: any = {}): CustomRule {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CustomRule($$parsedSource as Partial<CustomRule>);
    }
}

/**
 * LintConfigEntry is a single entry in the flat config array.
 * Entries without Files apply globally. Ignores-only entries skip matching files entirely.
 */
export class LintConfigEntry {
    "files"?: string[];
    "ignores"?: string[];
    "rules"?: { [_ in string]?: LintRuleConfig };
    "custom"?: CustomRule[];

    /** Creates a new LintConfigEntry instance. */
    constructor($$source: Partial<LintConfigEntry> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LintConfigEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): LintConfigEntry {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType2;
        const $$createField3_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("files" in $$parsedSource) {
            $$parsedSource["files"] = $$createField0_0($$parsedSource["files"]);
        }
        if ("ignores" in $$parsedSource) {
            $$parsedSource["ignores"] = $$createField1_0($$parsedSource["ignores"]);
        }
        if ("rules" in $$parsedSource) {
            $$parsedSource["rules"] = $$createField2_0($$parsedSource["rules"]);
        }
        if ("custom" in $$parsedSource) {
            $$parsedSource["custom"] = $$createField3_0($$parsedSource["custom"]);
        }
        return new LintConfigEntry($$parsedSource as Partial<LintConfigEntry>);
    }
}

/**
 * LintFile is the ordered list of config entries parsed from a .lint file.
 */
export type LintFile = LintConfigEntry[];

/**
 * LintRuleConfig holds a severity override for a built-in rule.
 * Accepts either a plain string ("off") or a tuple (["warning", {...}]) for forward compatibility.
 */
export class LintRuleConfig {
    "Severity": string;

    /** Creates a new LintRuleConfig instance. */
    constructor($$source: Partial<LintRuleConfig> = {}) {
        if (!("Severity" in $$source)) {
            this["Severity"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LintRuleConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): LintRuleConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LintRuleConfig($$parsedSource as Partial<LintRuleConfig>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = LintRuleConfig.createFrom;
const $$createType2 = $Create.Map($Create.Any, $$createType1);
const $$createType3 = CustomRule.createFrom;
const $$createType4 = $Create.Array($$createType3);
