// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as Workspace from "./workspace.js";
export {
    Workspace
};

export {
    CreateWorkspaceParams,
    LastFolder,
    OpenFolderResult,
    OpenFolderState,
    SearchUserResult,
    WorkspaceUserEntry,
    WorkspaceUserGroup,
    WorkspaceUserRole,
    WorkspaceWithCurrent
} from "./models.js";
