// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class CreateWorkspaceParams {
    "ID": string;
    "WorkspaceToUserID": string;
    "UserID": string;
    "Name": string;

    /** Creates a new CreateWorkspaceParams instance. */
    constructor($$source: Partial<CreateWorkspaceParams> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = "";
        }
        if (!("WorkspaceToUserID" in $$source)) {
            this["WorkspaceToUserID"] = "";
        }
        if (!("UserID" in $$source)) {
            this["UserID"] = "";
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateWorkspaceParams instance from a string or object.
     */
    static createFrom($$source: any = {}): CreateWorkspaceParams {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CreateWorkspaceParams($$parsedSource as Partial<CreateWorkspaceParams>);
    }
}

export class SearchUserResult {
    "found": boolean;
    "user_id"?: string;
    "name"?: string | null;
    "email": string;
    "already_added": boolean;

    /** Creates a new SearchUserResult instance. */
    constructor($$source: Partial<SearchUserResult> = {}) {
        if (!("found" in $$source)) {
            this["found"] = false;
        }
        if (!("email" in $$source)) {
            this["email"] = "";
        }
        if (!("already_added" in $$source)) {
            this["already_added"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchUserResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SearchUserResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SearchUserResult($$parsedSource as Partial<SearchUserResult>);
    }
}

export class SetOrCreateCurrentWorkspaceParams {
    "UserID": string;

    /** Creates a new SetOrCreateCurrentWorkspaceParams instance. */
    constructor($$source: Partial<SetOrCreateCurrentWorkspaceParams> = {}) {
        if (!("UserID" in $$source)) {
            this["UserID"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SetOrCreateCurrentWorkspaceParams instance from a string or object.
     */
    static createFrom($$source: any = {}): SetOrCreateCurrentWorkspaceParams {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SetOrCreateCurrentWorkspaceParams($$parsedSource as Partial<SetOrCreateCurrentWorkspaceParams>);
    }
}

export class WorkspaceUserEntry {
    "id": string;
    "name": string | null;
    "email": string | null;
    "roles": WorkspaceUserRole[];
    "groups": WorkspaceUserGroup[];
    "is_owner": boolean;

    /** Creates a new WorkspaceUserEntry instance. */
    constructor($$source: Partial<WorkspaceUserEntry> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = null;
        }
        if (!("email" in $$source)) {
            this["email"] = null;
        }
        if (!("roles" in $$source)) {
            this["roles"] = [];
        }
        if (!("groups" in $$source)) {
            this["groups"] = [];
        }
        if (!("is_owner" in $$source)) {
            this["is_owner"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkspaceUserEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkspaceUserEntry {
        const $$createField3_0 = $$createType1;
        const $$createField4_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("roles" in $$parsedSource) {
            $$parsedSource["roles"] = $$createField3_0($$parsedSource["roles"]);
        }
        if ("groups" in $$parsedSource) {
            $$parsedSource["groups"] = $$createField4_0($$parsedSource["groups"]);
        }
        return new WorkspaceUserEntry($$parsedSource as Partial<WorkspaceUserEntry>);
    }
}

export class WorkspaceUserGroup {
    "id": string;
    "name": string;
    "user_to_group_id": string;

    /** Creates a new WorkspaceUserGroup instance. */
    constructor($$source: Partial<WorkspaceUserGroup> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("user_to_group_id" in $$source)) {
            this["user_to_group_id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkspaceUserGroup instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkspaceUserGroup {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorkspaceUserGroup($$parsedSource as Partial<WorkspaceUserGroup>);
    }
}

export class WorkspaceUserRole {
    "id": string;
    "name": string;
    "user_to_role_id": string;

    /** Creates a new WorkspaceUserRole instance. */
    constructor($$source: Partial<WorkspaceUserRole> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("user_to_role_id" in $$source)) {
            this["user_to_role_id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkspaceUserRole instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkspaceUserRole {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorkspaceUserRole($$parsedSource as Partial<WorkspaceUserRole>);
    }
}

/**
 * WorkspaceWithCurrent is a workspace entry with a current flag for the UI.
 * Logo is the base64 of a 128x128 PNG, empty when the workspace has none; the
 * UI composes the data URL around it so a stored value can never bring its own
 * media type.
 */
export class WorkspaceWithCurrent {
    "id": string;
    "name": string;
    "logo": string;
    "current": boolean;

    /** Creates a new WorkspaceWithCurrent instance. */
    constructor($$source: Partial<WorkspaceWithCurrent> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("logo" in $$source)) {
            this["logo"] = "";
        }
        if (!("current" in $$source)) {
            this["current"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkspaceWithCurrent instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkspaceWithCurrent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorkspaceWithCurrent($$parsedSource as Partial<WorkspaceWithCurrent>);
    }
}

// Private type creation functions
const $$createType0 = WorkspaceUserRole.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = WorkspaceUserGroup.createFrom;
const $$createType3 = $Create.Array($$createType2);
