// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * FolderState is the status plus whatever its screen needs to say something
 * specific.
 */
export class FolderState {
    "status": WorkspaceStatus;
    "path": string;

    /**
     * The folder's own name, offered as the workspace name on the setup screen.
     */
    "suggestedName"?: string;

    /**
     * Set when the config names a workspace this server does not have, so the
     * setup screen can say so rather than pretend the folder was never one.
     */
    "staleWorkspaceId"?: string;
    "folderServer"?: string;
    "currentServer"?: string;

    /** Creates a new FolderState instance. */
    constructor($$source: Partial<FolderState> = {}) {
        if (!("status" in $$source)) {
            this["status"] = WorkspaceStatus.$zero;
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FolderState instance from a string or object.
     */
    static createFrom($$source: any = {}): FolderState {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FolderState($$parsedSource as Partial<FolderState>);
    }
}

/**
 * LastFolder is what the no-folder screen offers to reopen.
 */
export class LastFolder {
    "path": string;
    "name": string;

    /** Creates a new LastFolder instance. */
    constructor($$source: Partial<LastFolder> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LastFolder instance from a string or object.
     */
    static createFrom($$source: any = {}): LastFolder {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LastFolder($$parsedSource as Partial<LastFolder>);
    }
}

export class SearchUserResult {
    "found": boolean;
    "user_id"?: string;
    "name"?: string | null;
    "email": string;
    "already_added": boolean;

    /** Creates a new SearchUserResult instance. */
    constructor($$source: Partial<SearchUserResult> = {}) {
        if (!("found" in $$source)) {
            this["found"] = false;
        }
        if (!("email" in $$source)) {
            this["email"] = "";
        }
        if (!("already_added" in $$source)) {
            this["already_added"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchUserResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SearchUserResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SearchUserResult($$parsedSource as Partial<SearchUserResult>);
    }
}

/**
 * WorkspaceStatus is what opening a folder found, and so which screen the
 * frontend owes the user next.
 */
export enum WorkspaceStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * Signed in, nothing open.
     */
    NoFolder = "no_folder",

    /**
     * The workspace is set up and the graph is built.
     */
    Ready = "ready",

    /**
     * No config, or one naming a workspace this server does not have.
     */
    NeedsSetup = "needs_setup",

    /**
     * The workspace lives on another server, whose permissions gate every query.
     */
    WrongServer = "wrong_server",
};

export class WorkspaceUserEntry {
    "id": string;
    "name": string | null;
    "email": string | null;
    "roles": WorkspaceUserRole[];
    "groups": WorkspaceUserGroup[];
    "is_owner": boolean;

    /** Creates a new WorkspaceUserEntry instance. */
    constructor($$source: Partial<WorkspaceUserEntry> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = null;
        }
        if (!("email" in $$source)) {
            this["email"] = null;
        }
        if (!("roles" in $$source)) {
            this["roles"] = [];
        }
        if (!("groups" in $$source)) {
            this["groups"] = [];
        }
        if (!("is_owner" in $$source)) {
            this["is_owner"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkspaceUserEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkspaceUserEntry {
        const $$createField3_0 = $$createType1;
        const $$createField4_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("roles" in $$parsedSource) {
            $$parsedSource["roles"] = $$createField3_0($$parsedSource["roles"]);
        }
        if ("groups" in $$parsedSource) {
            $$parsedSource["groups"] = $$createField4_0($$parsedSource["groups"]);
        }
        return new WorkspaceUserEntry($$parsedSource as Partial<WorkspaceUserEntry>);
    }
}

export class WorkspaceUserGroup {
    "id": string;
    "name": string;
    "user_to_group_id": string;

    /** Creates a new WorkspaceUserGroup instance. */
    constructor($$source: Partial<WorkspaceUserGroup> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("user_to_group_id" in $$source)) {
            this["user_to_group_id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkspaceUserGroup instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkspaceUserGroup {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorkspaceUserGroup($$parsedSource as Partial<WorkspaceUserGroup>);
    }
}

export class WorkspaceUserRole {
    "id": string;
    "name": string;
    "user_to_role_id": string;

    /** Creates a new WorkspaceUserRole instance. */
    constructor($$source: Partial<WorkspaceUserRole> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("user_to_role_id" in $$source)) {
            this["user_to_role_id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkspaceUserRole instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkspaceUserRole {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorkspaceUserRole($$parsedSource as Partial<WorkspaceUserRole>);
    }
}

// Private type creation functions
const $$createType0 = WorkspaceUserRole.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = WorkspaceUserGroup.createFrom;
const $$createType3 = $Create.Array($$createType2);
