// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AddUserToWorkspace(email: string): $CancellablePromise<void> {
    return $Call.ByID(2010975648, email);
}

/**
 * CloseFolder leaves the user signed in on the no-folder screen. The folder on
 * disk is untouched.
 */
export function CloseFolder(): $CancellablePromise<void> {
    return $Call.ByID(2005530750);
}

/**
 * CreateWorkspaceInFolder creates the workspace on the server, writes the config
 * that names it, and opens it. An empty name defaults to the folder's.
 */
export function CreateWorkspaceInFolder(path: string, name: string): $CancellablePromise<$models.FolderState> {
    return $Call.ByID(1466431544, path, name).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * DeleteWorkspace removes the workspace on the server, its local rows, and the
 * select.config.json that named it. The folder is left as it was.
 * 
 * A config can outlive its workspace when the delete happened on another
 * machine; the init screen cleans that up on the next open.
 */
export function DeleteWorkspace(workspaceID: string): $CancellablePromise<void> {
    return $Call.ByID(1009480846, workspaceID);
}

/**
 * ListFolders returns every workspace this user has a folder for, the one that
 * was open first. A remembered path that no longer names its workspace is
 * forgotten rather than offered.
 */
export function ListFolders(): $CancellablePromise<$models.Folder[]> {
    return $Call.ByID(3511278583).then(($result: any) => {
        return $$createType2($result);
    });
}

export function ListWorkspaceUsers(): $CancellablePromise<$models.WorkspaceUserEntry[]> {
    return $Call.ByID(2078216013).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * OpenFolder is the only thing that sets up a workspace: not login, not sync.
 */
export function OpenFolder(path: string): $CancellablePromise<$models.FolderState> {
    return $Call.ByID(2229533346, path).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * PickFolder returns "" when the user cancels.
 */
export function PickFolder(): $CancellablePromise<string> {
    return $Call.ByID(2753062023);
}

export function RemoveUserFromWorkspace(userID: string): $CancellablePromise<void> {
    return $Call.ByID(3038059970, userID);
}

/**
 * ReopenLastFolder runs after login, so a returning user skips the picker.
 */
export function ReopenLastFolder(): $CancellablePromise<$models.FolderState> {
    return $Call.ByID(80028743).then(($result: any) => {
        return $$createType0($result);
    });
}

export function SearchUser(email: string): $CancellablePromise<$models.SearchUserResult | null> {
    return $Call.ByID(2043344285, email).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * UpdateLogo uploads a logo, then mirrors what the server stored — the
 * re-encoded image, not the caller's bytes — into the local database. Teammates
 * get it on their next pull, since the endpoint bumps updated_at.
 * 
 * The local write is untracked (@no-track in the query): the sync path does not
 * carry the logo column, so a tracked one would queue a commit that never applies.
 */
export function UpdateLogo(workspaceID: string, logo: string): $CancellablePromise<void> {
    return $Call.ByID(3908011900, workspaceID, logo);
}

export function UpdateName(workspaceID: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(1330736336, workspaceID, name);
}

// Private type creation functions
const $$createType0 = $models.FolderState.createFrom;
const $$createType1 = $models.Folder.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $models.WorkspaceUserEntry.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $models.SearchUserResult.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
