// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as generated$0 from "../db/generated/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AddUserToWorkspace(email: string): $CancellablePromise<void> {
    return $Call.ByID(2010975648, email);
}

export function CreateWorkspace(params: $models.CreateWorkspaceParams): $CancellablePromise<generated$0.Workspace> {
    return $Call.ByID(1706524711, params).then(($result: any) => {
        return $$createType0($result);
    });
}

export function CreateWorkspaceAndReload(name: string): $CancellablePromise<void> {
    return $Call.ByID(2601939573, name);
}

/**
 * DeleteWorkspace deletes the workspace on the server then removes it locally.
 * If the deleted workspace was current and ReloadHooks is set, runs switch-or-logout.
 * Returns (loggedOut, nil) when the user had no workspaces left and was logged out, (false, nil) otherwise, or (false, err) on error.
 */
export function DeleteWorkspace(workspaceID: string): $CancellablePromise<void> {
    return $Call.ByID(1009480846, workspaceID);
}

/**
 * Ensures the workspace root folder exists on disk
 */
export function EnsureWorkspaceFolderByID(workspaceID: string, $1: string): $CancellablePromise<void> {
    return $Call.ByID(1961383445, workspaceID, $1);
}

export function ListWorkspaceUsers(): $CancellablePromise<$models.WorkspaceUserEntry[]> {
    return $Call.ByID(2078216013).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * ListWorkspacesForCurrentUser returns all workspaces for the current user (from workspace_to_user).
 */
export function ListWorkspacesForCurrentUser(): $CancellablePromise<$models.WorkspaceWithCurrent[]> {
    return $Call.ByID(1919920487).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * RemoveLogo clears the workspace logo on the server, then locally.
 */
export function RemoveLogo(workspaceID: string): $CancellablePromise<void> {
    return $Call.ByID(393921065, workspaceID);
}

export function RemoveUserFromWorkspace(userID: string): $CancellablePromise<void> {
    return $Call.ByID(3038059970, userID);
}

/**
 * RemoveWorkspaceFolderByID deletes the workspace root directory on disk.
 * Safe to call if the folder does not exist (no error).
 */
export function RemoveWorkspaceFolderByID(workspaceID: string): $CancellablePromise<void> {
    return $Call.ByID(436077763, workspaceID);
}

export function SearchUser(email: string): $CancellablePromise<$models.SearchUserResult | null> {
    return $Call.ByID(2043344285, email).then(($result: any) => {
        return $$createType6($result);
    });
}

export function SetOrCreateCurrentWorkspace(params: $models.SetOrCreateCurrentWorkspaceParams): $CancellablePromise<generated$0.Workspace> {
    return $Call.ByID(3116085253, params).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SwitchWorkspace sets the current workspace for the current user, ensures its folder exists,
 * rebuilds the workspace graph, and emits workspaceGraphUpdated when ReloadHooks is set.
 */
export function SwitchWorkspace(workspaceID: string): $CancellablePromise<void> {
    return $Call.ByID(1184707179, workspaceID);
}

/**
 * UpdateLogo uploads a workspace logo through the backend, then mirrors what the
 * server stored into the local database.
 * 
 * The server is the one that validates and re-encodes the image, so the value
 * written locally is the server's, not the caller's. The local write is
 * deliberately untracked (@no-track): a tracked UPDATE would queue a mutation
 * commit and push the logo back up the sync path, which does not carry the
 * column. Teammates receive it on their next pull instead, because the endpoint
 * bumps the workspace's updated_at.
 */
export function UpdateLogo(workspaceID: string, logo: string): $CancellablePromise<void> {
    return $Call.ByID(3908011900, workspaceID, logo);
}

export function UpdateName(workspaceID: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(1330736336, workspaceID, name);
}

// Private type creation functions
const $$createType0 = generated$0.Workspace.createFrom;
const $$createType1 = $models.WorkspaceUserEntry.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $models.WorkspaceWithCurrent.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $models.SearchUserResult.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
