// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CreateHistory(params: $models.CreateQueryHistoryParams): $CancellablePromise<void> {
    return $Call.ByID(896448342, params);
}

/**
 * ListHistory returns recorded statements for a workspace from the last 7 days,
 * newest first, paginated by limit/offset.
 */
export function ListHistory(params: $models.ListHistoryParams): $CancellablePromise<$models.HistoryEntry[]> {
    return $Call.ByID(1113387086, params).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * PruneOnStartup clears stale history once at launch: rows older than 7 days
 * and anything beyond the newest 100 per workspace. Best-effort and silent.
 */
export function PruneOnStartup(): $CancellablePromise<void> {
    return $Call.ByID(534181776);
}

// Private type creation functions
const $$createType0 = $models.HistoryEntry.createFrom;
const $$createType1 = $Create.Array($$createType0);
