// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class CreateQueryHistoryParams {
    "Dsn": string;
    "Uri": string;
    "WorkspaceID": string;
    "DbInstanceID": string;
    "Statement": string;
    "AffectedRows": number | null;
    "RowCount": number | null;
    "DurationMs": number | null;
    "Errors": string[];

    /** Creates a new CreateQueryHistoryParams instance. */
    constructor($$source: Partial<CreateQueryHistoryParams> = {}) {
        if (!("Dsn" in $$source)) {
            this["Dsn"] = "";
        }
        if (!("Uri" in $$source)) {
            this["Uri"] = "";
        }
        if (!("WorkspaceID" in $$source)) {
            this["WorkspaceID"] = "";
        }
        if (!("DbInstanceID" in $$source)) {
            this["DbInstanceID"] = "";
        }
        if (!("Statement" in $$source)) {
            this["Statement"] = "";
        }
        if (!("AffectedRows" in $$source)) {
            this["AffectedRows"] = null;
        }
        if (!("RowCount" in $$source)) {
            this["RowCount"] = null;
        }
        if (!("DurationMs" in $$source)) {
            this["DurationMs"] = null;
        }
        if (!("Errors" in $$source)) {
            this["Errors"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateQueryHistoryParams instance from a string or object.
     */
    static createFrom($$source: any = {}): CreateQueryHistoryParams {
        const $$createField8_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Errors" in $$parsedSource) {
            $$parsedSource["Errors"] = $$createField8_0($$parsedSource["Errors"]);
        }
        return new CreateQueryHistoryParams($$parsedSource as Partial<CreateQueryHistoryParams>);
    }
}

/**
 * HistoryEntry is the frontend-facing shape of a recorded statement. The
 * database name/type are intentionally omitted: the frontend resolves them
 * from the workspace graph via DbInstanceID so renamed/removed instances stay
 * in sync instead of showing a stale snapshot.
 */
export class HistoryEntry {
    "id": string;
    "statement": string;
    "affectedRows": number | null;
    "rowCount": number | null;
    "durationMs": number | null;
    "errors": string[];
    "workspaceId": string;
    "dbInstanceId": string;
    "createdAt": string;

    /** Creates a new HistoryEntry instance. */
    constructor($$source: Partial<HistoryEntry> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("statement" in $$source)) {
            this["statement"] = "";
        }
        if (!("affectedRows" in $$source)) {
            this["affectedRows"] = null;
        }
        if (!("rowCount" in $$source)) {
            this["rowCount"] = null;
        }
        if (!("durationMs" in $$source)) {
            this["durationMs"] = null;
        }
        if (!("errors" in $$source)) {
            this["errors"] = [];
        }
        if (!("workspaceId" in $$source)) {
            this["workspaceId"] = "";
        }
        if (!("dbInstanceId" in $$source)) {
            this["dbInstanceId"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HistoryEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): HistoryEntry {
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("errors" in $$parsedSource) {
            $$parsedSource["errors"] = $$createField5_0($$parsedSource["errors"]);
        }
        return new HistoryEntry($$parsedSource as Partial<HistoryEntry>);
    }
}

export class ListHistoryParams {
    "workspaceId": string;
    "limit": number;
    "offset": number;

    /** Creates a new ListHistoryParams instance. */
    constructor($$source: Partial<ListHistoryParams> = {}) {
        if (!("workspaceId" in $$source)) {
            this["workspaceId"] = "";
        }
        if (!("limit" in $$source)) {
            this["limit"] = 0;
        }
        if (!("offset" in $$source)) {
            this["offset"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ListHistoryParams instance from a string or object.
     */
    static createFrom($$source: any = {}): ListHistoryParams {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ListHistoryParams($$parsedSource as Partial<ListHistoryParams>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
