// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as core$0 from "../../../github.com/selectDb/dialect/core/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as graph$0 from "../graph/models.js";

/**
 * CompleteResult is the completion response returned to the caller.
 */
export class CompleteResult {
    "id": string;
    "candidates": CompletionCandidate[];
    "errors": string[];

    /** Creates a new CompleteResult instance. */
    constructor($$source: Partial<CompleteResult> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("candidates" in $$source)) {
            this["candidates"] = [];
        }
        if (!("errors" in $$source)) {
            this["errors"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CompleteResult instance from a string or object.
     */
    static createFrom($$source: any = {}): CompleteResult {
        const $$createField1_0 = $$createType1;
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("candidates" in $$parsedSource) {
            $$parsedSource["candidates"] = $$createField1_0($$parsedSource["candidates"]);
        }
        if ("errors" in $$parsedSource) {
            $$parsedSource["errors"] = $$createField2_0($$parsedSource["errors"]);
        }
        return new CompleteResult($$parsedSource as Partial<CompleteResult>);
    }
}

/**
 * CompletionCandidate wraps a core.Candidate with a Monaco-specific kind integer.
 */
export class CompletionCandidate {
    "Type": core$0.CandidateType;

    /**
     * Display text shown in completion list
     */
    "Text": string;

    /**
     * Text to insert (may contain snippet placeholders like $1, $0)
     */
    "InsertText": string;
    "Definition": string;
    "Comment": string;

    /**
     * Monaco completion item kind
     */
    "kind": number;

    /** Creates a new CompletionCandidate instance. */
    constructor($$source: Partial<CompletionCandidate> = {}) {
        if (!("Type" in $$source)) {
            this["Type"] = core$0.CandidateType.$zero;
        }
        if (!("Text" in $$source)) {
            this["Text"] = "";
        }
        if (!("InsertText" in $$source)) {
            this["InsertText"] = "";
        }
        if (!("Definition" in $$source)) {
            this["Definition"] = "";
        }
        if (!("Comment" in $$source)) {
            this["Comment"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CompletionCandidate instance from a string or object.
     */
    static createFrom($$source: any = {}): CompletionCandidate {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CompletionCandidate($$parsedSource as Partial<CompletionCandidate>);
    }
}

/**
 * HoverResult contains markdown for the hovered identifier.
 */
export class HoverResult {
    "markdown": string;

    /** Creates a new HoverResult instance. */
    constructor($$source: Partial<HoverResult> = {}) {
        if (!("markdown" in $$source)) {
            this["markdown"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HoverResult instance from a string or object.
     */
    static createFrom($$source: any = {}): HoverResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HoverResult($$parsedSource as Partial<HoverResult>);
    }
}

/**
 * LintDiagnostic is a serialisable diagnostic with Monaco-compatible severity.
 */
export class LintDiagnostic {
    "ruleId": string;

    /**
     * 8=Error, 4=Warning, 1=Hint (Monaco MarkerSeverity)
     */
    "severity": number;
    "message": string;
    "startLine": number;
    "startCol": number;
    "endLine": number;
    "endCol": number;

    /** Creates a new LintDiagnostic instance. */
    constructor($$source: Partial<LintDiagnostic> = {}) {
        if (!("ruleId" in $$source)) {
            this["ruleId"] = "";
        }
        if (!("severity" in $$source)) {
            this["severity"] = 0;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("startLine" in $$source)) {
            this["startLine"] = 0;
        }
        if (!("startCol" in $$source)) {
            this["startCol"] = 0;
        }
        if (!("endLine" in $$source)) {
            this["endLine"] = 0;
        }
        if (!("endCol" in $$source)) {
            this["endCol"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LintDiagnostic instance from a string or object.
     */
    static createFrom($$source: any = {}): LintDiagnostic {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LintDiagnostic($$parsedSource as Partial<LintDiagnostic>);
    }
}

/**
 * LintResult is the lint response returned to the frontend.
 */
export class LintResult {
    "id": string;
    "diagnostics": LintDiagnostic[];
    "errors": string[];

    /** Creates a new LintResult instance. */
    constructor($$source: Partial<LintResult> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("diagnostics" in $$source)) {
            this["diagnostics"] = [];
        }
        if (!("errors" in $$source)) {
            this["errors"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LintResult instance from a string or object.
     */
    static createFrom($$source: any = {}): LintResult {
        const $$createField1_0 = $$createType4;
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("diagnostics" in $$parsedSource) {
            $$parsedSource["diagnostics"] = $$createField1_0($$parsedSource["diagnostics"]);
        }
        if ("errors" in $$parsedSource) {
            $$parsedSource["errors"] = $$createField2_0($$parsedSource["errors"]);
        }
        return new LintResult($$parsedSource as Partial<LintResult>);
    }
}

/**
 * PositionParams identifies a caret position inside a SQL file/buffer.
 */
export class PositionParams {
    "DbInstanceID": string;

    /**
     * optional; enables variable substitution
     */
    "FileID": string;
    "SQL": string;
    "Line": number;
    "Column": number;

    /** Creates a new PositionParams instance. */
    constructor($$source: Partial<PositionParams> = {}) {
        if (!("DbInstanceID" in $$source)) {
            this["DbInstanceID"] = "";
        }
        if (!("FileID" in $$source)) {
            this["FileID"] = "";
        }
        if (!("SQL" in $$source)) {
            this["SQL"] = "";
        }
        if (!("Line" in $$source)) {
            this["Line"] = 0;
        }
        if (!("Column" in $$source)) {
            this["Column"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PositionParams instance from a string or object.
     */
    static createFrom($$source: any = {}): PositionParams {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PositionParams($$parsedSource as Partial<PositionParams>);
    }
}

/**
 * ResolveResult is returned by Resolve for ItemInfoModal navigation.
 */
export class ResolveResult {
    "node"?: graph$0.DBInstanceItemNode | null;
    "found": boolean;
    "kind": string;

    /** Creates a new ResolveResult instance. */
    constructor($$source: Partial<ResolveResult> = {}) {
        if (!("found" in $$source)) {
            this["found"] = false;
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResolveResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ResolveResult {
        const $$createField0_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("node" in $$parsedSource) {
            $$parsedSource["node"] = $$createField0_0($$parsedSource["node"]);
        }
        return new ResolveResult($$parsedSource as Partial<ResolveResult>);
    }
}

// Private type creation functions
const $$createType0 = CompletionCandidate.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = LintDiagnostic.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = graph$0.DBInstanceItemNode.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
