// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Close(): $CancellablePromise<void> {
    return $Call.ByID(2789191454);
}

/**
 * Complete returns SQL completion candidates for the identifier at the cursor.
 */
export function Complete(p: $models.PositionParams): $CancellablePromise<$models.CompleteResult> {
    return $Call.ByID(2455691337, p).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Hover returns brief markdown for the identifier at the cursor.
 */
export function Hover(p: $models.PositionParams): $CancellablePromise<$models.HoverResult> {
    return $Call.ByID(1253443172, p).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Lint analyses the SQL in p and returns a list of diagnostics.
 */
export function Lint(p: $models.PositionParams): $CancellablePromise<$models.LintResult> {
    return $Call.ByID(3660577331, p).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * Resolve returns the graph node ID for the identifier at the cursor.
 */
export function Resolve(p: $models.PositionParams): $CancellablePromise<$models.ResolveResult> {
    return $Call.ByID(3814333666, p).then(($result: any) => {
        return $$createType3($result);
    });
}

// Private type creation functions
const $$createType0 = $models.CompleteResult.createFrom;
const $$createType1 = $models.HoverResult.createFrom;
const $$createType2 = $models.LintResult.createFrom;
const $$createType3 = $models.ResolveResult.createFrom;
