// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelAccessTokenPolling() {
  return window['go']['auth']['GithubAuth']['CancelAccessTokenPolling']();
}

export function GetAccessToken(arg1) {
  return window['go']['auth']['GithubAuth']['GetAccessToken'](arg1);
}

export function GetDeviceCode() {
  return window['go']['auth']['GithubAuth']['GetDeviceCode']();
}

export function SetContext(arg1) {
  return window['go']['auth']['GithubAuth']['SetContext'](arg1);
}
