// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {auth} from '../models';
import {context} from '../models';

export function CancelAccessTokenPolling():Promise<void>;

export function GetAccessToken(arg1:string):Promise<void>;

export function GetDeviceCode():Promise<auth.DeviceCodeResponse>;

export function SetContext(arg1:context.Context):Promise<void>;
